# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mrpc-mt5-error.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("mrpc-mt5-error.proto", :syntax => :proto3) do
    add_message "mt5_term_api.Error" do
      optional :type, :enum, 1, "mt5_term_api.ErrorType"
      optional :error_code, :string, 2
      optional :error_message, :string, 3
      optional :mql_error_code, :enum, 4, "mt5_term_api.MqlErrorCode"
      optional :mql_error_int_code, :int32, 5
      optional :mql_error_description, :string, 6
      optional :mql_error_trade_code, :enum, 7, "mt5_term_api.MqlErrorTradeCode"
      optional :mql_error_trade_int_code, :int32, 8
      optional :mql_error_trade_description, :string, 9
      optional :stack_trace, :string, 10
      optional :command_type_name, :string, 11
      optional :commandId, :int64, 12
      repeated :properties, :message, 13, "mt5_term_api.ErrorProperty"
    end
    add_message "mt5_term_api.ErrorProperty" do
      optional :error_arg_key, :string, 1
      optional :error_arg_value, :string, 2
    end
    add_message "mt5_term_api.LogFileInfo" do
      optional :log_type, :enum, 1, "mt5_term_api.LogType"
      optional :full_path, :string, 2
      optional :name, :string, 3
      optional :content, :string, 4
    end
    add_enum "mt5_term_api.ErrorType" do
      value :UNDEFINED, 0
      value :MRPC, 1
      value :MRPC_VALIDATION, 2
      value :MRPC_TIMEOUT, 3
      value :TERMINAL_API_TIMEOUT, 4
      value :TERMINAL_API_GET_PARAMS, 5
      value :TERMINAL_API_SET_RESULT, 6
      value :TERMINAL_API_UNEXPECTED, 7
      value :MQL_EXECUTION, 8
      value :MQL_CUSTOM_EXECUTION, 9
      value :MQL_TRADE_EXECUTION, 10
    end
    add_enum "mt5_term_api.LogType" do
      value :Global, 0
      value :MQL5, 1
      value :MQL4, 2
    end
    add_enum "mt5_term_api.MqlErrorCode" do
      value :ERR_SUCCESS, 0
      value :ERR_INTERNAL_ERROR, 4001
      value :ERR_WRONG_INTERNAL_PARAMETER, 4002
      value :ERR_INVALID_PARAMETER, 4003
      value :ERR_NOT_ENOUGH_MEMORY, 4004
      value :ERR_STRUCT_WITHOBJECTS_ORCLASS, 4005
      value :ERR_INVALID_ARRAY, 4006
      value :ERR_ARRAY_RESIZE_ERROR, 4007
      value :ERR_STRING_RESIZE_ERROR, 4008
      value :ERR_NOTINITIALIZED_STRING, 4009
      value :ERR_INVALID_DATETIME, 4010
      value :ERR_ARRAY_BAD_SIZE, 4011
      value :ERR_INVALID_POINTER, 4012
      value :ERR_INVALID_POINTER_TYPE, 4013
      value :ERR_FUNCTION_NOT_ALLOWED, 4014
      value :ERR_RESOURCE_NAME_DUPLICATED, 4015
      value :ERR_RESOURCE_NOT_FOUND, 4016
      value :ERR_RESOURCE_UNSUPPORTED_TYPE, 4017
      value :ERR_RESOURCE_NAME_IS_TOO_LONG, 4018
      value :ERR_MATH_OVERFLOW, 4019
      value :ERR_SLEEP_ERROR, 4020
      value :ERR_PROGRAM_STOPPED, 4022
      value :ERR_INVALID_TYPE, 4023
      value :ERR_INVALID_HANDLE, 4024
      value :ERR_TOO_MANY_OBJECTS, 4025
      value :ERR_CHART_WRONG_ID, 4101
      value :ERR_CHART_NO_REPLY, 4102
      value :ERR_CHART_NOT_FOUND, 4103
      value :ERR_CHART_NO_EXPERT, 4104
      value :ERR_CHART_CANNOT_OPEN, 4105
      value :ERR_CHART_CANNOT_CHANGE, 4106
      value :ERR_CHART_WRONG_PARAMETER, 4107
      value :ERR_CHART_CANNOT_CREATE_TIMER, 4108
      value :ERR_CHART_WRONG_PROPERTY, 4109
      value :ERR_CHART_SCREENSHOT_FAILED, 4110
      value :ERR_CHART_NAVIGATE_FAILED, 4111
      value :ERR_CHART_TEMPLATE_FAILED, 4112
      value :ERR_CHART_WINDOW_NOT_FOUND, 4113
      value :ERR_CHART_INDICATOR_CANNOT_ADD, 4114
      value :ERR_CHART_INDICATOR_CANNOT_DEL, 4115
      value :ERR_CHART_INDICATOR_NOT_FOUND, 4116
      value :ERR_OBJECT_ERROR, 4201
      value :ERR_OBJECT_NOT_FOUND, 4202
      value :ERR_OBJECT_WRONG_PROPERTY, 4203
      value :ERR_OBJECT_GETDATE_FAILED, 4204
      value :ERR_OBJECT_GETVALUE_FAILED, 4205
      value :ERR_MARKET_UNKNOWN_SYMBOL, 4301
      value :ERR_MARKET_NOT_SELECTED, 4302
      value :ERR_MARKET_WRONG_PROPERTY, 4303
      value :ERR_MARKET_LASTTIME_UNKNOWN, 4304
      value :ERR_MARKET_SELECT_ERROR, 4305
      value :ERR_MARKET_SELECT_LIMIT, 4306
      value :ERR_MARKET_SESSION_INDEX, 4307
      value :ERR_HISTORY_NOT_FOUND, 4401
      value :ERR_HISTORY_WRONG_PROPERTY, 4402
      value :ERR_HISTORY_TIMEOUT, 4403
      value :ERR_HISTORY_BARS_LIMIT, 4404
      value :ERR_HISTORY_LOAD_ERRORS, 4405
      value :ERR_HISTORY_SMALL_BUFFER, 4407
      value :ERR_GLOBALVARIABLE_NOT_FOUND, 4501
      value :ERR_GLOBALVARIABLE_EXISTS, 4502
      value :ERR_GLOBALVARIABLE_NOT_MODIFIED, 4503
      value :ERR_GLOBALVARIABLE_CANNOTREAD, 4504
      value :ERR_GLOBALVARIABLE_CANNOTWRITE, 4505
      value :ERR_MAIL_SEND_FAILED, 4510
      value :ERR_PLAY_SOUND_FAILED, 4511
      value :ERR_MQL5_WRONG_PROPERTY, 4512
      value :ERR_TERMINAL_WRONG_PROPERTY, 4513
      value :ERR_FTP_SEND_FAILED, 4514
      value :ERR_NOTIFICATION_SEND_FAILED, 4515
      value :ERR_NOTIFICATION_WRONG_PARAMETER, 4516
      value :ERR_NOTIFICATION_WRONG_SETTINGS, 4517
      value :ERR_NOTIFICATION_TOO_FREQUENT, 4518
      value :ERR_FTP_NOSERVER, 4519
      value :ERR_FTP_NOLOGIN, 4520
      value :ERR_FTP_FILE_ERROR, 4521
      value :ERR_FTP_CONNECT_FAILED, 4522
      value :ERR_FTP_CHANGEDIR, 4523
      value :ERR_BUFFERS_NO_MEMORY, 4601
      value :ERR_BUFFERS_WRONG_INDEX, 4602
      value :ERR_CUSTOM_WRONG_PROPERTY, 4603
      value :ERR_ACCOUNT_WRONG_PROPERTY, 4701
      value :ERR_TRADE_WRONG_PROPERTY, 4751
      value :ERR_TRADE_DISABLED, 4752
      value :ERR_TRADE_POSITION_NOT_FOUND, 4753
      value :ERR_TRADE_ORDER_NOT_FOUND, 4754
      value :ERR_TRADE_DEAL_NOT_FOUND, 4755
      value :ERR_TRADE_SEND_FAILED, 4756
      value :ERR_TRADE_CALC_FAILED, 4758
      value :ERR_INDICATOR_UNKNOWN_SYMBOL, 4801
      value :ERR_INDICATOR_CANNOT_CREATE, 4802
      value :ERR_INDICATOR_NO_MEMORY, 4803
      value :ERR_INDICATOR_CANNOT_APPLY, 4804
      value :ERR_INDICATOR_CANNOT_ADD, 4805
      value :ERR_INDICATOR_DATA_NOT_FOUND, 4806
      value :ERR_INDICATOR_WRONG_HANDLE, 4807
      value :ERR_INDICATOR_WRONG_PARAMETERS, 4808
      value :ERR_BOOKS_CANNOT_ADD, 4901
      value :ERR_BOOKS_CANNOT_DELETE, 4902
      value :ERR_BOOKS_CANNOT_GET, 4903
      value :ERR_BOOKS_CANNOT_SUBSCRIBE, 4904
      value :ERR_TOO_MANY_FILES, 5001
      value :ERR_WRONG_FILENAME, 5002
      value :ERR_TOO_LONG_FILENAME, 5003
      value :ERR_CANNOT_OPEN_FILE, 5004
      value :ERR_FILE_CACHEBUFFER_ERROR, 5005
      value :ERR_CANNOT_DELETE_FILE, 5006
      value :ERR_INVALID_FILEHANDLE, 5007
      value :ERR_WRONG_FILEHANDLE, 5008
      value :ERR_NO_STRING_DATE, 5030
      value :ERR_WRONG_STRING_DATE, 5031
      value :ERR_WRONG_STRING_TIME, 5032
      value :ERR_STRING_TIME_ERROR, 5033
      value :ERR_STRING_OUT_OF_MEMORY, 5034
      value :ERR_INCOMPATIBLE_ARRAYS, 5050
      value :ERR_SMALL_ASSERIES_ARRAY, 5051
      value :ERR_SMALL_ARRAY, 5052
      value :ERR_ZEROSIZE_ARRAY, 5053
      value :ERR_NUMBER_ARRAYS_ONLY, 5054
      value :ERR_OPENCL_NOT_SUPPORTED, 5100
      value :ERR_OPENCL_INTERNAL, 5101
      value :ERR_OPENCL_INVALID_HANDLE, 5102
      value :ERR_OPENCL_CONTEXT_CREATE, 5103
      value :ERR_OPENCL_QUEUE_CREATE, 5104
      value :ERR_OPENCL_PROGRAM_CREATE, 5105
      value :ERR_OPENCL_TOO_LONG_KERNEL_NAME, 5106
      value :ERR_OPENCL_KERNEL_CREATE, 5107
      value :ERR_OPENCL_SET_KERNEL_PARAMETER, 5108
      value :ERR_OPENCL_EXECUTE, 5109
      value :ERR_OPENCL_WRONG_BUFFER_SIZE, 5110
      value :ERR_OPENCL_WRONG_BUFFER_OFFSET, 5111
      value :ERR_OPENCL_BUFFER_CREATE, 5112
      value :ERR_OPENCL_TOO_MANY_OBJECTS, 5113
      value :ERR_OPENCL_SELECTDEVICE, 5114
      value :ERR_DATABASE_INTERNAL, 5120
      value :ERR_DATABASE_INVALID_HANDLE, 5121
      value :ERR_DATABASE_TOO_MANY_OBJECTS, 5122
      value :ERR_DATABASE_CONNECT, 5123
      value :ERR_DATABASE_EXECUTE, 5124
      value :ERR_DATABASE_PREPARE, 5125
      value :ERR_DATABASE_NO_MORE_DATA, 5126
      value :ERR_DATABASE_STEP, 5127
      value :ERR_DATABASE_NOT_READY, 5128
      value :ERR_DATABASE_BIND_PARAMETERS, 5129
      value :ERR_WEBREQUEST_INVALID_ADDRESS, 5200
      value :ERR_WEBREQUEST_CONNECT_FAILED, 5201
      value :ERR_WEBREQUEST_TIMEOUT, 5202
      value :ERR_WEBREQUEST_REQUEST_FAILED, 5203
      value :ERR_NETSOCKET_INVALIDHANDLE, 5270
      value :ERR_NETSOCKET_TOO_MANY_OPENED, 5271
      value :ERR_NETSOCKET_CANNOT_CONNECT, 5272
      value :ERR_NETSOCKET_IO_ERROR, 5273
      value :ERR_NETSOCKET_HANDSHAKE_FAILED, 5274
      value :ERR_NETSOCKET_NO_CERTIFICATE, 5275
      value :ERR_NOT_CUSTOM_SYMBOL, 5300
      value :ERR_CUSTOM_SYMBOL_WRONG_NAME, 5301
      value :ERR_CUSTOM_SYMBOL_NAME_LONG, 5302
      value :ERR_CUSTOM_SYMBOL_PATH_LONG, 5303
      value :ERR_CUSTOM_SYMBOL_EXIST, 5304
      value :ERR_CUSTOM_SYMBOL_ERROR, 5305
      value :ERR_CUSTOM_SYMBOL_SELECTED, 5306
      value :ERR_CUSTOM_SYMBOL_PROPERTY_WRONG, 5307
      value :ERR_CUSTOM_SYMBOL_PARAMETER_ERROR, 5308
      value :ERR_CUSTOM_SYMBOL_PARAMETER_LONG, 5309
      value :ERR_CUSTOM_TICKS_WRONG_ORDER, 5310
      value :ERR_CALENDAR_MORE_DATA, 5400
      value :ERR_CALENDAR_TIMEOUT, 5401
      value :ERR_CALENDAR_NO_DATA, 5402
      value :ERR_DATABASE_ERROR, 5601
      value :ERR_DATABASE_LOGIC, 5602
      value :ERR_DATABASE_PERM, 5603
      value :ERR_DATABASE_ABORT, 5604
      value :ERR_DATABASE_BUSY, 5605
      value :ERR_DATABASE_LOCKED, 5606
      value :ERR_DATABASE_NOMEM, 5607
      value :ERR_DATABASE_READONLY, 5608
      value :ERR_DATABASE_INTERRUPT, 5609
      value :ERR_DATABASE_IOERR, 5610
      value :ERR_DATABASE_CORRUPT, 5611
      value :ERR_DATABASE_NOTFOUND, 5612
      value :ERR_DATABASE_FULL, 5613
      value :ERR_DATABASE_CANTOPEN, 5614
      value :ERR_DATABASE_PROTOCOL, 5615
      value :ERR_DATABASE_EMPTY, 5616
      value :ERR_DATABASE_SCHEMA, 5617
      value :ERR_DATABASE_TOOBIG, 5618
      value :ERR_DATABASE_CONSTRAINT, 5619
      value :ERR_DATABASE_MISMATCH, 5620
      value :ERR_DATABASE_MISUSE, 5621
      value :ERR_DATABASE_NOLFS, 5622
      value :ERR_DATABASE_AUTH, 5623
      value :ERR_DATABASE_FORMAT, 5624
      value :ERR_DATABASE_RANGE, 5625
      value :ERR_DATABASE_NOTADB, 5626
      value :ERR_MATRIX_INTERNAL, 5700
      value :ERR_MATRIX_NOT_INITIALIZED, 5701
      value :ERR_MATRIX_INCONSISTENT, 5702
      value :ERR_MATRIX_INVALID_SIZE, 5703
      value :ERR_MATRIX_INVALID_TYPE, 5704
      value :ERR_MATRIX_FUNC_NOT_ALLOWED, 5705
      value :ERR_MATRIX_CONTAINS_NAN, 5706
      value :ERR_ONNX_INTERNAL, 5800
      value :ERR_ONNX_NOT_INITIALIZED, 5801
      value :ERR_ONNX_NOT_SUPPORTED, 5802
      value :ERR_ONNX_RUN_FAILED, 5803
      value :ERR_ONNX_INVALID_PARAMETERS_COUNT, 5804
      value :ERR_ONNX_INVALID_PARAMETER, 5805
      value :ERR_ONNX_INVALID_PARAMETER_TYPE, 5806
      value :ERR_ONNX_INVALID_PARAMETER_SIZE, 5807
      value :ERR_ONNX_WRONG_DIMENSION, 5808
      value :ERR_USER_ERROR_FIRST, 65536
    end
    add_enum "mt5_term_api.MqlErrorTradeCode" do
      value :TRADE_RETCODE_SUCCESS, 0
      value :TRADE_RETCODE_REQUOTE, 10004
      value :TRADE_RETCODE_REJECT, 10006
      value :TRADE_RETCODE_CANCEL, 10007
      value :TRADE_RETCODE_PLACED, 10008
      value :TRADE_RETCODE_DONE, 10009
      value :TRADE_RETCODE_DONE_PARTIAL, 10010
      value :TRADE_RETCODE_ERROR, 10011
      value :TRADE_RETCODE_TIMEOUT, 10012
      value :TRADE_RETCODE_INVALID, 10013
      value :TRADE_RETCODE_INVALID_VOLUME, 10014
      value :TRADE_RETCODE_INVALID_PRICE, 10015
      value :TRADE_RETCODE_INVALID_STOPS, 10016
      value :TRADE_RETCODE_TRADE_DISABLED, 10017
      value :TRADE_RETCODE_MARKET_CLOSED, 10018
      value :TRADE_RETCODE_NO_MONEY, 10019
      value :TRADE_RETCODE_PRICE_CHANGED, 10020
      value :TRADE_RETCODE_PRICE_OFF, 10021
      value :TRADE_RETCODE_INVALID_EXPIRATION, 10022
      value :TRADE_RETCODE_ORDER_CHANGED, 10023
      value :TRADE_RETCODE_TOO_MANY_REQUESTS, 10024
      value :TRADE_RETCODE_NO_CHANGES, 10025
      value :TRADE_RETCODE_SERVER_DISABLES_AT, 10026
      value :TRADE_RETCODE_CLIENT_DISABLES_AT, 10027
      value :TRADE_RETCODE_LOCKED, 10028
      value :TRADE_RETCODE_FROZEN, 10029
      value :TRADE_RETCODE_INVALID_FILL, 10030
      value :TRADE_RETCODE_CONNECTION, 10031
      value :TRADE_RETCODE_ONLY_REAL, 10032
      value :TRADE_RETCODE_LIMIT_ORDERS, 10033
      value :TRADE_RETCODE_LIMIT_VOLUME, 10034
      value :TRADE_RETCODE_INVALID_ORDER, 10035
      value :TRADE_RETCODE_POSITION_CLOSED, 10036
      value :TRADE_RETCODE_INVALID_CLOSE_VOLUME, 10038
      value :TRADE_RETCODE_CLOSE_ORDER_EXIST, 10039
      value :TRADE_RETCODE_LIMIT_POSITIONS, 10040
      value :TRADE_RETCODE_REJECT_CANCEL, 10041
      value :TRADE_RETCODE_LONG_ONLY, 10042
      value :TRADE_RETCODE_SHORT_ONLY, 10043
      value :TRADE_RETCODE_CLOSE_ONLY, 10044
      value :TRADE_RETCODE_FIFO_CLOSE, 10045
      value :TRADE_RETCODE_HEDGE_PROHIBITED, 10046
    end
  end
end

module Mt5TermApi
  Error = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.Error").msgclass
  ErrorProperty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ErrorProperty").msgclass
  LogFileInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.LogFileInfo").msgclass
  ErrorType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ErrorType").enummodule
  LogType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.LogType").enummodule
  MqlErrorCode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.MqlErrorCode").enummodule
  MqlErrorTradeCode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.MqlErrorTradeCode").enummodule
end
