# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mt5-term-api-account-helper.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'google/api/annotations_pb'
require 'mrpc-mt5-error_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("mt5-term-api-account-helper.proto", :syntax => :proto3) do
    add_message "mt5_term_api.AllHistoryOrdersRequest" do
      optional :inputSortMode, :enum, 1, "mt5_term_api.BMT5_ENUM_ORDER_HISTORY_SORT_TYPE"
      proto3_optional :inputFrom, :message, 2, "google.protobuf.Timestamp"
      proto3_optional :inputTo, :message, 3, "google.protobuf.Timestamp"
      proto3_optional :pageNumber, :int32, 4
      proto3_optional :itemsPerPage, :int32, 5
    end
    add_message "mt5_term_api.AllHistoryOrdersReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.AllHistoryOrdersData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.AllHistoryOrdersData" do
      optional :arrayTotal, :int32, 1
      optional :pageNumber, :int32, 2
      optional :itemsPerPage, :int32, 3
      repeated :history_orders, :message, 4, "mt5_term_api.HistoryOrderInfo"
    end
    add_message "mt5_term_api.HistoryOrderInfo" do
      optional :record_index, :int32, 1
      optional :ticket, :uint64, 2
      optional :time_setup, :message, 3, "google.protobuf.Timestamp"
      optional :type, :enum, 4, "mt5_term_api.BMT5_ENUM_ORDER_TYPE"
      optional :state, :enum, 5, "mt5_term_api.BMT5_ENUM_ORDER_STATE"
      optional :time_done, :message, 6, "google.protobuf.Timestamp"
      optional :expiration_time_type, :enum, 7, "mt5_term_api.BMT5_ENUM_ORDER_TYPE_TIME"
      optional :expiration_time, :message, 8, "google.protobuf.Timestamp"
      optional :filling_type, :enum, 9, "mt5_term_api.BMT5_ENUM_ORDER_TYPE_FILLING"
      optional :magic, :int64, 10
      optional :position_id, :int64, 11
      optional :position_by_id, :int64, 12
      optional :volume_initial, :double, 13
      optional :volume_current, :double, 14
      optional :price_open, :double, 15
      optional :sl, :double, 16
      optional :tp, :double, 17
      optional :price_current, :double, 18
      optional :stop_limit, :double, 19
      optional :symbol, :string, 20
      optional :comment, :string, 21
      optional :order_external_id_name, :string, 22
    end
    add_message "mt5_term_api.PositionsHistoryRequest" do
      optional :sort_type, :enum, 1, "mt5_term_api.AH_ENUM_POSITIONS_HISTORY_SORT_TYPE"
      proto3_optional :position_open_time_from, :message, 2, "google.protobuf.Timestamp"
      proto3_optional :position_open_time_to, :message, 3, "google.protobuf.Timestamp"
      proto3_optional :page_number, :int32, 4
      proto3_optional :items_per_page, :int32, 5
    end
    add_message "mt5_term_api.PositionsHistoryReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.PositionsHistoryData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.PositionsHistoryData" do
      repeated :history_positions, :message, 1, "mt5_term_api.PositionHistoryInfo"
    end
    add_message "mt5_term_api.PositionHistoryInfo" do
      optional :index, :int32, 1
      optional :position_ticket, :uint64, 2
      optional :order_type, :enum, 3, "mt5_term_api.AH_ENUM_POSITIONS_HISTORY_ORDER_TYPE"
      optional :open_time, :message, 4, "google.protobuf.Timestamp"
      optional :close_time, :message, 5, "google.protobuf.Timestamp"
      optional :volume, :double, 6
      optional :open_price, :double, 7
      optional :close_price, :double, 8
      optional :stop_loss, :double, 9
      optional :take_profit, :double, 10
      optional :market_value, :double, 11
      optional :commission, :double, 12
      optional :fee, :double, 13
      optional :profit, :double, 14
      optional :swap, :double, 15
      optional :comment, :string, 16
      optional :symbol, :string, 17
      optional :magic, :int64, 18
    end
    add_message "mt5_term_api.TickValueWithSizeRequest" do
      repeated :symbol_names, :string, 1
    end
    add_message "mt5_term_api.TickValueWithSizeReply" do
      optional :data, :message, 1, "mt5_term_api.TickValueWithSizeData"
      optional :error, :message, 2, "mt5_term_api.Error"
    end
    add_message "mt5_term_api.TickValueWithSizeData" do
      repeated :symbol_tick_size_infos, :message, 1, "mt5_term_api.TickSizeSymbol"
    end
    add_message "mt5_term_api.TickSizeSymbol" do
      optional :Index, :int32, 1
      optional :Name, :string, 2
      optional :TradeTickValue, :double, 3
      optional :TradeTickValueProfit, :double, 4
      optional :TradeTickValueLoss, :double, 5
      optional :TradeTickSize, :double, 6
      optional :TradeContractSize, :double, 7
    end
    add_message "mt5_term_api.OpenedOrdersTicketsRequest" do
    end
    add_message "mt5_term_api.OpenedOrdersTicketsReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.OpenedOrdersTicketsData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.OpenedOrdersTicketsData" do
      repeated :opened_orders_tickets, :int64, 1
      repeated :opened_position_tickets, :int64, 2
    end
    add_message "mt5_term_api.OpenedOrdersRequest" do
      optional :inputSortMode, :enum, 1, "mt5_term_api.BMT5_ENUM_OPENED_ORDER_SORT_TYPE"
    end
    add_message "mt5_term_api.OpenedOrdersReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.OpenedOrdersData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.OpenedOrdersData" do
      repeated :opened_orders, :message, 1, "mt5_term_api.OpenedOrderInfo"
      repeated :position_infos, :message, 2, "mt5_term_api.PositionInfo"
    end
    add_message "mt5_term_api.PositionInfo" do
      optional :index, :uint32, 1
      optional :ticket, :uint64, 2
      optional :open_time, :message, 3, "google.protobuf.Timestamp"
      optional :volume, :double, 4
      optional :price_open, :double, 5
      optional :stop_loss, :double, 6
      optional :take_profit, :double, 7
      optional :price_current, :double, 8
      optional :swap, :double, 9
      optional :profit, :double, 10
      optional :last_update_time, :message, 11, "google.protobuf.Timestamp"
      optional :type, :enum, 12, "mt5_term_api.BMT5_ENUM_POSITION_TYPE"
      optional :magic_number, :int64, 13
      optional :identifier, :int64, 14
      optional :reason, :enum, 15, "mt5_term_api.BMT5_ENUM_POSITION_REASON"
      optional :symbol, :string, 16
      optional :comment, :string, 17
      optional :external_id, :string, 18
      optional :position_commission, :double, 19
      optional :account_login, :int64, 20
    end
    add_message "mt5_term_api.OpenedOrderInfo" do
      optional :index, :uint32, 1
      optional :ticket, :uint64, 2
      optional :price_current, :double, 3
      optional :price_open, :double, 4
      optional :stop_limit, :double, 5
      optional :stop_loss, :double, 6
      optional :take_profit, :double, 7
      optional :volume_current, :double, 8
      optional :volume_initial, :double, 9
      optional :magic_number, :int64, 10
      optional :reason, :int32, 11
      optional :type, :enum, 12, "mt5_term_api.BMT5_ENUM_ORDER_TYPE"
      optional :state, :enum, 13, "mt5_term_api.BMT5_ENUM_ORDER_STATE"
      optional :time_expiration, :message, 14, "google.protobuf.Timestamp"
      optional :time_setup, :message, 15, "google.protobuf.Timestamp"
      optional :time_done, :message, 16, "google.protobuf.Timestamp"
      optional :type_filling, :enum, 17, "mt5_term_api.BMT5_ENUM_ORDER_TYPE_FILLING"
      optional :type_time, :enum, 18, "mt5_term_api.BMT5_ENUM_ORDER_TYPE_TIME"
      optional :position_id, :int64, 19
      optional :position_by_id, :int64, 20
      optional :symbol, :string, 21
      optional :external_id, :string, 22
      optional :comment, :string, 23
      optional :account_login, :int64, 24
    end
    add_message "mt5_term_api.OrderHistoryRequest" do
      optional :inputFrom, :message, 1, "google.protobuf.Timestamp"
      optional :inputTo, :message, 2, "google.protobuf.Timestamp"
      optional :inputSortMode, :enum, 3, "mt5_term_api.BMT5_ENUM_ORDER_HISTORY_SORT_TYPE"
      optional :pageNumber, :int32, 4
      optional :itemsPerPage, :int32, 5
    end
    add_message "mt5_term_api.OrderHistoryReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.OrdersHistoryData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.OrdersHistoryData" do
      optional :arrayTotal, :int32, 1
      optional :pageNumber, :int32, 2
      optional :itemsPerPage, :int32, 3
      repeated :history_data, :message, 4, "mt5_term_api.HistoryData"
    end
    add_message "mt5_term_api.HistoryData" do
      optional :index, :uint32, 1
      optional :history_order, :message, 2, "mt5_term_api.OrderHistoryData"
      optional :history_deal, :message, 3, "mt5_term_api.DealHistoryData"
    end
    add_message "mt5_term_api.DealHistoryData" do
      optional :ticket, :uint64, 1
      optional :profit, :double, 2
      optional :commission, :double, 3
      optional :fee, :double, 4
      optional :price, :double, 5
      optional :stop_loss, :double, 6
      optional :take_profit, :double, 7
      optional :swap, :double, 8
      optional :volume, :double, 9
      optional :entry_type, :enum, 10, "mt5_term_api.BMT5_ENUM_DEAL_ENTRY_TYPE"
      optional :time, :message, 11, "google.protobuf.Timestamp"
      optional :type, :enum, 12, "mt5_term_api.BMT5_ENUM_DEAL_TYPE"
      optional :reason, :enum, 13, "mt5_term_api.BMT5_ENUM_DEAL_REASON"
      optional :position_id, :uint64, 14
      optional :comment, :string, 15
      optional :symbol, :string, 16
      optional :external_id, :string, 17
      optional :account_login, :int64, 18
    end
    add_message "mt5_term_api.OrderHistoryData" do
      optional :ticket, :uint64, 1
      optional :setup_time, :message, 2, "google.protobuf.Timestamp"
      optional :done_time, :message, 3, "google.protobuf.Timestamp"
      optional :state, :enum, 4, "mt5_term_api.BMT5_ENUM_ORDER_STATE"
      optional :price_current, :double, 5
      optional :price_open, :double, 6
      optional :stop_limit, :double, 7
      optional :stop_loss, :double, 8
      optional :take_profit, :double, 9
      optional :volume_current, :double, 10
      optional :volume_initial, :double, 11
      optional :magic_number, :int64, 12
      optional :type, :enum, 13, "mt5_term_api.BMT5_ENUM_ORDER_TYPE"
      optional :time_expiration, :message, 14, "google.protobuf.Timestamp"
      optional :type_filling, :enum, 15, "mt5_term_api.BMT5_ENUM_ORDER_TYPE_FILLING"
      optional :type_time, :enum, 16, "mt5_term_api.BMT5_ENUM_ORDER_TYPE_TIME"
      optional :position_id, :uint64, 17
      optional :symbol, :string, 18
      optional :external_id, :string, 19
      optional :comment, :string, 20
      optional :account_login, :int64, 21
    end
    add_message "mt5_term_api.AccountSummaryRequest" do
    end
    add_message "mt5_term_api.AccountSummaryReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.AccountSummaryData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.AccountSummaryData" do
      optional :account_login, :int64, 1
      optional :account_balance, :double, 2
      optional :account_equity, :double, 3
      optional :account_user_name, :string, 4
      optional :account_leverage, :int64, 5
      optional :account_trade_mode, :enum, 6, "mt5_term_api.MrpcEnumAccountTradeMode"
      optional :account_company_name, :string, 7
      optional :account_currency, :string, 8
      optional :server_time, :message, 9, "google.protobuf.Timestamp"
      optional :utc_timezone_server_time_shift_minutes, :int64, 10
      optional :account_credit, :double, 11
    end
    add_message "mt5_term_api.SymbolParamsManyRequest" do
      proto3_optional :symbol_name, :string, 1
      proto3_optional :sort_type, :enum, 2, "mt5_term_api.AH_SYMBOL_PARAMS_MANY_SORT_TYPE"
      proto3_optional :page_number, :int32, 3
      proto3_optional :items_per_page, :int32, 4
    end
    add_message "mt5_term_api.SymbolParamsManyReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.SymbolParamsManyData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.SymbolParamsManyData" do
      repeated :symbol_infos, :message, 1, "mt5_term_api.SymbolParameters"
      optional :symbols_total, :int32, 2
      proto3_optional :page_number, :int32, 3
      proto3_optional :items_per_page, :int32, 4
    end
    add_message "mt5_term_api.SymbolParameters" do
      optional :name, :string, 1
      optional :bid, :double, 2
      optional :bid_high, :double, 3
      optional :bid_low, :double, 4
      optional :ask, :double, 5
      optional :ask_high, :double, 6
      optional :ask_low, :double, 7
      optional :last, :double, 8
      optional :last_high, :double, 9
      optional :last_low, :double, 10
      optional :volume_real, :double, 11
      optional :volume_high_real, :double, 12
      optional :volume_low_real, :double, 13
      optional :option_strike, :double, 14
      optional :point, :double, 15
      optional :trade_tick_value, :double, 16
      optional :trade_tick_value_profit, :double, 17
      optional :trade_tick_value_loss, :double, 18
      optional :trade_tick_size, :double, 19
      optional :trade_contract_size, :double, 20
      optional :trade_accrued_interest, :double, 21
      optional :trade_face_value, :double, 22
      optional :trade_liquidity_rate, :double, 23
      optional :volume_min, :double, 24
      optional :volume_max, :double, 25
      optional :volume_step, :double, 26
      optional :volume_limit, :double, 27
      optional :swap_long, :double, 28
      optional :swap_short, :double, 29
      optional :swap_sunday, :double, 30
      optional :swap_monday, :double, 31
      optional :swap_tuesday, :double, 32
      optional :swap_wednesday, :double, 33
      optional :swap_thursday, :double, 34
      optional :swap_friday, :double, 35
      optional :swap_saturday, :double, 36
      optional :margin_initial, :double, 37
      optional :margin_maintenance, :double, 38
      optional :session_volume, :double, 39
      optional :session_turnover, :double, 40
      optional :session_interest, :double, 41
      optional :session_buy_orders_volume, :double, 42
      optional :session_sell_orders_volume, :double, 43
      optional :session_open, :double, 44
      optional :session_close, :double, 45
      optional :session_aw, :double, 46
      optional :session_price_settlement, :double, 47
      optional :session_price_limit_min, :double, 48
      optional :session_price_limit_max, :double, 49
      optional :margin_hedged, :double, 50
      optional :price_change, :double, 51
      optional :price_volatility, :double, 52
      optional :price_theoretical, :double, 53
      optional :price_delta, :double, 54
      optional :price_theta, :double, 55
      optional :price_gamma, :double, 56
      optional :price_vega, :double, 57
      optional :price_rho, :double, 58
      optional :price_omega, :double, 59
      optional :price_sensitivity, :double, 60
      optional :sector, :enum, 61, "mt5_term_api.BMT5_ENUM_SYMBOL_SECTOR"
      optional :industry, :enum, 62, "mt5_term_api.BMT5_ENUM_SYMBOL_INDUSTRY"
      optional :custom, :bool, 63
      optional :background_color, :string, 64
      optional :chart_mode, :enum, 65, "mt5_term_api.BMT5_ENUM_SYMBOL_CHART_MODE"
      optional :exist, :bool, 66
      optional :select, :bool, 67
      optional :subscription_delay, :int32, 68
      optional :visible, :bool, 69
      optional :session_deals, :int64, 70
      optional :session_buy_orders, :int64, 71
      optional :session_sell_orders, :int64, 72
      optional :volume, :int64, 73
      optional :volume_high, :int64, 74
      optional :volume_low, :int64, 75
      optional :time, :message, 76, "google.protobuf.Timestamp"
      optional :time_msc, :int64, 77
      optional :digits, :int32, 78
      optional :spread_float, :bool, 79
      optional :spread, :int32, 80
      optional :ticks_book_depth, :int32, 81
      optional :trade_calc_mode, :enum, 82, "mt5_term_api.BMT5_ENUM_SYMBOL_CALC_MODE"
      optional :trade_mode, :enum, 83, "mt5_term_api.BMT5_ENUM_SYMBOL_TRADE_MODE"
      optional :start_time, :message, 84, "google.protobuf.Timestamp"
      optional :expiration_time, :message, 85, "google.protobuf.Timestamp"
      optional :trade_stops_level, :int32, 86
      optional :trade_freeze_level, :int32, 87
      optional :trade_exe_mode, :enum, 88, "mt5_term_api.BMT5_ENUM_SYMBOL_TRADE_EXECUTION"
      optional :swap_mode, :enum, 89, "mt5_term_api.BMT5_ENUM_SYMBOL_SWAP_MODE"
      optional :swap_rollover_3days, :enum, 90, "mt5_term_api.BMT5_ENUM_DAY_OF_WEEK"
      optional :margin_hedged_use_leg, :bool, 91
      optional :expiration_mode, :int32, 92
      repeated :filling_mode, :enum, 93, "mt5_term_api.BMT5_ENUM_ORDER_TYPE_FILLING"
      optional :order_mode, :enum, 94, "mt5_term_api.BMT5_ENUM_ORDER_TYPE"
      optional :order_gtc_mode, :enum, 95, "mt5_term_api.BMT5_ENUM_SYMBOL_ORDER_GTC_MODE"
      optional :option_mode, :enum, 96, "mt5_term_api.BMT5_ENUM_SYMBOL_OPTION_MODE"
      optional :option_right, :enum, 97, "mt5_term_api.BMT5_ENUM_SYMBOL_OPTION_RIGHT"
      optional :basis, :string, 98
      optional :category, :string, 99
      optional :country, :string, 100
      optional :sector_name, :string, 101
      optional :industry_name, :string, 102
      optional :currency_base, :string, 103
      optional :currency_profit, :string, 104
      optional :currency_margin, :string, 105
      optional :bank, :string, 106
      optional :sym_description, :string, 107
      optional :exchange, :string, 108
      optional :formula, :string, 109
      optional :isin, :string, 110
      optional :page, :string, 111
      optional :path, :string, 112
    end
    add_enum "mt5_term_api.AH_ENUM_POSITIONS_HISTORY_SORT_TYPE" do
      value :AH_POSITION_OPEN_TIME_ASC, 0
      value :AH_POSITION_OPEN_TIME_DESC, 1
      value :AH_POSITION_TICKET_ASC, 2
      value :AH_POSITION_TICKET_DESC, 3
    end
    add_enum "mt5_term_api.AH_ENUM_POSITIONS_HISTORY_ORDER_TYPE" do
      value :AH_ORDER_TYPE_BUY, 0
      value :AH_ORDER_TYPE_SELL, 1
      value :AH_ORDER_TYPE_BUY_LIMIT, 2
      value :AH_ORDER_TYPE_SELL_LIMIT, 3
      value :AH_ORDER_TYPE_BUY_STOP, 4
      value :AH_ORDER_TYPE_SELL_STOP, 5
      value :AH_ORDER_TYPE_BUY_STOP_LIMIT, 6
      value :AH_ORDER_TYPE_SELL_STOP_LIMIT, 7
      value :AH_ORDER_TYPE_CLOSE_BY, 8
    end
    add_enum "mt5_term_api.BMT5_ENUM_OPENED_ORDER_SORT_TYPE" do
      value :BMT5_OPENED_ORDER_SORT_BY_OPEN_TIME_ASC, 0
      value :BMT5_OPENED_ORDER_SORT_BY_OPEN_TIME_DESC, 1
      value :BMT5_OPENED_ORDER_SORT_BY_ORDER_TICKET_ID_ASC, 2
      value :BMT5_OPENED_ORDER_SORT_BY_ORDER_TICKET_ID_DESC, 3
    end
    add_enum "mt5_term_api.BMT5_ENUM_POSITION_TYPE" do
      value :BMT5_POSITION_TYPE_BUY, 0
      value :BMT5_POSITION_TYPE_SELL, 1
    end
    add_enum "mt5_term_api.BMT5_ENUM_POSITION_REASON" do
      value :BMT5_POSITION_REASON_CLIENT, 0
      value :BMT5_POSITION_REASON_MOBILE, 1
      value :BMT5_POSITION_REASON_WEB, 2
      value :BMT5_POSITION_REASON_EXPERT, 3
      value :ORDER_REASON_SL, 4
      value :ORDER_REASON_TP, 5
      value :ORDER_REASON_SO, 6
    end
    add_enum "mt5_term_api.BMT5_ENUM_ORDER_TYPE_TIME" do
      value :BMT5_ORDER_TIME_GTC, 0
      value :BMT5_ORDER_TIME_DAY, 1
      value :BMT5_ORDER_TIME_SPECIFIED, 2
      value :BMT5_ORDER_TIME_SPECIFIED_DAY, 3
    end
    add_enum "mt5_term_api.BMT5_ENUM_ORDER_TYPE_FILLING" do
      value :BMT5_ORDER_FILLING_FOK, 0
      value :BMT5_ORDER_FILLING_IOC, 1
      value :BMT5_ORDER_FILLING_BOC, 3
      value :BMT5_ORDER_FILLING_RETURN, 2
    end
    add_enum "mt5_term_api.BMT5_ENUM_ORDER_TYPE" do
      value :BMT5_ORDER_TYPE_BUY, 0
      value :BMT5_ORDER_TYPE_SELL, 1
      value :BMT5_ORDER_TYPE_BUY_LIMIT, 2
      value :BMT5_ORDER_TYPE_SELL_LIMIT, 3
      value :BMT5_ORDER_TYPE_BUY_STOP, 4
      value :BMT5_ORDER_TYPE_SELL_STOP, 5
      value :BMT5_ORDER_TYPE_BUY_STOP_LIMIT, 6
      value :BMT5_ORDER_TYPE_SELL_STOP_LIMIT, 7
      value :BMT5_ORDER_TYPE_CLOSE_BY, 8
    end
    add_enum "mt5_term_api.BMT5_ENUM_DEAL_REASON" do
      value :BMT5_DEAL_REASON_CLIENT, 0
      value :BMT5_DEAL_REASON_MOBILE, 1
      value :BMT5_DEAL_REASON_WEB, 2
      value :BMT5_DEAL_REASON_EXPERT, 3
      value :BMT5_DEAL_REASON_SL, 4
      value :BMT5_DEAL_REASON_TP, 5
      value :BMT5_DEAL_REASON_SO, 6
      value :BMT5_DEAL_REASON_ROLLOVER, 7
      value :BMT5_DEAL_REASON_VMARGIN, 8
      value :BMT5_DEAL_REASON_SPLIT, 9
      value :BMT5_DEAL_REASON_CORPORATE_ACTION, 10
    end
    add_enum "mt5_term_api.BMT5_ENUM_DEAL_TYPE" do
      value :BMT5_DEAL_TYPE_BUY, 0
      value :BMT5_DEAL_TYPE_SELL, 1
      value :BMT5_DEAL_TYPE_BALANCE, 2
      value :BMT5_DEAL_TYPE_CREDIT, 3
      value :BMT5_DEAL_TYPE_CHARGE, 4
      value :BMT5_DEAL_TYPE_CORRECTION, 5
      value :BMT5_DEAL_TYPE_BONUS, 6
      value :BMT5_DEAL_TYPE_COMMISSION, 7
      value :BMT5_DEAL_TYPE_COMMISSION_DAILY, 8
      value :BMT5_DEAL_TYPE_COMMISSION_MONTHLY, 9
      value :BMT5_DEAL_TYPE_COMMISSION_AGENT_DAILY, 10
      value :BMT5_DEAL_TYPE_COMMISSION_AGENT_MONTHLY, 11
      value :BMT5_DEAL_TYPE_INTEREST, 12
      value :BMT5_DEAL_TYPE_BUY_CANCELED, 13
      value :BMT5_DEAL_TYPE_SELL_CANCELED, 14
      value :BMT5_DEAL_DIVIDEND, 15
      value :BMT5_DEAL_DIVIDEND_FRANKED, 16
      value :BMT5_DEAL_TAX, 17
    end
    add_enum "mt5_term_api.BMT5_ENUM_DEAL_ENTRY_TYPE" do
      value :BMT5_DEAL_ENTRY_IN, 0
      value :BMT5_DEAL_ENTRY_OUT, 1
      value :BMT5_DEAL_ENTRY_INOUT, 2
      value :BMT5_DEAL_ENTRY_OUT_BY, 3
    end
    add_enum "mt5_term_api.BMT5_ENUM_ORDER_HISTORY_SORT_TYPE" do
      value :BMT5_SORT_BY_OPEN_TIME_ASC, 0
      value :BMT5_SORT_BY_OPEN_TIME_DESC, 1
      value :BMT5_SORT_BY_CLOSE_TIME_ASC, 2
      value :BMT5_SORT_BY_CLOSE_TIME_DESC, 3
      value :BMT5_SORT_BY_ORDER_TICKET_ID_ASC, 4
      value :BMT5_SORT_BY_ORDER_TICKET_ID_DESC, 5
    end
    add_enum "mt5_term_api.BMT5_ENUM_ORDER_STATE" do
      value :BMT5_ORDER_STATE_STARTED, 0
      value :BMT5_ORDER_STATE_PLACED, 1
      value :BMT5_ORDER_STATE_CANCELED, 2
      value :BMT5_ORDER_STATE_PARTIAL, 3
      value :BMT5_ORDER_STATE_FILLED, 4
      value :BMT5_ORDER_STATE_REJECTED, 5
      value :BMT5_ORDER_STATE_EXPIRED, 6
      value :BMT5_ORDER_STATE_REQUEST_ADD, 7
      value :BMT5_ORDER_STATE_REQUEST_MODIFY, 8
      value :BMT5_ORDER_STATE_REQUEST_CANCEL, 9
    end
    add_enum "mt5_term_api.MrpcEnumAccountTradeMode" do
      value :MRPC_ACCOUNT_TRADE_MODE_DEMO, 0
      value :MRPC_ACCOUNT_TRADE_MODE_CONTEST, 1
      value :MRPC_ACCOUNT_TRADE_MODE_REAL, 2
    end
    add_enum "mt5_term_api.AH_SYMBOL_PARAMS_MANY_SORT_TYPE" do
      value :AH_PARAMS_MANY_SORT_TYPE_SYMBOL_NAME_ASC, 0
      value :AH_PARAMS_MANY_SORT_TYPE_SYMBOL_NAME_DESC, 1
      value :AH_PARAMS_MANY_SORT_TYPE_MQL_INDEX_ASC, 2
      value :AH_PARAMS_MANY_SORT_TYPE_MQL_INDEX_DESC, 3
    end
    add_enum "mt5_term_api.BMT5_ENUM_SYMBOL_OPTION_RIGHT" do
      value :BMT5_SYMBOL_OPTION_RIGHT_CALL, 0
      value :BMT5_SYMBOL_OPTION_RIGHT_PUT, 1
    end
    add_enum "mt5_term_api.BMT5_ENUM_SYMBOL_OPTION_MODE" do
      value :BMT5_SYMBOL_OPTION_MODE_EUROPEAN, 0
      value :BMT5_SYMBOL_OPTION_MODE_AMERICAN, 1
    end
    add_enum "mt5_term_api.BMT5_ENUM_SYMBOL_ORDER_GTC_MODE" do
      value :BMT5_SYMBOL_ORDERS_GTC, 0
      value :BMT5_SYMBOL_ORDERS_DAILY, 1
      value :BMT5_SYMBOL_ORDERS_DAILY_EXCLUDING_STOPS, 2
    end
    add_enum "mt5_term_api.BMT5_ENUM_DAY_OF_WEEK" do
      value :BMT5_SUNDAY, 0
      value :BMT5_MONDAY, 1
      value :BMT5_TUESDAY, 2
      value :BMT5_WEDNESDAY, 3
      value :BMT5_THURSDAY, 4
      value :BMT5_FRIDAY, 5
      value :BMT5_SATURDAY, 6
    end
    add_enum "mt5_term_api.BMT5_ENUM_SYMBOL_SWAP_MODE" do
      value :BMT5_SYMBOL_SWAP_MODE_DISABLED, 0
      value :BMT5_SYMBOL_SWAP_MODE_POINTS, 1
      value :BMT5_SYMBOL_SWAP_MODE_CURRENCY_SYMBOL, 2
      value :BMT5_SYMBOL_SWAP_MODE_CURRENCY_MARGIN, 3
      value :BMT5_SYMBOL_SWAP_MODE_CURRENCY_DEPOSIT, 4
      value :BMT5_SYMBOL_SWAP_MODE_CURRENCY_PROFIT, 5
      value :BMT5_SYMBOL_SWAP_MODE_INTEREST_CURRENT, 6
      value :BMT5_SYMBOL_SWAP_MODE_INTEREST_OPEN, 7
      value :BMT5_SYMBOL_SWAP_MODE_REOPEN_CURRENT, 8
      value :BMT5_SYMBOL_SWAP_MODE_REOPEN_BID, 9
    end
    add_enum "mt5_term_api.BMT5_ENUM_SYMBOL_TRADE_EXECUTION" do
      value :BMT5_SYMBOL_TRADE_EXECUTION_REQUEST, 0
      value :BMT5_SYMBOL_TRADE_EXECUTION_INSTANT, 1
      value :BMT5_SYMBOL_TRADE_EXECUTION_MARKET, 2
      value :BMT5_SYMBOL_TRADE_EXECUTION_EXCHANGE, 3
    end
    add_enum "mt5_term_api.BMT5_ENUM_SYMBOL_TRADE_MODE" do
      value :BMT5_SYMBOL_TRADE_MODE_DISABLED, 0
      value :BMT5_SYMBOL_TRADE_MODE_LONGONLY, 1
      value :BMT5_SYMBOL_TRADE_MODE_SHORTONLY, 2
      value :BMT5_SYMBOL_TRADE_MODE_CLOSEONLY, 3
      value :BMT5_SYMBOL_TRADE_MODE_FULL, 4
    end
    add_enum "mt5_term_api.BMT5_ENUM_SYMBOL_CALC_MODE" do
      value :BMT5_SYMBOL_CALC_MODE_FOREX, 0
      value :BMT5_SYMBOL_CALC_MODE_FOREX_NO_LEVERAGE, 1
      value :BMT5_SYMBOL_CALC_MODE_FUTURES, 2
      value :BMT5_SYMBOL_CALC_MODE_CFD, 3
      value :BMT5_SYMBOL_CALC_MODE_CFDINDEX, 4
      value :BMT5_SYMBOL_CALC_MODE_CFDLEVERAGE, 5
      value :BMT5_SYMBOL_CALC_MODE_EXCH_STOCKS, 6
      value :BMT5_SYMBOL_CALC_MODE_EXCH_FUTURES, 7
      value :BMT5_SYMBOL_CALC_MODE_EXCH_FUTURES_FORTS, 8
      value :BMT5_SYMBOL_CALC_MODE_EXCH_BONDS, 9
      value :BMT5_SYMBOL_CALC_MODE_EXCH_STOCKS_MOEX, 10
      value :BMT5_SYMBOL_CALC_MODE_EXCH_BONDS_MOEX, 11
      value :BMT5_SYMBOL_CALC_MODE_SERV_COLLATERAL, 12
    end
    add_enum "mt5_term_api.BMT5_ENUM_SYMBOL_SECTOR" do
      value :BMT5_SECTOR_UNDEFINED, 0
      value :BMT5_SECTOR_BASIC_MATERIALS, 1
      value :BMT5_SECTOR_COMMUNICATION_SERVICES, 2
      value :BMT5_SECTOR_CONSUMER_CYCLICAL, 3
      value :BMT5_SECTOR_CONSUMER_DEFENSIVE, 4
      value :BMT5_SECTOR_CURRENCY, 5
      value :BMT5_SECTOR_CURRENCY_CRYPTO, 6
      value :BMT5_SECTOR_ENERGY, 7
      value :BMT5_SECTOR_FINANCIAL, 8
      value :BMT5_SECTOR_HEALTHCARE, 9
      value :BMT5_SECTOR_INDUSTRIALS, 10
      value :BMT5_SECTOR_REAL_ESTATE, 11
      value :BMT5_SECTOR_TECHNOLOGY, 12
      value :BMT5_SECTOR_UTILITIES, 13
    end
    add_enum "mt5_term_api.BMT5_ENUM_SYMBOL_CHART_MODE" do
      value :BMT5_SYMBOL_CHART_MODE_BID, 0
      value :BMT5_SYMBOL_CHART_MODE_LAST, 1
    end
    add_enum "mt5_term_api.BMT5_ENUM_SYMBOL_INDUSTRY" do
      value :BMT5_INDUSTRY_UNDEFINED, 0
      value :BMT5_INDUSTRY_AGRICULTURAL_INPUTS, 1
      value :BMT5_INDUSTRY_ALUMINIUM, 2
      value :BMT5_INDUSTRY_BUILDING_MATERIALS, 3
      value :BMT5_INDUSTRY_CHEMICALS, 4
      value :BMT5_INDUSTRY_COKING_COAL, 5
      value :BMT5_INDUSTRY_COPPER, 6
      value :BMT5_INDUSTRY_GOLD, 7
      value :BMT5_INDUSTRY_LUMBER_WOOD, 8
      value :BMT5_INDUSTRY_INDUSTRIAL_METALS, 9
      value :BMT5_INDUSTRY_PRECIOUS_METALS, 10
      value :BMT5_INDUSTRY_PAPER, 11
      value :BMT5_INDUSTRY_SILVER, 12
      value :BMT5_INDUSTRY_SPECIALTY_CHEMICALS, 13
      value :BMT5_INDUSTRY_STEEL, 14
      value :BMT5_INDUSTRY_ADVERTISING, 15
      value :BMT5_INDUSTRY_BROADCASTING, 16
      value :BMT5_INDUSTRY_GAMING_MULTIMEDIA, 17
      value :BMT5_INDUSTRY_ENTERTAINMENT, 18
      value :BMT5_INDUSTRY_INTERNET_CONTENT, 19
      value :BMT5_INDUSTRY_PUBLISHING, 20
      value :BMT5_INDUSTRY_TELECOM, 21
      value :BMT5_INDUSTRY_APPAREL_MANUFACTURING, 22
      value :BMT5_INDUSTRY_APPAREL_RETAIL, 23
      value :BMT5_INDUSTRY_AUTO_MANUFACTURERS, 24
      value :BMT5_INDUSTRY_AUTO_PARTS, 25
      value :BMT5_INDUSTRY_AUTO_DEALERSHIP, 26
      value :BMT5_INDUSTRY_DEPARTMENT_STORES, 27
      value :BMT5_INDUSTRY_FOOTWEAR_ACCESSORIES, 28
      value :BMT5_INDUSTRY_FURNISHINGS, 29
      value :BMT5_INDUSTRY_GAMBLING, 30
      value :BMT5_INDUSTRY_HOME_IMPROV_RETAIL, 31
      value :BMT5_INDUSTRY_INTERNET_RETAIL, 32
      value :BMT5_INDUSTRY_LEISURE, 33
      value :BMT5_INDUSTRY_LODGING, 34
      value :BMT5_INDUSTRY_LUXURY_GOODS, 35
      value :BMT5_INDUSTRY_PACKAGING_CONTAINERS, 36
      value :BMT5_INDUSTRY_PERSONAL_SERVICES, 37
      value :BMT5_INDUSTRY_RECREATIONAL_VEHICLES, 38
      value :BMT5_INDUSTRY_RESIDENT_CONSTRUCTION, 39
      value :BMT5_INDUSTRY_RESORTS_CASINOS, 40
      value :BMT5_INDUSTRY_RESTAURANTS, 41
      value :BMT5_INDUSTRY_SPECIALTY_RETAIL, 42
      value :BMT5_INDUSTRY_TEXTILE_MANUFACTURING, 43
      value :BMT5_INDUSTRY_TRAVEL_SERVICES, 44
      value :BMT5_INDUSTRY_BEVERAGES_BREWERS, 45
      value :BMT5_INDUSTRY_BEVERAGES_NON_ALCO, 46
      value :BMT5_INDUSTRY_BEVERAGES_WINERIES, 47
      value :BMT5_INDUSTRY_CONFECTIONERS, 48
      value :BMT5_INDUSTRY_DISCOUNT_STORES, 49
      value :BMT5_INDUSTRY_EDUCATION_TRAINIG, 50
      value :BMT5_INDUSTRY_FARM_PRODUCTS, 51
      value :BMT5_INDUSTRY_FOOD_DISTRIBUTION, 52
      value :BMT5_INDUSTRY_GROCERY_STORES, 53
      value :BMT5_INDUSTRY_HOUSEHOLD_PRODUCTS, 54
      value :BMT5_INDUSTRY_PACKAGED_FOODS, 55
      value :BMT5_INDUSTRY_TOBACCO, 56
      value :BMT5_INDUSTRY_OIL_GAS_DRILLING, 57
      value :BMT5_INDUSTRY_OIL_GAS_EP, 58
      value :BMT5_INDUSTRY_OIL_GAS_EQUIPMENT, 59
      value :BMT5_INDUSTRY_OIL_GAS_INTEGRATED, 60
      value :BMT5_INDUSTRY_OIL_GAS_MIDSTREAM, 61
      value :BMT5_INDUSTRY_OIL_GAS_REFINING, 62
      value :BMT5_INDUSTRY_THERMAL_COAL, 63
      value :BMT5_INDUSTRY_URANIUM, 64
      value :BMT5_INDUSTRY_EXCHANGE_TRADED_FUND, 65
      value :BMT5_INDUSTRY_ASSETS_MANAGEMENT, 66
      value :BMT5_INDUSTRY_BANKS_DIVERSIFIED, 67
      value :BMT5_INDUSTRY_BANKS_REGIONAL, 68
      value :BMT5_INDUSTRY_CAPITAL_MARKETS, 69
      value :BMT5_INDUSTRY_CLOSE_END_FUND_DEBT, 70
      value :BMT5_INDUSTRY_CLOSE_END_FUND_EQUITY, 71
      value :BMT5_INDUSTRY_CLOSE_END_FUND_FOREIGN, 72
      value :BMT5_INDUSTRY_CREDIT_SERVICES, 73
      value :BMT5_INDUSTRY_FINANCIAL_CONGLOMERATE, 74
      value :BMT5_INDUSTRY_FINANCIAL_DATA_EXCHANGE, 75
      value :BMT5_INDUSTRY_INSURANCE_BROKERS, 76
      value :BMT5_INDUSTRY_INSURANCE_DIVERSIFIED, 77
      value :BMT5_INDUSTRY_INSURANCE_LIFE, 78
      value :BMT5_INDUSTRY_INSURANCE_PROPERTY, 79
      value :BMT5_INDUSTRY_INSURANCE_REINSURANCE, 80
      value :BMT5_INDUSTRY_INSURANCE_SPECIALTY, 81
      value :BMT5_INDUSTRY_MORTGAGE_FINANCE, 82
      value :BMT5_INDUSTRY_SHELL_COMPANIES, 83
      value :BMT5_INDUSTRY_BIOTECHNOLOGY, 84
      value :BMT5_INDUSTRY_DIAGNOSTICS_RESEARCH, 85
      value :BMT5_INDUSTRY_DRUGS_MANUFACTURERS, 86
      value :BMT5_INDUSTRY_DRUGS_MANUFACTURERS_SPEC, 87
      value :BMT5_INDUSTRY_HEALTHCARE_PLANS, 88
      value :BMT5_INDUSTRY_HEALTH_INFORMATION, 89
      value :BMT5_INDUSTRY_MEDICAL_FACILITIES, 90
      value :BMT5_INDUSTRY_MEDICAL_DEVICES, 91
      value :BMT5_INDUSTRY_MEDICAL_DISTRIBUTION, 92
      value :BMT5_INDUSTRY_MEDICAL_INSTRUMENTS, 93
      value :BMT5_INDUSTRY_PHARM_RETAILERS, 94
      value :BMT5_INDUSTRY_AEROSPACE_DEFENSE, 95
      value :BMT5_INDUSTRY_AIRLINES, 96
      value :BMT5_INDUSTRY_AIRPORTS_SERVICES, 97
      value :BMT5_INDUSTRY_BUILDING_PRODUCTS, 98
      value :BMT5_INDUSTRY_BUSINESS_EQUIPMENT, 99
      value :BMT5_INDUSTRY_CONGLOMERATES, 100
      value :BMT5_INDUSTRY_CONSULTING_SERVICES, 101
      value :BMT5_INDUSTRY_ELECTRICAL_EQUIPMENT, 102
      value :BMT5_INDUSTRY_ENGINEERING_CONSTRUCTION, 103
      value :BMT5_INDUSTRY_FARM_HEAVY_MACHINERY, 104
      value :BMT5_INDUSTRY_INDUSTRIAL_DISTRIBUTION, 105
      value :BMT5_INDUSTRY_INFRASTRUCTURE_OPERATIONS, 106
      value :BMT5_INDUSTRY_FREIGHT_LOGISTICS, 107
      value :BMT5_INDUSTRY_MARINE_SHIPPING, 108
      value :BMT5_INDUSTRY_METAL_FABRICATION, 109
      value :BMT5_INDUSTRY_POLLUTION_CONTROL, 110
      value :BMT5_INDUSTRY_RAILROADS, 111
      value :BMT5_INDUSTRY_RENTAL_LEASING, 112
      value :BMT5_INDUSTRY_SECURITY_PROTECTION, 113
      value :BMT5_INDUSTRY_SPEALITY_BUSINESS_SERVICES, 114
      value :BMT5_INDUSTRY_SPEALITY_MACHINERY, 115
      value :BMT5_INDUSTRY_STUFFING_EMPLOYMENT, 116
      value :BMT5_INDUSTRY_TOOLS_ACCESSORIES, 117
      value :BMT5_INDUSTRY_TRUCKING, 118
      value :BMT5_INDUSTRY_WASTE_MANAGEMENT, 119
      value :BMT5_INDUSTRY_REAL_ESTATE_DEVELOPMENT, 120
      value :BMT5_INDUSTRY_REAL_ESTATE_DIVERSIFIED, 121
      value :BMT5_INDUSTRY_REAL_ESTATE_SERVICES, 122
      value :BMT5_INDUSTRY_REIT_DIVERSIFIED, 123
      value :BMT5_INDUSTRY_REIT_HEALTCARE, 124
      value :BMT5_INDUSTRY_REIT_HOTEL_MOTEL, 125
      value :BMT5_INDUSTRY_REIT_INDUSTRIAL, 126
      value :BMT5_INDUSTRY_REIT_MORTAGE, 127
      value :BMT5_INDUSTRY_REIT_OFFICE, 128
      value :BMT5_INDUSTRY_REIT_RESIDENTAL, 129
      value :BMT5_INDUSTRY_REIT_RETAIL, 130
      value :BMT5_INDUSTRY_REIT_SPECIALITY, 131
      value :BMT5_INDUSTRY_COMMUNICATION_EQUIPMENT, 132
      value :BMT5_INDUSTRY_COMPUTER_HARDWARE, 133
      value :BMT5_INDUSTRY_CONSUMER_ELECTRONICS, 134
      value :BMT5_INDUSTRY_ELECTRONIC_COMPONENTS, 135
      value :BMT5_INDUSTRY_ELECTRONIC_DISTRIBUTION, 136
      value :BMT5_INDUSTRY_IT_SERVICES, 137
      value :BMT5_INDUSTRY_SCIENTIFIC_INSTRUMENTS, 138
      value :BMT5_INDUSTRY_SEMICONDUCTOR_EQUIPMENT, 139
      value :BMT5_INDUSTRY_SEMICONDUCTORS, 140
      value :BMT5_INDUSTRY_SOFTWARE_APPLICATION, 141
      value :BMT5_INDUSTRY_SOFTWARE_INFRASTRUCTURE, 142
      value :BMT5_INDUSTRY_SOLAR, 143
      value :BMT5_INDUSTRY_UTILITIES_DIVERSIFIED, 144
      value :BMT5_INDUSTRY_UTILITIES_POWERPRODUCERS, 145
      value :BMT5_INDUSTRY_UTILITIES_RENEWABLE, 146
      value :BMT5_INDUSTRY_UTILITIES_REGULATED_ELECTRIC, 147
      value :BMT5_INDUSTRY_UTILITIES_REGULATED_GAS, 148
      value :BMT5_INDUSTRY_UTILITIES_REGULATED_WATER, 149
      value :BMT5_INDUSTRY_UTILITIES_FIRST, 150
      value :BMT5_INDUSTRY_UTILITIES_LAST, 151
    end
  end
end

module Mt5TermApi
  AllHistoryOrdersRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.AllHistoryOrdersRequest").msgclass
  AllHistoryOrdersReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.AllHistoryOrdersReply").msgclass
  AllHistoryOrdersData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.AllHistoryOrdersData").msgclass
  HistoryOrderInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.HistoryOrderInfo").msgclass
  PositionsHistoryRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.PositionsHistoryRequest").msgclass
  PositionsHistoryReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.PositionsHistoryReply").msgclass
  PositionsHistoryData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.PositionsHistoryData").msgclass
  PositionHistoryInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.PositionHistoryInfo").msgclass
  TickValueWithSizeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.TickValueWithSizeRequest").msgclass
  TickValueWithSizeReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.TickValueWithSizeReply").msgclass
  TickValueWithSizeData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.TickValueWithSizeData").msgclass
  TickSizeSymbol = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.TickSizeSymbol").msgclass
  OpenedOrdersTicketsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OpenedOrdersTicketsRequest").msgclass
  OpenedOrdersTicketsReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OpenedOrdersTicketsReply").msgclass
  OpenedOrdersTicketsData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OpenedOrdersTicketsData").msgclass
  OpenedOrdersRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OpenedOrdersRequest").msgclass
  OpenedOrdersReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OpenedOrdersReply").msgclass
  OpenedOrdersData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OpenedOrdersData").msgclass
  PositionInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.PositionInfo").msgclass
  OpenedOrderInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OpenedOrderInfo").msgclass
  OrderHistoryRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OrderHistoryRequest").msgclass
  OrderHistoryReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OrderHistoryReply").msgclass
  OrdersHistoryData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OrdersHistoryData").msgclass
  HistoryData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.HistoryData").msgclass
  DealHistoryData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.DealHistoryData").msgclass
  OrderHistoryData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OrderHistoryData").msgclass
  AccountSummaryRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.AccountSummaryRequest").msgclass
  AccountSummaryReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.AccountSummaryReply").msgclass
  AccountSummaryData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.AccountSummaryData").msgclass
  SymbolParamsManyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolParamsManyRequest").msgclass
  SymbolParamsManyReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolParamsManyReply").msgclass
  SymbolParamsManyData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolParamsManyData").msgclass
  SymbolParameters = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolParameters").msgclass
  AH_ENUM_POSITIONS_HISTORY_SORT_TYPE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.AH_ENUM_POSITIONS_HISTORY_SORT_TYPE").enummodule
  AH_ENUM_POSITIONS_HISTORY_ORDER_TYPE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.AH_ENUM_POSITIONS_HISTORY_ORDER_TYPE").enummodule
  BMT5_ENUM_OPENED_ORDER_SORT_TYPE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.BMT5_ENUM_OPENED_ORDER_SORT_TYPE").enummodule
  BMT5_ENUM_POSITION_TYPE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.BMT5_ENUM_POSITION_TYPE").enummodule
  BMT5_ENUM_POSITION_REASON = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.BMT5_ENUM_POSITION_REASON").enummodule
  BMT5_ENUM_ORDER_TYPE_TIME = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.BMT5_ENUM_ORDER_TYPE_TIME").enummodule
  BMT5_ENUM_ORDER_TYPE_FILLING = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.BMT5_ENUM_ORDER_TYPE_FILLING").enummodule
  BMT5_ENUM_ORDER_TYPE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.BMT5_ENUM_ORDER_TYPE").enummodule
  BMT5_ENUM_DEAL_REASON = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.BMT5_ENUM_DEAL_REASON").enummodule
  BMT5_ENUM_DEAL_TYPE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.BMT5_ENUM_DEAL_TYPE").enummodule
  BMT5_ENUM_DEAL_ENTRY_TYPE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.BMT5_ENUM_DEAL_ENTRY_TYPE").enummodule
  BMT5_ENUM_ORDER_HISTORY_SORT_TYPE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.BMT5_ENUM_ORDER_HISTORY_SORT_TYPE").enummodule
  BMT5_ENUM_ORDER_STATE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.BMT5_ENUM_ORDER_STATE").enummodule
  MrpcEnumAccountTradeMode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.MrpcEnumAccountTradeMode").enummodule
  AH_SYMBOL_PARAMS_MANY_SORT_TYPE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.AH_SYMBOL_PARAMS_MANY_SORT_TYPE").enummodule
  BMT5_ENUM_SYMBOL_OPTION_RIGHT = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.BMT5_ENUM_SYMBOL_OPTION_RIGHT").enummodule
  BMT5_ENUM_SYMBOL_OPTION_MODE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.BMT5_ENUM_SYMBOL_OPTION_MODE").enummodule
  BMT5_ENUM_SYMBOL_ORDER_GTC_MODE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.BMT5_ENUM_SYMBOL_ORDER_GTC_MODE").enummodule
  BMT5_ENUM_DAY_OF_WEEK = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.BMT5_ENUM_DAY_OF_WEEK").enummodule
  BMT5_ENUM_SYMBOL_SWAP_MODE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.BMT5_ENUM_SYMBOL_SWAP_MODE").enummodule
  BMT5_ENUM_SYMBOL_TRADE_EXECUTION = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.BMT5_ENUM_SYMBOL_TRADE_EXECUTION").enummodule
  BMT5_ENUM_SYMBOL_TRADE_MODE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.BMT5_ENUM_SYMBOL_TRADE_MODE").enummodule
  BMT5_ENUM_SYMBOL_CALC_MODE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.BMT5_ENUM_SYMBOL_CALC_MODE").enummodule
  BMT5_ENUM_SYMBOL_SECTOR = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.BMT5_ENUM_SYMBOL_SECTOR").enummodule
  BMT5_ENUM_SYMBOL_CHART_MODE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.BMT5_ENUM_SYMBOL_CHART_MODE").enummodule
  BMT5_ENUM_SYMBOL_INDUSTRY = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.BMT5_ENUM_SYMBOL_INDUSTRY").enummodule
end
