# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mt5-term-api-admin.proto for package 'mrpc_admin'

require 'grpc'
require 'mt5-term-api-admin_pb'

module MrpcAdmin
  module AdminApi
    # ============================================================
    # Admin / diagnostics service.
    # Auth via admin_key (matched against the ADMIN_KEY env setting).
    # HTTP-transcoded for the /admin HTML page + cross-pod fan-out, but HIDDEN from
    # Swagger (excluded in SwaggerGen DocInclusionPredicate in Program.cs).
    # ============================================================
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mrpc_admin.AdminApi'

      # Active terminals running on THIS pod.
      rpc :ActiveTerminals, ::MrpcAdmin::ActiveTerminalsRequest, ::MrpcAdmin::ActiveTerminalsReply
      # Active terminals across ALL pods of this StatefulSet/Deployment.
      # Lists peer pods via the Kubernetes API, then calls ActiveTerminals on each.
      rpc :ActiveTerminalsCluster, ::MrpcAdmin::ActiveTerminalsRequest, ::MrpcAdmin::ActiveTerminalsClusterReply
      # Whole-machine CPU % and physical RAM (current + short history) for THIS pod.
      rpc :SystemUsage, ::MrpcAdmin::ActiveTerminalsRequest, ::MrpcAdmin::SystemUsageReply
      # Lists the diagnostic log files on \\host.lan\Data\logs (mrpc.log, startup.log,
      # install.log, boot-diag.log, and any future additions) - the exact files the container's
      # postStart hook tails into "kubectl logs", readable here without cluster/kubectl access.
      rpc :ListLogFiles, ::MrpcAdmin::ActiveTerminalsRequest, ::MrpcAdmin::ListLogFilesReply
      # Content of one log file from \\host.lan\Data\logs (see ListLogFiles). Truncated to the
      # LAST max_bytes bytes if larger (0 = server default, 256 KiB).
      rpc :GetLogFile, ::MrpcAdmin::GetLogFileRequest, ::MrpcAdmin::GetLogFileReply
      # On-demand dump of recent Windows Event Log entries (Service Control Manager events,
      # shutdown/restart events, Application errors) - the same data boot-diag.bat captures on a
      # service state change, available here without waiting for that trigger.
      rpc :GetEventLogEntries, ::MrpcAdmin::GetEventLogEntriesRequest, ::MrpcAdmin::GetEventLogEntriesReply
      # Screenshot of a Windows interactive session's whole desktop - a specific
      # MrpcTerminalUser<N> session, or (if session_user_name is empty) the pod's main/autologon
      # session, the one startup.bat runs in.
      rpc :CaptureSessionScreenshot, ::MrpcAdmin::CaptureSessionScreenshotRequest, ::MrpcAdmin::CaptureSessionScreenshotReply
      # Same as CaptureSessionScreenshot, but fanned out from THIS pod to a DIFFERENT pod by IP
      # (mirroring the ActiveTerminalsCluster fan-out) - a browser can only reach the pod that is
      # currently serving it, not other pods' ClusterIPs, so the cluster admin view asks whichever
      # pod it's connected to relay the request.
      rpc :CaptureSessionScreenshotOnPod, ::MrpcAdmin::CaptureSessionScreenshotOnPodRequest, ::MrpcAdmin::CaptureSessionScreenshotReply
      # Runs, in-process (LocalSystem, no guest logon/SSH needed), the same refresh
      # startup.bat performs on a successful ONLOGON boot: robocopy published-app (including
      # mrpc-rest) from the host share, then create/start MrpcRestService. Exists because
      # ONLOGON is unreliable (autologon-dependent) - this lets a stuck deploy be repaired
      # through the Terminal Manager's own already-running gRPC/HTTP API instead of waiting
      # on that trigger or requiring interactive guest access.
      rpc :RefreshMrpcRest, ::MrpcAdmin::ActiveTerminalsRequest, ::MrpcAdmin::RefreshMrpcRestReply
      # Build/version identity of the Terminal Manager running on THIS pod, so a deploy can be
      # VERIFIED rather than guessed. No admin_key required - it exposes no secrets. mrpc-rest
      # transcodes GET /version-tm onto this (its own build is at GET /version).
      rpc :GetVersion, ::MrpcAdmin::VersionRequest, ::MrpcAdmin::VersionReply
      # Diagnostic MT5/MT4 journal for a SPECIFIC terminal instance on THIS pod: reads the terminal's
      # own journal (logs\*.log) and the expert/script journal (MQL5\logs\*.log) straight from the
      # terminal's working directory. Lets us see WHY a terminal failed to start / log in to the broker
      # without RDP/noVNC access. The terminal must live on the pod serving this request (its record
      # must be in the local registry); if it is on another pod or was already cleaned up, `error` says so.
      rpc :GetTerminalJournal, ::MrpcAdmin::GetTerminalJournalRequest, ::MrpcAdmin::GetTerminalJournalReply
      # One-shot bundle of EVERY diagnostic log available on this pod: every *.log file on the
      # shared Data folder AND in C:\OEM (mrpc.log, mrpc-rest.log, boot-diag.log, startup.log,
      # install.log, ...), plus the Windows Application + System event logs. Each entry carries a
      # tail of its content so a single call gives the full diagnostic picture for the pod without
      # needing to know file names up front (contrast ListLogFiles + N× GetLogFile).
      rpc :GetAllLogs, ::MrpcAdmin::GetAllLogsRequest, ::MrpcAdmin::GetAllLogsReply
      # Session restore logs for the latest startup sequence on a pod (stored in MongoDB session_restore_logs).
      rpc :GetSessionRestoreLogs, ::MrpcAdmin::GetSessionRestoreLogsRequest, ::MrpcAdmin::GetSessionRestoreLogsReply
      # Session restore watcher status (terminals loaded, queue count, state, diagnostics) for THIS pod.
      rpc :GetSessionRestoreStatus, ::MrpcAdmin::ActiveTerminalsRequest, ::MrpcAdmin::GetSessionRestoreStatusReply
    end

    Stub = Service.rpc_stub_class
  end
end
