# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mt5-term-api-vnc.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("mt5-term-api-vnc.proto", :syntax => :proto3) do
    add_message "mt5_term_api.VncData" do
      optional :payload, :bytes, 1
    end
  end
end

module Mt5TermApi
  VncData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.VncData").msgclass
end
