# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mt5-term-api-gui.proto for package 'mt5_term_api'

require 'grpc'
require 'mt5-term-api-gui_pb'

module Mt5TermApi
  module Gui
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mt5_term_api.Gui'

      rpc :Login, ::Mt5TermApi::GuiLoginRequest, ::Mt5TermApi::GuiLoginReply
      rpc :BrokerSearch, ::Mt5TermApi::GuiBrokerSearchRequest, ::Mt5TermApi::GuiBrokerSearchReply
      rpc :LoginEx, ::Mt5TermApi::GuiLoginExRequest, ::Mt5TermApi::GuiLoginExReply
      rpc :CloseDialogs, ::Mt5TermApi::GuiCloseDialogsRequest, ::Mt5TermApi::GuiCloseDialogsReply
      rpc :DemoFindCompanies, ::Mt5TermApi::GuiDemoFindCompaniesRequest, ::Mt5TermApi::GuiDemoFindCompaniesReply
      rpc :DemoServersAndTypes, ::Mt5TermApi::GuiDemoServersAndTypesRequest, ::Mt5TermApi::GuiDemoServersAndTypesReply
      rpc :DemoOpenAccount, ::Mt5TermApi::GuiDemoOpenAccountRequest, ::Mt5TermApi::GuiDemoOpenAccountReply
      rpc :DemoEnumControls, ::Mt5TermApi::GuiDemoEnumControlsRequest, ::Mt5TermApi::GuiDemoEnumControlsReply
      rpc :DemoOpenAccountWithProgress, ::Mt5TermApi::GuiDemoOpenAccountRequest, stream(::Mt5TermApi::GuiDemoProgressEvent)
      rpc :DemoOpenAccountInteractive, stream(::Mt5TermApi::GuiDemoInteractiveClientMessage), stream(::Mt5TermApi::GuiDemoInteractiveServerMessage)
    end

    Stub = Service.rpc_stub_class
  end
end
