# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mt5-term-api-trade-functions.proto for package 'mt5_term_api'

require 'grpc'
require 'mt5-term-api-trade-functions_pb'

module Mt5TermApi
  module TradeFunctions
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mt5_term_api.TradeFunctions'

      # The function calculates the margin required for the specified order type, on the current account, in the current market environment not taking into account current pending orders and open positions. It allows the evaluation of margin for the trade operation planned. The value is returned in the account currency +
      # https://www.mql5.com/en/docs/trading/ordercalcmargin
      rpc :OrderCalcMargin, ::Mt5TermApi::OrderCalcMarginRequest, ::Mt5TermApi::OrderCalcMarginReply
      # The function calculates the profit for the current account, in the current market conditions, based on the parameters passed. The function is used for pre-evaluation of the result of a trade operation. The value is returned in the account currency. + 
      # https://www.mql5.com/en/docs/trading/ordercalcprofit
      rpc :OrderCalcProfit, ::Mt5TermApi::OrderCalcProfitRequest, ::Mt5TermApi::OrderCalcProfitReply
      # Checks if there are enough money to execute a required Trade Operation Type +
      # https://www.mql5.com/en/docs/trading/ordercheck
      rpc :OrderCheck, ::Mt5TermApi::OrderCheckRequest, ::Mt5TermApi::OrderCheckReply
      # Returns the number of open positions +
      # https://www.mql5.com/en/docs/trading/positionstotal
      rpc :PositionsTotal, ::Google::Protobuf::Empty, ::Mt5TermApi::PositionsTotalReply
    end

    Stub = Service.rpc_stub_class
  end
end
