# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mt5-term-api-account-information.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'mrpc-mt5-error_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("mt5-term-api-account-information.proto", :syntax => :proto3) do
    add_message "mt5_term_api.AccountInfoDoubleRequest" do
      optional :property_id, :enum, 1, "mt5_term_api.AccountInfoDoublePropertyType"
    end
    add_message "mt5_term_api.AccountInfoDoubleReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.AccountInfoDoubleData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.AccountInfoDoubleData" do
      optional :requested_value, :double, 1
    end
    add_message "mt5_term_api.AccountInfoIntegerRequest" do
      optional :property_id, :enum, 1, "mt5_term_api.AccountInfoIntegerPropertyType"
    end
    add_message "mt5_term_api.AccountInfoIntegerReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.AccountInfoIntegerData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.AccountInfoIntegerData" do
      optional :requested_value, :int64, 1
    end
    add_message "mt5_term_api.AccountInfoStringRequest" do
      optional :property_id, :enum, 1, "mt5_term_api.AccountInfoStringPropertyType"
    end
    add_message "mt5_term_api.AccountInfoStringReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.AccountInfoStringData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.AccountInfoStringData" do
      optional :requested_value, :string, 1
    end
    add_enum "mt5_term_api.AccountInfoDoublePropertyType" do
      value :ACCOUNT_BALANCE, 0
      value :ACCOUNT_CREDIT, 1
      value :ACCOUNT_PROFIT, 2
      value :ACCOUNT_EQUITY, 3
      value :ACCOUNT_MARGIN, 4
      value :ACCOUNT_MARGIN_FREE, 5
      value :ACCOUNT_MARGIN_LEVEL, 6
      value :ACCOUNT_MARGIN_SO_CALL, 7
      value :ACCOUNT_MARGIN_SO_SO, 8
      value :ACCOUNT_MARGIN_INITIAL, 9
      value :ACCOUNT_MARGIN_MAINTENANCE, 10
      value :ACCOUNT_ASSETS, 11
      value :ACCOUNT_LIABILITIES, 12
      value :ACCOUNT_COMMISSION_BLOCKED, 13
    end
    add_enum "mt5_term_api.AccountInfoIntegerPropertyType" do
      value :ACCOUNT_LOGIN, 0
      value :ACCOUNT_TRADE_MODE, 1
      value :ACCOUNT_LEVERAGE, 2
      value :ACCOUNT_LIMIT_ORDERS, 3
      value :ACCOUNT_MARGIN_SO_MODE, 4
      value :ACCOUNT_TRADE_ALLOWED, 5
      value :ACCOUNT_TRADE_EXPERT, 6
      value :ACCOUNT_MARGIN_MODE, 7
      value :ACCOUNT_CURRENCY_DIGITS, 8
      value :ACCOUNT_FIFO_CLOSE, 9
      value :ACCOUNT_HEDGE_ALLOWED, 10
    end
    add_enum "mt5_term_api.AccountInfoStringPropertyType" do
      value :ACCOUNT_NAME, 0
      value :ACCOUNT_SERVER, 1
      value :ACCOUNT_CURRENCY, 2
      value :ACCOUNT_COMPANY, 3
    end
  end
end

module Mt5TermApi
  AccountInfoDoubleRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.AccountInfoDoubleRequest").msgclass
  AccountInfoDoubleReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.AccountInfoDoubleReply").msgclass
  AccountInfoDoubleData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.AccountInfoDoubleData").msgclass
  AccountInfoIntegerRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.AccountInfoIntegerRequest").msgclass
  AccountInfoIntegerReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.AccountInfoIntegerReply").msgclass
  AccountInfoIntegerData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.AccountInfoIntegerData").msgclass
  AccountInfoStringRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.AccountInfoStringRequest").msgclass
  AccountInfoStringReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.AccountInfoStringReply").msgclass
  AccountInfoStringData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.AccountInfoStringData").msgclass
  AccountInfoDoublePropertyType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.AccountInfoDoublePropertyType").enummodule
  AccountInfoIntegerPropertyType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.AccountInfoIntegerPropertyType").enummodule
  AccountInfoStringPropertyType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.AccountInfoStringPropertyType").enummodule
end
