# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mt5-term-api-subscriptions.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'google/protobuf/timestamp_pb'
require 'mrpc-mt5-error_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("mt5-term-api-subscriptions.proto", :syntax => :proto3) do
    add_message "mt5_term_api.OnTradeTransactionRequest" do
    end
    add_message "mt5_term_api.OnTradeTransactionReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.OnTradeTransactionData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.OnTradeTransactionData" do
      optional :type, :enum, 1, "mt5_term_api.MT5_SUB_ENUM_EVENT_GROUP_TYPE"
      optional :trade_transaction, :message, 2, "mt5_term_api.MqlTradeTransaction"
      optional :trade_request, :message, 3, "mt5_term_api.MqlTradeRequest"
      optional :trade_result, :message, 4, "mt5_term_api.MqlTradeResult"
      optional :terminal_instance_guid_id, :string, 5
      optional :account_info, :message, 6, "mt5_term_api.OnEventAccountInfo"
    end
    add_message "mt5_term_api.MqlTradeTransaction" do
      optional :deal_ticket, :uint64, 1
      optional :order_ticket, :uint64, 2
      optional :symbol, :string, 3
      optional :type, :enum, 4, "mt5_term_api.SUB_ENUM_TRADE_TRANSACTION_TYPE"
      optional :order_type, :enum, 5, "mt5_term_api.SUB_ENUM_ORDER_TYPE"
      optional :order_state, :enum, 6, "mt5_term_api.SUB_ENUM_ORDER_STATE"
      optional :deal_type, :enum, 7, "mt5_term_api.SUB_ENUM_DEAL_TYPE"
      optional :order_time_type, :enum, 8, "mt5_term_api.SUB_ENUM_ORDER_TYPE_TIME"
      optional :order_expiration_time, :message, 9, "google.protobuf.Timestamp"
      optional :price, :double, 10
      optional :price_trigger_stop_limit, :double, 11
      optional :price_stop_loss, :double, 12
      optional :price_take_profit, :double, 13
      optional :volume, :double, 14
      optional :position_ticket, :uint64, 15
      optional :position_by_opposite_position, :uint64, 16
    end
    add_message "mt5_term_api.MqlTradeRequest" do
      optional :trade_operation_type, :enum, 1, "mt5_term_api.SUB_ENUM_TRADE_REQUEST_ACTIONS"
      optional :magic, :uint64, 2
      optional :order_ticket, :uint64, 3
      optional :symbol, :string, 4
      optional :requested_deal_volume_lots, :double, 5
      optional :price, :double, 6
      optional :stopl_imit, :double, 7
      optional :stop_loss, :double, 8
      optional :take_profit, :double, 9
      optional :deviation, :uint64, 10
      optional :order_type, :enum, 11, "mt5_term_api.SUB_ENUM_ORDER_TYPE"
      optional :order_type_filling, :enum, 12, "mt5_term_api.SUB_ENUM_ORDER_TYPE_FILLING"
      optional :type_time, :enum, 13, "mt5_term_api.SUB_ENUM_ORDER_TYPE_TIME"
      optional :order_expiration_time, :message, 14, "google.protobuf.Timestamp"
      optional :order_comment, :string, 15
      optional :position_ticket, :uint64, 16
      optional :position_by_opposite_position, :uint64, 17
    end
    add_message "mt5_term_api.MqlTradeResult" do
      optional :trade_return_int_code, :uint32, 1
      optional :trade_return_code, :enum, 2, "mt5_term_api.MqlErrorTradeCode"
      optional :deal_ticket, :uint64, 3
      optional :order_ticket, :uint64, 4
      optional :deal_volume, :double, 5
      optional :deal_price, :double, 6
      optional :current_bid, :double, 7
      optional :current_ask, :double, 8
      optional :broker_comment_to_operation, :string, 9
      optional :terminal_dispatch_request_id, :uint32, 10
      optional :return_code_external, :int32, 11
    end
    add_message "mt5_term_api.OnPositionsAndPendingOrdersTicketsRequest" do
      optional :timer_period_milliseconds, :int32, 1
    end
    add_message "mt5_term_api.OnPositionsAndPendingOrdersTicketsReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.OnPositionsAndPendingOrdersTicketsData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.OnPositionsAndPendingOrdersTicketsData" do
      repeated :position_tickets, :uint64, 1
      repeated :pending_order_tickets, :uint64, 2
      optional :server_time, :message, 3, "google.protobuf.Timestamp"
      optional :terminal_instance_guid_id, :string, 4
    end
    add_message "mt5_term_api.OnPositionProfitReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.OnPositionProfitData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.OnPositionProfitData" do
      optional :type, :enum, 1, "mt5_term_api.MT5_SUB_ENUM_EVENT_GROUP_TYPE"
      repeated :new_positions, :message, 2, "mt5_term_api.OnPositionProfitPositionInfo"
      repeated :updated_positions, :message, 3, "mt5_term_api.OnPositionProfitPositionInfo"
      repeated :deleted_positions, :message, 4, "mt5_term_api.OnPositionProfitPositionInfo"
      optional :account_info, :message, 5, "mt5_term_api.OnEventAccountInfo"
      optional :terminal_instance_guid_id, :string, 6
    end
    add_message "mt5_term_api.OnPositionProfitRequest" do
      optional :timer_period_milliseconds, :int32, 1
      optional :ignore_empty_data, :bool, 2
    end
    add_message "mt5_term_api.OnPositionProfitPositionInfo" do
      optional :index, :int32, 1
      optional :ticket, :int64, 2
      optional :profit, :double, 3
      optional :position_symbol, :string, 4
    end
    add_message "mt5_term_api.OnEventAccountInfo" do
      optional :balance, :double, 1
      optional :credit, :double, 2
      optional :equity, :double, 3
      optional :margin, :double, 4
      optional :free_margin, :double, 5
      optional :profit, :double, 6
      optional :margin_level, :double, 7
      optional :login, :int64, 8
    end
    add_message "mt5_term_api.OnTradeRequest" do
    end
    add_message "mt5_term_api.OnTradeReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.OnTradeData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.OnTradeData" do
      optional :type, :enum, 1, "mt5_term_api.MT5_SUB_ENUM_EVENT_GROUP_TYPE"
      optional :event_data, :message, 2, "mt5_term_api.OnTadeEventData"
      optional :account_info, :message, 3, "mt5_term_api.OnEventAccountInfo"
      optional :terminal_instance_guid_id, :string, 4
    end
    add_message "mt5_term_api.OnTradeOrderInfo" do
      optional :index, :int32, 1
      optional :ticket, :int64, 2
      optional :state, :enum, 3, "mt5_term_api.SUB_ENUM_ORDER_STATE"
      optional :setup_time_msc, :int64, 4
      optional :stop_loss, :double, 5
      optional :take_profit, :double, 6
      optional :stop_limit, :double, 7
      optional :price_current, :double, 8
      optional :time_expiration, :message, 9, "google.protobuf.Timestamp"
      optional :time_type, :enum, 10, "mt5_term_api.SUB_ENUM_ORDER_TYPE_TIME"
      optional :comment, :string, 11
      optional :symbol, :string, 12
      optional :magic, :int64, 13
      optional :price_open, :double, 14
      optional :setup_time, :message, 15, "google.protobuf.Timestamp"
      optional :time_expiration_seconds, :int64, 16
      optional :volume_current, :double, 17
      optional :volume_initial, :double, 18
      optional :account_login, :int64, 19
      optional :order_type, :enum, 20, "mt5_term_api.SUB_ENUM_ORDER_TYPE"
      optional :order_type_filling, :enum, 21, "mt5_term_api.SUB_ENUM_ORDER_TYPE_FILLING"
      optional :order_reason, :enum, 22, "mt5_term_api.SUB_ENUM_ORDER_REASON"
      optional :position_id, :int64, 23
      optional :position_by_id, :int64, 24
    end
    add_message "mt5_term_api.OnTradePositionInfo" do
      optional :index, :int32, 1
      optional :ticket, :int64, 2
      optional :type, :enum, 3, "mt5_term_api.SUB_ENUM_POSITION_TYPE"
      optional :position_time, :message, 4, "google.protobuf.Timestamp"
      optional :last_update_time, :message, 5, "google.protobuf.Timestamp"
      optional :price_open, :double, 6
      optional :profit, :double, 7
      optional :sl, :double, 8
      optional :tp, :double, 9
      optional :volume, :double, 10
      optional :swap, :double, 11
      optional :comment, :string, 12
      optional :symbol, :string, 13
      optional :magic, :int64, 14
      optional :price_current, :double, 15
      optional :account_login, :int64, 16
      optional :reason, :enum, 17, "mt5_term_api.SUB_ENUM_POSITION_REASON"
      optional :from_pending_order, :bool, 18
    end
    add_message "mt5_term_api.OnTradeHistoryDealInfo" do
      optional :index, :int32, 1
      optional :ticket, :uint64, 2
      optional :order_ticket, :int64, 3
      optional :type, :enum, 4, "mt5_term_api.SUB_ENUM_DEAL_TYPE"
      optional :deal_time, :message, 5, "google.protobuf.Timestamp"
      optional :entry, :enum, 6, "mt5_term_api.SUB_ENUM_DEAL_ENTRY"
      optional :deal_position_id, :int64, 7
      optional :commission, :double, 8
      optional :fee, :double, 9
      optional :price, :double, 10
      optional :profit, :double, 11
      optional :sl, :double, 12
      optional :tp, :double, 13
      optional :volume, :double, 14
      optional :comment, :string, 15
      optional :symbol, :string, 16
      optional :swap, :double, 17
      optional :reason, :enum, 18, "mt5_term_api.SUB_ENUM_DEAL_REASON"
      optional :magic, :int64, 19
      optional :account_login, :int64, 20
    end
    add_message "mt5_term_api.OnTradeHistoryOrderInfo" do
      optional :index, :int32, 1
      optional :ticket, :int64, 2
      optional :state, :enum, 3, "mt5_term_api.SUB_ENUM_ORDER_STATE"
      optional :setup_time, :message, 4, "google.protobuf.Timestamp"
      optional :done_time, :message, 5, "google.protobuf.Timestamp"
      optional :time_expiration, :message, 6, "google.protobuf.Timestamp"
      optional :position_id, :uint64, 7
      optional :type_time, :enum, 8, "mt5_term_api.SUB_ENUM_ORDER_TYPE_TIME"
      optional :stop_loss, :double, 9
      optional :take_profit, :double, 10
      optional :stop_limit, :double, 11
      optional :price_current, :double, 12
      optional :price_open, :double, 13
      optional :volume_current, :double, 14
      optional :volume_initial, :double, 15
      optional :magic, :int64, 19
      optional :position_by, :int64, 20
      optional :reason, :enum, 21, "mt5_term_api.SUB_ENUM_DEAL_REASON"
      optional :comment, :string, 22
      optional :symbol, :string, 23
      optional :time_expiration_seconds, :int64, 24
      optional :account_login, :int64, 25
      optional :order_type, :enum, 26, "mt5_term_api.SUB_ENUM_ORDER_TYPE"
      optional :order_type_filling, :enum, 27, "mt5_term_api.SUB_ENUM_ORDER_TYPE_FILLING"
    end
    add_message "mt5_term_api.OnTradeOrderStateChange" do
      optional :previous_order, :message, 1, "mt5_term_api.OnTradeOrderInfo"
      optional :current_order, :message, 2, "mt5_term_api.OnTradeOrderInfo"
    end
    add_message "mt5_term_api.OnTradePositionUpdate" do
      optional :previous_position, :message, 1, "mt5_term_api.OnTradePositionInfo"
      optional :current_position, :message, 2, "mt5_term_api.OnTradePositionInfo"
    end
    add_message "mt5_term_api.OnTradeHistoryDealUpdate" do
      optional :previous_history_deal, :message, 1, "mt5_term_api.OnTradeHistoryDealInfo"
      optional :current_history_deal, :message, 2, "mt5_term_api.OnTradeHistoryDealInfo"
    end
    add_message "mt5_term_api.OnTradeHistoryOrderUpdate" do
      optional :previous_history_order, :message, 1, "mt5_term_api.OnTradeHistoryOrderInfo"
      optional :current_history_order, :message, 2, "mt5_term_api.OnTradeHistoryOrderInfo"
    end
    add_message "mt5_term_api.OnTadeEventData" do
      repeated :new_orders, :message, 1, "mt5_term_api.OnTradeOrderInfo"
      repeated :disappeared_orders, :message, 2, "mt5_term_api.OnTradeOrderInfo"
      repeated :state_changed_orders, :message, 3, "mt5_term_api.OnTradeOrderStateChange"
      repeated :new_history_orders, :message, 4, "mt5_term_api.OnTradeHistoryOrderInfo"
      repeated :disappeared_history_orders, :message, 5, "mt5_term_api.OnTradeHistoryOrderInfo"
      repeated :updated_history_orders, :message, 6, "mt5_term_api.OnTradeHistoryOrderUpdate"
      repeated :new_history_deals, :message, 7, "mt5_term_api.OnTradeHistoryDealInfo"
      repeated :disappeared_history_deals, :message, 8, "mt5_term_api.OnTradeHistoryDealInfo"
      repeated :updated_history_deals, :message, 9, "mt5_term_api.OnTradeHistoryDealUpdate"
      repeated :new_positions, :message, 10, "mt5_term_api.OnTradePositionInfo"
      repeated :disappeared_positions, :message, 11, "mt5_term_api.OnTradePositionInfo"
      repeated :updated_positions, :message, 12, "mt5_term_api.OnTradePositionUpdate"
    end
    add_message "mt5_term_api.OnSymbolTickRequest" do
      repeated :symbol_names, :string, 1
    end
    add_message "mt5_term_api.OnSymbolTickReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.OnSymbolTickData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.OnSymbolTickData" do
      optional :symbol_tick, :message, 1, "mt5_term_api.MrpcSubscriptionMqlTick"
      optional :terminal_instance_guid_id, :string, 2
    end
    add_message "mt5_term_api.MrpcSubscriptionMqlTick" do
      optional :time, :message, 1, "google.protobuf.Timestamp"
      optional :bid, :double, 2
      optional :ask, :double, 3
      optional :last, :double, 4
      optional :volume, :uint64, 5
      optional :time_msc, :int64, 6
      optional :flags, :uint32, 7
      optional :volume_real, :double, 8
      optional :symbol, :string, 9
    end
    add_enum "mt5_term_api.SUB_ENUM_TRADE_TRANSACTION_TYPE" do
      value :SUB_TRADE_TRANSACTION_ORDER_ADD, 0
      value :SUB_TRADE_TRANSACTION_ORDER_UPDATE, 1
      value :SUB_TRADE_TRANSACTION_ORDER_DELETE, 2
      value :SUB_TRADE_TRANSACTION_DEAL_ADD, 3
      value :SUB_TRADE_TRANSACTION_DEAL_UPDATE, 4
      value :SUB_TRADE_TRANSACTION_DEAL_DELETE, 5
      value :SUB_TRADE_TRANSACTION_HISTORY_ADD, 6
      value :SUB_TRADE_TRANSACTION_HISTORY_UPDATE, 7
      value :SUB_TRADE_TRANSACTION_HISTORY_DELETE, 8
      value :SUB_TRADE_TRANSACTION_POSITION, 9
      value :SUB_TRADE_TRANSACTION_REQUEST, 10
    end
    add_enum "mt5_term_api.SUB_ENUM_TRADE_REQUEST_ACTIONS" do
      value :SUB_TRADE_ACTION_UNDEFINED, 0
      value :SUB_TRADE_ACTION_DEAL, 1
      value :SUB_TRADE_ACTION_PENDING, 2
      value :SUB_TRADE_ACTION_SLTP, 3
      value :SUB_TRADE_ACTION_MODIFY, 4
      value :SUB_TRADE_ACTION_REMOVE, 5
      value :SUB_TRADE_ACTION_CLOSE_BY, 6
    end
    add_enum "mt5_term_api.SUB_ENUM_ORDER_REASON" do
      value :SUB_ORDER_REASON_CLIENT, 0
      value :SUB_ORDER_REASON_MOBILE, 2
      value :SUB_ORDER_REASON_WEB, 3
      value :SUB_ORDER_REASON_EXPERT, 4
      value :SUB_ORDER_REASON_SL, 5
      value :SUB_ORDER_REASON_TP, 6
      value :SUB_ORDER_REASON_SO, 7
    end
    add_enum "mt5_term_api.SUB_ENUM_ORDER_TYPE_FILLING" do
      value :SUB_ORDER_FILLING_FOK, 0
      value :SUB_ORDER_FILLING_IOC, 1
      value :SUB_ORDER_FILLING_BOC, 2
      value :SUB_ORDER_FILLING_RETURN, 3
    end
    add_enum "mt5_term_api.SUB_ENUM_ORDER_TYPE" do
      value :SUB_ORDER_TYPE_BUY, 0
      value :SUB_ORDER_TYPE_SELL, 1
      value :SUB_ORDER_TYPE_BUY_LIMIT, 2
      value :SUB_ORDER_TYPE_SELL_LIMIT, 3
      value :SUB_ORDER_TYPE_BUY_STOP, 4
      value :SUB_ORDER_TYPE_SELL_STOP, 5
      value :SUB_ORDER_TYPE_BUY_STOP_LIMIT, 6
      value :SUB_ORDER_TYPE_SELL_STOP_LIMIT, 7
      value :SUB_ORDER_TYPE_CLOSE_BY, 8
    end
    add_enum "mt5_term_api.SUB_ENUM_ORDER_TYPE_TIME" do
      value :SUB_ORDER_TIME_GTC, 0
      value :SUB_ORDER_TIME_DAY, 1
      value :SUB_ORDER_TIME_SPECIFIED, 2
      value :SUB_ORDER_TIME_SPECIFIED_DAY, 3
    end
    add_enum "mt5_term_api.SUB_ENUM_ORDER_STATE" do
      value :SUB_ORDER_STATE_STARTED, 0
      value :SUB_ORDER_STATE_PLACED, 1
      value :SUB_ORDER_STATE_CANCELED, 2
      value :SUB_ORDER_STATE_PARTIAL, 3
      value :SUB_ORDER_STATE_FILLED, 4
      value :SUB_ORDER_STATE_REJECTED, 5
      value :SUB_ORDER_STATE_EXPIRED, 6
      value :SUB_ORDER_STATE_REQUEST_ADD, 7
      value :SUB_ORDER_STATE_REQUEST_MODIFY, 8
      value :SUB_ORDER_STATE_REQUEST_CANCEL, 9
    end
    add_enum "mt5_term_api.SUB_ENUM_POSITION_REASON" do
      value :SUB_POSITION_REASON_CLIENT, 0
      value :SUB_POSITION_REASON_MOBILE, 2
      value :SUB_POSITION_REASON_WEB, 3
      value :SUB_POSITION_REASON_EXPERT, 4
    end
    add_enum "mt5_term_api.SUB_ENUM_POSITION_TYPE" do
      value :SUB_POSITION_TYPE_BUY, 0
      value :SUB_POSITION_TYPE_SELL, 1
    end
    add_enum "mt5_term_api.SUB_ENUM_DEAL_REASON" do
      value :SUB_DEAL_REASON_CLIENT, 0
      value :SUB_DEAL_REASON_MOBILE, 1
      value :SUB_DEAL_REASON_WEB, 2
      value :SUB_DEAL_REASON_EXPERT, 3
      value :SUB_DEAL_REASON_SL, 4
      value :SUB_DEAL_REASON_TP, 5
      value :SUB_DEAL_REASON_SO, 6
      value :SUB_DEAL_REASON_ROLLOVER, 7
      value :SUB_DEAL_REASON_VMARGIN, 8
      value :SUB_DEAL_REASON_SPLIT, 9
      value :SUB_DEAL_REASON_CORPORATE_ACTION, 10
    end
    add_enum "mt5_term_api.SUB_ENUM_DEAL_TYPE" do
      value :SUB_DEAL_TYPE_BUY, 0
      value :SUB_DEAL_TYPE_SELL, 1
      value :SUB_DEAL_TYPE_BALANCE, 2
      value :SUB_DEAL_TYPE_CREDIT, 3
      value :SUB_DEAL_TYPE_CHARGE, 4
      value :SUB_DEAL_TYPE_CORRECTION, 5
      value :SUB_DEAL_TYPE_BONUS, 6
      value :SUB_DEAL_TYPE_COMMISSION, 7
      value :SUB_DEAL_TYPE_COMMISSION_DAILY, 8
      value :SUB_DEAL_TYPE_COMMISSION_MONTHLY, 9
      value :SUB_DEAL_TYPE_COMMISSION_AGENT_DAILY, 10
      value :SUB_DEAL_TYPE_COMMISSION_AGENT_MONTHLY, 11
      value :SUB_DEAL_TYPE_INTEREST, 12
      value :SUB_DEAL_TYPE_BUY_CANCELED, 13
      value :SUB_DEAL_TYPE_SELL_CANCELED, 14
      value :SUB_DEAL_DIVIDEND, 15
      value :SUB_DEAL_DIVIDEND_FRANKED, 16
      value :SUB_DEAL_TAX, 17
    end
    add_enum "mt5_term_api.SUB_ENUM_DEAL_ENTRY" do
      value :SUB_DEAL_ENTRY_IN, 0
      value :SUB_DEAL_ENTRY_OUT, 1
      value :SUB_DEAL_ENTRY_INOUT, 2
      value :SUB_DEAL_ENTRY_OUT_BY, 3
    end
    add_enum "mt5_term_api.MT5_SUB_ENUM_EVENT_GROUP_TYPE" do
      value :OrderProfit, 0
      value :OrderUpdate, 1
    end
  end
end

module Mt5TermApi
  OnTradeTransactionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OnTradeTransactionRequest").msgclass
  OnTradeTransactionReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OnTradeTransactionReply").msgclass
  OnTradeTransactionData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OnTradeTransactionData").msgclass
  MqlTradeTransaction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.MqlTradeTransaction").msgclass
  MqlTradeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.MqlTradeRequest").msgclass
  MqlTradeResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.MqlTradeResult").msgclass
  OnPositionsAndPendingOrdersTicketsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OnPositionsAndPendingOrdersTicketsRequest").msgclass
  OnPositionsAndPendingOrdersTicketsReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OnPositionsAndPendingOrdersTicketsReply").msgclass
  OnPositionsAndPendingOrdersTicketsData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OnPositionsAndPendingOrdersTicketsData").msgclass
  OnPositionProfitReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OnPositionProfitReply").msgclass
  OnPositionProfitData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OnPositionProfitData").msgclass
  OnPositionProfitRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OnPositionProfitRequest").msgclass
  OnPositionProfitPositionInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OnPositionProfitPositionInfo").msgclass
  OnEventAccountInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OnEventAccountInfo").msgclass
  OnTradeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OnTradeRequest").msgclass
  OnTradeReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OnTradeReply").msgclass
  OnTradeData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OnTradeData").msgclass
  OnTradeOrderInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OnTradeOrderInfo").msgclass
  OnTradePositionInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OnTradePositionInfo").msgclass
  OnTradeHistoryDealInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OnTradeHistoryDealInfo").msgclass
  OnTradeHistoryOrderInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OnTradeHistoryOrderInfo").msgclass
  OnTradeOrderStateChange = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OnTradeOrderStateChange").msgclass
  OnTradePositionUpdate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OnTradePositionUpdate").msgclass
  OnTradeHistoryDealUpdate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OnTradeHistoryDealUpdate").msgclass
  OnTradeHistoryOrderUpdate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OnTradeHistoryOrderUpdate").msgclass
  OnTadeEventData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OnTadeEventData").msgclass
  OnSymbolTickRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OnSymbolTickRequest").msgclass
  OnSymbolTickReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OnSymbolTickReply").msgclass
  OnSymbolTickData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OnSymbolTickData").msgclass
  MrpcSubscriptionMqlTick = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.MrpcSubscriptionMqlTick").msgclass
  SUB_ENUM_TRADE_TRANSACTION_TYPE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SUB_ENUM_TRADE_TRANSACTION_TYPE").enummodule
  SUB_ENUM_TRADE_REQUEST_ACTIONS = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SUB_ENUM_TRADE_REQUEST_ACTIONS").enummodule
  SUB_ENUM_ORDER_REASON = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SUB_ENUM_ORDER_REASON").enummodule
  SUB_ENUM_ORDER_TYPE_FILLING = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SUB_ENUM_ORDER_TYPE_FILLING").enummodule
  SUB_ENUM_ORDER_TYPE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SUB_ENUM_ORDER_TYPE").enummodule
  SUB_ENUM_ORDER_TYPE_TIME = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SUB_ENUM_ORDER_TYPE_TIME").enummodule
  SUB_ENUM_ORDER_STATE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SUB_ENUM_ORDER_STATE").enummodule
  SUB_ENUM_POSITION_REASON = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SUB_ENUM_POSITION_REASON").enummodule
  SUB_ENUM_POSITION_TYPE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SUB_ENUM_POSITION_TYPE").enummodule
  SUB_ENUM_DEAL_REASON = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SUB_ENUM_DEAL_REASON").enummodule
  SUB_ENUM_DEAL_TYPE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SUB_ENUM_DEAL_TYPE").enummodule
  SUB_ENUM_DEAL_ENTRY = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SUB_ENUM_DEAL_ENTRY").enummodule
  MT5_SUB_ENUM_EVENT_GROUP_TYPE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.MT5_SUB_ENUM_EVENT_GROUP_TYPE").enummodule
end
