# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mt5-term-api-market-info.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'google/protobuf/timestamp_pb'
require 'mrpc-mt5-error_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("mt5-term-api-market-info.proto", :syntax => :proto3) do
    add_message "mt5_term_api.SymbolListRequest" do
    end
    add_message "mt5_term_api.SymbolListReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.SymbolListData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.SymbolListData" do
      repeated :Symbols, :string, 1
    end
    add_message "mt5_term_api.SymbolsTotalRequest" do
      optional :mode, :bool, 1
    end
    add_message "mt5_term_api.SymbolsTotalReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.SymbolsTotalData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.SymbolsTotalData" do
      optional :total, :int32, 1
    end
    add_message "mt5_term_api.SymbolExistRequest" do
      optional :name, :string, 1
    end
    add_message "mt5_term_api.SymbolExistReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.SymbolExistData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.SymbolExistData" do
      optional :exists, :bool, 1
      optional :is_custom, :bool, 2
    end
    add_message "mt5_term_api.SymbolNameRequest" do
      optional :index, :int32, 1
      optional :selected, :bool, 2
    end
    add_message "mt5_term_api.SymbolNameReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.SymbolNameData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.SymbolNameData" do
      optional :name, :string, 1
    end
    add_message "mt5_term_api.SymbolSelectRequest" do
      optional :symbol, :string, 1
      optional :select, :bool, 2
    end
    add_message "mt5_term_api.SymbolSelectReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.SymbolSelectData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.SymbolSelectData" do
      optional :success, :bool, 1
    end
    add_message "mt5_term_api.SymbolIsSynchronizedRequest" do
      optional :symbol, :string, 1
    end
    add_message "mt5_term_api.SymbolIsSynchronizedReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.SymbolIsSynchronizedData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.SymbolIsSynchronizedData" do
      optional :synchronized, :bool, 1
    end
    add_message "mt5_term_api.SymbolInfoDoubleRequest" do
      optional :symbol, :string, 1
      optional :type, :enum, 2, "mt5_term_api.SymbolInfoDoubleProperty"
    end
    add_message "mt5_term_api.SymbolInfoDoubleReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.SymbolInfoDoubleData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.SymbolInfoDoubleData" do
      optional :value, :double, 1
    end
    add_message "mt5_term_api.SymbolInfoIntegerRequest" do
      optional :symbol, :string, 1
      optional :type, :enum, 2, "mt5_term_api.SymbolInfoIntegerProperty"
    end
    add_message "mt5_term_api.SymbolInfoIntegerReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.SymbolInfoIntegerData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.SymbolInfoIntegerData" do
      optional :value, :int64, 1
    end
    add_message "mt5_term_api.SymbolInfoStringRequest" do
      optional :symbol, :string, 1
      optional :type, :enum, 2, "mt5_term_api.SymbolInfoStringProperty"
    end
    add_message "mt5_term_api.SymbolInfoStringReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.SymbolInfoStringData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.SymbolInfoStringData" do
      optional :value, :string, 1
    end
    add_message "mt5_term_api.SymbolInfoMarginRateRequest" do
      optional :symbol, :string, 1
      optional :order_type, :enum, 2, "mt5_term_api.ENUM_ORDER_TYPE"
    end
    add_message "mt5_term_api.SymbolInfoMarginRateReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.SymbolInfoMarginRateData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.SymbolInfoMarginRateData" do
      optional :maintenance_margin_rate, :double, 1
      optional :initial_margin_rate, :double, 2
    end
    add_message "mt5_term_api.SymbolInfoTickRequest" do
      optional :symbol, :string, 1
    end
    add_message "mt5_term_api.SymbolInfoTickRequestReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.MrpcMqlTick"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.MrpcMqlTick" do
      optional :time, :int64, 1
      optional :bid, :double, 2
      optional :ask, :double, 3
      optional :last, :double, 4
      optional :volume, :uint64, 5
      optional :time_msc, :int64, 6
      optional :flags, :uint32, 7
      optional :volume_real, :double, 8
    end
    add_message "mt5_term_api.SymbolInfoSessionQuoteRequest" do
      optional :symbol, :string, 1
      optional :day_of_week, :enum, 2, "mt5_term_api.DayOfWeek"
      optional :session_index, :uint32, 3
    end
    add_message "mt5_term_api.SymbolInfoSessionQuoteReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.SymbolInfoSessionQuoteData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.SymbolInfoSessionQuoteData" do
      optional :from, :message, 1, "google.protobuf.Timestamp"
      optional :to, :message, 2, "google.protobuf.Timestamp"
    end
    add_message "mt5_term_api.SymbolInfoSessionTradeRequest" do
      optional :symbol, :string, 1
      optional :day_of_week, :enum, 2, "mt5_term_api.DayOfWeek"
      optional :session_index, :uint32, 3
    end
    add_message "mt5_term_api.SymbolInfoSessionTradeReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.SymbolInfoSessionTradeData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.SymbolInfoSessionTradeData" do
      optional :from, :message, 1, "google.protobuf.Timestamp"
      optional :to, :message, 2, "google.protobuf.Timestamp"
    end
    add_message "mt5_term_api.MarketBookAddRequest" do
      optional :symbol, :string, 1
    end
    add_message "mt5_term_api.MarketBookAddReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.MarketBookAddData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.MarketBookAddData" do
      optional :opened_successfully, :bool, 1
    end
    add_message "mt5_term_api.MarketBookReleaseRequest" do
      optional :symbol, :string, 1
    end
    add_message "mt5_term_api.MarketBookReleaseReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.MarketBookReleaseData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.MarketBookReleaseData" do
      optional :closed_successfully, :bool, 1
    end
    add_message "mt5_term_api.MarketBookGetRequest" do
      optional :symbol, :string, 1
    end
    add_message "mt5_term_api.MarketBookGetReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.MarketBookGetData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.MarketBookGetData" do
      repeated :mql_book_infos, :message, 1, "mt5_term_api.MrpcMqlBookInfo"
    end
    add_message "mt5_term_api.MrpcMqlBookInfo" do
      optional :type, :enum, 1, "mt5_term_api.BookType"
      optional :price, :double, 2
      optional :volume, :int64, 3
      optional :volume_real, :double, 4
    end
    add_message "mt5_term_api.PriceHistoryRequest" do
      optional :symbol, :string, 1
      optional :timeframe, :int32, 2
      optional :from_time, :int64, 3
      optional :to_time, :int64, 4
      optional :max_bars, :int32, 5
    end
    add_message "mt5_term_api.PriceHistoryReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.PriceHistoryData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.PriceHistoryData" do
      repeated :bars, :message, 1, "mt5_term_api.PriceBar"
    end
    add_message "mt5_term_api.PriceBar" do
      optional :time, :int64, 1
      optional :open, :double, 2
      optional :high, :double, 3
      optional :low, :double, 4
      optional :close, :double, 5
      optional :tick_volume, :int64, 6
      optional :spread, :int32, 7
      optional :real_volume, :int64, 8
    end
    add_enum "mt5_term_api.SymbolInfoDoubleProperty" do
      value :SYMBOL_BID, 0
      value :SYMBOL_BIDHIGH, 1
      value :SYMBOL_BIDLOW, 2
      value :SYMBOL_ASK, 3
      value :SYMBOL_ASKHIGH, 4
      value :SYMBOL_ASKLOW, 5
      value :SYMBOL_LAST, 6
      value :SYMBOL_LASTHIGH, 7
      value :SYMBOL_LASTLOW, 8
      value :SYMBOL_VOLUME_REAL, 9
      value :SYMBOL_VOLUMEHIGH_REAL, 10
      value :SYMBOL_VOLUMELOW_REAL, 11
      value :SYMBOL_OPTION_STRIKE, 12
      value :SYMBOL_POINT, 13
      value :SYMBOL_TRADE_TICK_VALUE, 14
      value :SYMBOL_TRADE_TICK_VALUE_PROFIT, 15
      value :SYMBOL_TRADE_TICK_VALUE_LOSS, 16
      value :SYMBOL_TRADE_TICK_SIZE, 17
      value :SYMBOL_TRADE_CONTRACT_SIZE, 18
      value :SYMBOL_TRADE_ACCRUED_INTEREST, 19
      value :SYMBOL_TRADE_FACE_VALUE, 20
      value :SYMBOL_TRADE_LIQUIDITY_RATE, 21
      value :SYMBOL_VOLUME_MIN, 22
      value :SYMBOL_VOLUME_MAX, 23
      value :SYMBOL_VOLUME_STEP, 24
      value :SYMBOL_VOLUME_LIMIT, 25
      value :SYMBOL_SWAP_LONG, 26
      value :SYMBOL_SWAP_SHORT, 27
      value :SYMBOL_SWAP_SUNDAY, 28
      value :SYMBOL_SWAP_MONDAY, 29
      value :SYMBOL_SWAP_TUESDAY, 30
      value :SYMBOL_SWAP_WEDNESDAY, 31
      value :SYMBOL_SWAP_THURSDAY, 32
      value :SYMBOL_SWAP_FRIDAY, 33
      value :SYMBOL_SWAP_SATURDAY, 34
      value :SYMBOL_MARGIN_INITIAL, 35
      value :SYMBOL_MARGIN_MAINTENANCE, 36
      value :SYMBOL_SESSION_VOLUME, 37
      value :SYMBOL_SESSION_TURNOVER, 38
      value :SYMBOL_SESSION_INTEREST, 39
      value :SYMBOL_SESSION_BUY_ORDERS_VOLUME, 40
      value :SYMBOL_SESSION_SELL_ORDERS_VOLUME, 41
      value :SYMBOL_SESSION_OPEN, 42
      value :SYMBOL_SESSION_CLOSE, 43
      value :SYMBOL_SESSION_AW, 44
      value :SYMBOL_SESSION_PRICE_SETTLEMENT, 45
      value :SYMBOL_SESSION_PRICE_LIMIT_MIN, 46
      value :SYMBOL_SESSION_PRICE_LIMIT_MAX, 47
      value :SYMBOL_MARGIN_HEDGED, 48
      value :SYMBOL_PRICE_CHANGE, 49
      value :SYMBOL_PRICE_VOLATILITY, 50
      value :SYMBOL_PRICE_THEORETICAL, 51
      value :SYMBOL_PRICE_DELTA, 52
      value :SYMBOL_PRICE_THETA, 53
      value :SYMBOL_PRICE_GAMMA, 54
      value :SYMBOL_PRICE_VEGA, 55
      value :SYMBOL_PRICE_RHO, 56
      value :SYMBOL_PRICE_OMEGA, 57
      value :SYMBOL_PRICE_SENSITIVITY, 58
      value :SYMBOL_COUNT, 59
    end
    add_enum "mt5_term_api.SymbolInfoIntegerProperty" do
      value :SYMBOL_SUBSCRIPTION_DELAY, 0
      value :SYMBOL_SECTOR, 1
      value :SYMBOL_INDUSTRY, 2
      value :SYMBOL_CUSTOM, 3
      value :SYMBOL_BACKGROUND_COLOR, 4
      value :SYMBOL_CHART_MODE, 5
      value :SYMBOL_EXIST, 6
      value :SYMBOL_SELECT, 7
      value :SYMBOL_VISIBLE, 8
      value :SYMBOL_SESSION_DEALS, 9
      value :SYMBOL_SESSION_BUY_ORDERS, 10
      value :SYMBOL_SESSION_SELL_ORDERS, 11
      value :SYMBOL_VOLUME, 12
      value :SYMBOL_VOLUMEHIGH, 13
      value :SYMBOL_VOLUMELOW, 14
      value :SYMBOL_TIME, 15
      value :SYMBOL_TIME_MSC, 16
      value :SYMBOL_DIGITS, 17
      value :SYMBOL_SPREAD_FLOAT, 18
      value :SYMBOL_SPREAD, 19
      value :SYMBOL_TICKS_BOOKDEPTH, 20
      value :SYMBOL_TRADE_CALC_MODE, 21
      value :SYMBOL_TRADE_MODE, 22
      value :SYMBOL_START_TIME, 23
      value :SYMBOL_EXPIRATION_TIME, 24
      value :SYMBOL_TRADE_STOPS_LEVEL, 25
      value :SYMBOL_TRADE_FREEZE_LEVEL, 26
      value :SYMBOL_TRADE_EXEMODE, 27
      value :SYMBOL_SWAP_MODE, 28
      value :SYMBOL_SWAP_ROLLOVER3DAYS, 29
      value :SYMBOL_MARGIN_HEDGED_USE_LEG, 30
      value :SYMBOL_EXPIRATION_MODE, 31
      value :SYMBOL_FILLING_MODE, 32
      value :SYMBOL_ORDER_MODE, 33
      value :SYMBOL_ORDER_GTC_MODE, 34
      value :SYMBOL_OPTION_MODE, 35
      value :SYMBOL_OPTION_RIGHT, 36
    end
    add_enum "mt5_term_api.SymbolInfoStringProperty" do
      value :SYMBOL_BASIS, 0
      value :SYMBOL_CATEGORY, 1
      value :SYMBOL_COUNTRY, 2
      value :SYMBOL_SECTOR_NAME, 3
      value :SYMBOL_INDUSTRY_NAME, 4
      value :SYMBOL_CURRENCY_BASE, 5
      value :SYMBOL_CURRENCY_PROFIT, 6
      value :SYMBOL_CURRENCY_MARGIN, 7
      value :SYMBOL_BANK, 8
      value :SYMBOL_DESCRIPTION, 9
      value :SYMBOL_EXCHANGE, 10
      value :SYMBOL_FORMULA, 11
      value :SYMBOL_ISIN, 12
      value :SYMBOL_PAGE, 13
      value :SYMBOL_PATH, 14
    end
    add_enum "mt5_term_api.ENUM_ORDER_TYPE" do
      value :ORDER_TYPE_BUY, 0
      value :ORDER_TYPE_SELL, 1
      value :ORDER_TYPE_BUY_LIMIT, 2
      value :ORDER_TYPE_SELL_LIMIT, 3
      value :ORDER_TYPE_BUY_STOP, 4
      value :ORDER_TYPE_SELL_STOP, 5
      value :ORDER_TYPE_BUY_STOP_LIMIT, 6
      value :ORDER_TYPE_SELL_STOP_LIMIT, 7
      value :ORDER_TYPE_CLOSE_BY, 8
    end
    add_enum "mt5_term_api.DayOfWeek" do
      value :SUNDAY, 0
      value :MONDAY, 1
      value :TUESDAY, 2
      value :WEDNESDAY, 3
      value :THURSDAY, 4
      value :FRIDAY, 5
      value :SATURDAY, 6
    end
    add_enum "mt5_term_api.BookType" do
      value :BOOK_TYPE_SELL, 0
      value :BOOK_TYPE_BUY, 1
      value :BOOK_TYPE_SELL_MARKET, 2
      value :BOOK_TYPE_BUY_MARKET, 3
    end
  end
end

module Mt5TermApi
  SymbolListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolListRequest").msgclass
  SymbolListReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolListReply").msgclass
  SymbolListData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolListData").msgclass
  SymbolsTotalRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolsTotalRequest").msgclass
  SymbolsTotalReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolsTotalReply").msgclass
  SymbolsTotalData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolsTotalData").msgclass
  SymbolExistRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolExistRequest").msgclass
  SymbolExistReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolExistReply").msgclass
  SymbolExistData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolExistData").msgclass
  SymbolNameRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolNameRequest").msgclass
  SymbolNameReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolNameReply").msgclass
  SymbolNameData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolNameData").msgclass
  SymbolSelectRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolSelectRequest").msgclass
  SymbolSelectReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolSelectReply").msgclass
  SymbolSelectData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolSelectData").msgclass
  SymbolIsSynchronizedRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolIsSynchronizedRequest").msgclass
  SymbolIsSynchronizedReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolIsSynchronizedReply").msgclass
  SymbolIsSynchronizedData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolIsSynchronizedData").msgclass
  SymbolInfoDoubleRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolInfoDoubleRequest").msgclass
  SymbolInfoDoubleReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolInfoDoubleReply").msgclass
  SymbolInfoDoubleData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolInfoDoubleData").msgclass
  SymbolInfoIntegerRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolInfoIntegerRequest").msgclass
  SymbolInfoIntegerReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolInfoIntegerReply").msgclass
  SymbolInfoIntegerData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolInfoIntegerData").msgclass
  SymbolInfoStringRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolInfoStringRequest").msgclass
  SymbolInfoStringReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolInfoStringReply").msgclass
  SymbolInfoStringData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolInfoStringData").msgclass
  SymbolInfoMarginRateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolInfoMarginRateRequest").msgclass
  SymbolInfoMarginRateReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolInfoMarginRateReply").msgclass
  SymbolInfoMarginRateData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolInfoMarginRateData").msgclass
  SymbolInfoTickRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolInfoTickRequest").msgclass
  SymbolInfoTickRequestReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolInfoTickRequestReply").msgclass
  MrpcMqlTick = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.MrpcMqlTick").msgclass
  SymbolInfoSessionQuoteRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolInfoSessionQuoteRequest").msgclass
  SymbolInfoSessionQuoteReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolInfoSessionQuoteReply").msgclass
  SymbolInfoSessionQuoteData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolInfoSessionQuoteData").msgclass
  SymbolInfoSessionTradeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolInfoSessionTradeRequest").msgclass
  SymbolInfoSessionTradeReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolInfoSessionTradeReply").msgclass
  SymbolInfoSessionTradeData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolInfoSessionTradeData").msgclass
  MarketBookAddRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.MarketBookAddRequest").msgclass
  MarketBookAddReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.MarketBookAddReply").msgclass
  MarketBookAddData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.MarketBookAddData").msgclass
  MarketBookReleaseRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.MarketBookReleaseRequest").msgclass
  MarketBookReleaseReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.MarketBookReleaseReply").msgclass
  MarketBookReleaseData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.MarketBookReleaseData").msgclass
  MarketBookGetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.MarketBookGetRequest").msgclass
  MarketBookGetReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.MarketBookGetReply").msgclass
  MarketBookGetData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.MarketBookGetData").msgclass
  MrpcMqlBookInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.MrpcMqlBookInfo").msgclass
  PriceHistoryRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.PriceHistoryRequest").msgclass
  PriceHistoryReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.PriceHistoryReply").msgclass
  PriceHistoryData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.PriceHistoryData").msgclass
  PriceBar = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.PriceBar").msgclass
  SymbolInfoDoubleProperty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolInfoDoubleProperty").enummodule
  SymbolInfoIntegerProperty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolInfoIntegerProperty").enummodule
  SymbolInfoStringProperty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SymbolInfoStringProperty").enummodule
  ENUM_ORDER_TYPE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ENUM_ORDER_TYPE").enummodule
  DayOfWeek = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.DayOfWeek").enummodule
  BookType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.BookType").enummodule
end
