# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mt5-term-api-trade-stats.proto for package 'mt5_term_api'

require 'grpc'
require 'mt5-term-api-trade-stats_pb'

module Mt5TermApi
  module TradeStats
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mt5_term_api.TradeStats'

      # Trading statistics calculated from order history and open orders
      # [DefaultValues]
      # {
      #   "from": "2024-01-01T00:00:00"
      # }
      rpc :TradeStats, ::Mt5TermApi::TradeStatsRequest, ::Mt5TermApi::TradeStatsReply
      # Trading statistics with equity history chart points
      # [DefaultValues]
      # {
      #   "from": "2024-01-01T00:00:00",
      #   "excludeSameBars": true
      # }
      rpc :TradeStatsEquityHistory, ::Mt5TermApi::TradeStatsEquityHistoryRequest, ::Mt5TermApi::TradeStatsEquityHistoryReply
      # Equity history curve points with drawdown calculation
      # [DefaultValues]
      # {
      #   "from": "2024-10-01T00:00:00",
      #   "excludeSameBars": true
      # }
      rpc :EquityHistory, ::Mt5TermApi::EquityHistoryRequest, ::Mt5TermApi::EquityHistoryReply
      # Maximum and minimum unrealized profit/loss per trade
      # [DefaultValues]
      # {
      #   "from": "2024-01-01T00:00:00"
      # }
      rpc :TradeUnrealizedPL, ::Mt5TermApi::TradeUnrealizedPLRequest, ::Mt5TermApi::TradeUnrealizedPLReply
    end

    Stub = Service.rpc_stub_class
  end
end
