# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mt5-term-api-connection.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'google/protobuf/wrappers_pb'
require 'mrpc-mt5-error_pb'
require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("mt5-term-api-connection.proto", :syntax => :proto3) do
    add_message "mt5_term_api.JournalRequest" do
    end
    add_message "mt5_term_api.JournalReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.GetTerminalJournalData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.OnJournalRequest" do
    end
    add_message "mt5_term_api.OnJournalReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.GetTerminalJournalData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.GetTerminalJournalData" do
      repeated :rows, :message, 1, "mt5_term_api.TerminalJournalRow"
    end
    add_message "mt5_term_api.TerminalJournalRow" do
      optional :time, :message, 1, "google.protobuf.Timestamp"
      optional :source, :string, 2
      optional :message, :string, 3
    end
    add_message "mt5_term_api.GetBrokerServersByBrokerNameRequest" do
      optional :BrokerName, :string, 1
    end
    add_message "mt5_term_api.GetBrokerServersByBrokerNameReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.GetBrokerServersByBrokerNameData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.GetBrokerServersByBrokerNameData" do
      repeated :result, :message, 1, "mt5_term_api.GetBrokerServersByBrokerNameData.BrokerResult"
    end
    add_message "mt5_term_api.GetBrokerServersByBrokerNameData.BrokerResult" do
      optional :company, :string, 1
      repeated :results, :message, 2, "mt5_term_api.GetBrokerServersByBrokerNameData.BrokerServer"
    end
    add_message "mt5_term_api.GetBrokerServersByBrokerNameData.BrokerServer" do
      optional :name, :string, 1
      proto3_optional :logo_url, :string, 2
      proto3_optional :site, :string, 3
      repeated :access, :string, 4
    end
    add_message "mt5_term_api.ConnectExRequest" do
      optional :user, :uint64, 1
      optional :password, :string, 2
      optional :mt_cluster_name, :string, 3
      repeated :experts_to_add, :message, 5, "mt5_term_api.ExpertAdviser"
      proto3_optional :timeout_seconds, :uint32, 6
      proto3_optional :name, :string, 7
      proto3_optional :expiration, :uint32, 8
    end
    add_message "mt5_term_api.ConnectByTokenRequest" do
      proto3_optional :timeout_seconds, :uint32, 2
      proto3_optional :expiration, :uint32, 3
    end
    add_message "mt5_term_api.ConnectExReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.ConnectData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.ReconnectRequest" do
      proto3_optional :force_reconnection, :bool, 1
    end
    add_message "mt5_term_api.ReconnectReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.ReconnectData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.ReconnectData" do
      optional :terminal_was_recreated, :bool, 1
      optional :terminal_type, :enum, 2, "mt5_term_api.TerminalType"
      optional :terminal_instance_guid, :string, 3
      optional :old_terminal_full_live_time_seconds, :int64, 4
      repeated :old_log_files, :message, 5, "mt5_term_api.LogFileInfo"
    end
    add_message "mt5_term_api.ConnectRequest" do
      optional :user, :uint64, 1
      optional :password, :string, 2
      optional :host, :string, 3
      optional :port, :int32, 4
      repeated :experts_to_add, :message, 5, "mt5_term_api.ExpertAdviser"
      proto3_optional :timeout_seconds, :uint32, 6
      proto3_optional :name, :string, 7
      proto3_optional :expiration, :uint32, 8
    end
    add_message "mt5_term_api.ExpertAdviser" do
      optional :file_name, :string, 1
      optional :file_content, :bytes, 2
    end
    add_message "mt5_term_api.ConnectReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.ConnectData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.ConnectData" do
      optional :terminal_instance_guid, :string, 1
      optional :terminal_type, :enum, 3, "mt5_term_api.TerminalType"
    end
    add_message "mt5_term_api.ConnectProxyRequest" do
      optional :user, :uint64, 1
      optional :password, :string, 2
      optional :host, :string, 3
      optional :port, :int32, 4
      optional :proxyUser, :string, 5
      optional :proxyPassword, :string, 6
      optional :proxyHost, :string, 7
      optional :proxyPort, :uint32, 8
      optional :proxyType, :enum, 9, "mt5_term_api.ProxyTypes"
      repeated :experts_to_add, :message, 10, "mt5_term_api.ExpertAdviser"
      proto3_optional :timeout_seconds, :uint32, 11
      proto3_optional :name, :string, 12
      proto3_optional :expiration, :uint32, 13
    end
    add_message "mt5_term_api.ConnectProxyReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.ConnectProxyData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.ConnectProxyData" do
      optional :unique_identifier, :string, 1
      optional :terminal_type, :enum, 2, "mt5_term_api.TerminalType"
    end
    add_message "mt5_term_api.CheckConnectRequest" do
    end
    add_message "mt5_term_api.CheckConnectReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.CheckConnectData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.CheckConnectData" do
      optional :unique_identifier, :string, 1
      optional :health_check, :message, 2, "mt5_term_api.TerminalHealthCheck"
    end
    add_message "mt5_term_api.TerminalHealthCheck" do
      optional :is_alive, :bool, 1
      optional :ErrorMessage, :message, 2, "google.protobuf.StringValue"
      optional :ErrorCode, :message, 3, "google.protobuf.StringValue"
      optional :StackTrace, :message, 4, "google.protobuf.StringValue"
      optional :has_authorization_error, :bool, 5
      optional :api_is_alive, :bool, 6
      optional :terminal_is_connected_to_mt_server, :bool, 7
    end
    add_message "mt5_term_api.DisconnectRequest" do
      proto3_optional :reason, :string, 1
    end
    add_message "mt5_term_api.DisconnectReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.DisconnectData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.DisconnectData" do
      optional :unique_identifier, :string, 1
      optional :full_life_time_seconds, :int64, 2
    end
    add_message "mt5_term_api.ScreenshotRequest" do
    end
    add_message "mt5_term_api.ScreenshotReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.ScreenshotData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.ScreenshotData" do
      optional :image_data, :bytes, 1
      optional :display_number, :int32, 2
      optional :terminal_id, :string, 3
      optional :content_type, :string, 4
    end
    add_message "mt5_term_api.GetIdRequest" do
      optional :user, :string, 1
      optional :password, :string, 2
    end
    add_message "mt5_term_api.GetIdReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.GetIdData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.GetIdData" do
      optional :id, :string, 1
    end
    add_message "mt5_term_api.ConnectStreamEvent" do
      optional :step, :string, 1
      optional :message, :string, 2
      optional :level, :string, 3
      optional :elapsed_ms, :int64, 4
      optional :timestamp, :message, 5, "google.protobuf.Timestamp"
      optional :is_final, :bool, 6
      optional :connect_data, :message, 7, "mt5_term_api.ConnectData"
      optional :error_data, :message, 8, "mt5_term_api.Error"
    end
    add_message "mt5_term_api.ConnectStateRequest" do
    end
    add_message "mt5_term_api.ConnectStateReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.ConnectStateData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.OnConnectStateRequest" do
      repeated :terminal_ids, :string, 1
    end
    add_message "mt5_term_api.OnConnectStateReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.ConnectStateData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.ConnectStateData" do
      optional :id, :string, 1
      optional :state, :string, 2
      optional :is_connected, :bool, 3
      optional :is_alive, :bool, 4
      optional :api_is_alive, :bool, 5
      optional :server, :string, 6
      optional :account, :uint64, 7
      optional :error_message, :string, 8
      optional :timestamp, :message, 9, "google.protobuf.Timestamp"
    end
    add_message "mt5_term_api.ConnectionStatusRequest" do
    end
    add_message "mt5_term_api.ConnectionStatusReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.ConnectionStatusData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.ConnectionStatusData" do
      optional :id, :string, 1
      optional :is_connected, :bool, 2
      optional :is_alive, :bool, 3
      optional :api_is_alive, :bool, 4
      optional :server, :string, 5
      optional :account, :uint64, 6
      optional :error_message, :string, 7
      optional :state, :string, 8
    end
    add_enum "mt5_term_api.ProxyTypes" do
      value :None, 0
      value :Https, 1
      value :Socks4, 2
      value :Socks5, 3
    end
    add_enum "mt5_term_api.TerminalType" do
      value :MT4, 0
      value :MT5, 1
    end
  end
end

module Mt5TermApi
  JournalRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.JournalRequest").msgclass
  JournalReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.JournalReply").msgclass
  OnJournalRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OnJournalRequest").msgclass
  OnJournalReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OnJournalReply").msgclass
  GetTerminalJournalData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.GetTerminalJournalData").msgclass
  TerminalJournalRow = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.TerminalJournalRow").msgclass
  GetBrokerServersByBrokerNameRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.GetBrokerServersByBrokerNameRequest").msgclass
  GetBrokerServersByBrokerNameReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.GetBrokerServersByBrokerNameReply").msgclass
  GetBrokerServersByBrokerNameData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.GetBrokerServersByBrokerNameData").msgclass
  GetBrokerServersByBrokerNameData::BrokerResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.GetBrokerServersByBrokerNameData.BrokerResult").msgclass
  GetBrokerServersByBrokerNameData::BrokerServer = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.GetBrokerServersByBrokerNameData.BrokerServer").msgclass
  ConnectExRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ConnectExRequest").msgclass
  ConnectByTokenRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ConnectByTokenRequest").msgclass
  ConnectExReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ConnectExReply").msgclass
  ReconnectRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ReconnectRequest").msgclass
  ReconnectReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ReconnectReply").msgclass
  ReconnectData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ReconnectData").msgclass
  ConnectRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ConnectRequest").msgclass
  ExpertAdviser = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ExpertAdviser").msgclass
  ConnectReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ConnectReply").msgclass
  ConnectData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ConnectData").msgclass
  ConnectProxyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ConnectProxyRequest").msgclass
  ConnectProxyReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ConnectProxyReply").msgclass
  ConnectProxyData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ConnectProxyData").msgclass
  CheckConnectRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.CheckConnectRequest").msgclass
  CheckConnectReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.CheckConnectReply").msgclass
  CheckConnectData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.CheckConnectData").msgclass
  TerminalHealthCheck = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.TerminalHealthCheck").msgclass
  DisconnectRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.DisconnectRequest").msgclass
  DisconnectReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.DisconnectReply").msgclass
  DisconnectData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.DisconnectData").msgclass
  ScreenshotRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ScreenshotRequest").msgclass
  ScreenshotReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ScreenshotReply").msgclass
  ScreenshotData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ScreenshotData").msgclass
  GetIdRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.GetIdRequest").msgclass
  GetIdReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.GetIdReply").msgclass
  GetIdData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.GetIdData").msgclass
  ConnectStreamEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ConnectStreamEvent").msgclass
  ConnectStateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ConnectStateRequest").msgclass
  ConnectStateReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ConnectStateReply").msgclass
  OnConnectStateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OnConnectStateRequest").msgclass
  OnConnectStateReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OnConnectStateReply").msgclass
  ConnectStateData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ConnectStateData").msgclass
  ConnectionStatusRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ConnectionStatusRequest").msgclass
  ConnectionStatusReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ConnectionStatusReply").msgclass
  ConnectionStatusData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ConnectionStatusData").msgclass
  ProxyTypes = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ProxyTypes").enummodule
  TerminalType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.TerminalType").enummodule
end
