# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mt5-term-api-account-helper.proto for package 'mt5_term_api'

require 'grpc'
require 'mt5-term-api-account-helper_pb'

module Mt5TermApi
  module AccountHelper
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mt5_term_api.AccountHelper'

      # Some information about account
      rpc :AccountSummary, ::Mt5TermApi::AccountSummaryRequest, ::Mt5TermApi::AccountSummaryReply
      # Orders History
      # [DefaultValues]
      # {
      #   "pageNumber": "0",
      #   "itemsPerPage": "0",
      # }  
      rpc :OrderHistory, ::Mt5TermApi::OrderHistoryRequest, ::Mt5TermApi::OrderHistoryReply
      # Pending orders and opened positions
      rpc :OpenedOrders, ::Mt5TermApi::OpenedOrdersRequest, ::Mt5TermApi::OpenedOrdersReply
      # Just opened order tickets
      rpc :OpenedOrdersTickets, ::Mt5TermApi::OpenedOrdersTicketsRequest, ::Mt5TermApi::OpenedOrdersTicketsReply
      # Full information about symbol and his group for several symbols
      rpc :SymbolParamsMany, ::Mt5TermApi::SymbolParamsManyRequest, ::Mt5TermApi::SymbolParamsManyReply
      # Tick value as array
      rpc :TickValueWithSize, ::Mt5TermApi::TickValueWithSizeRequest, ::Mt5TermApi::TickValueWithSizeReply
      # History positions
      rpc :PositionsHistory, ::Mt5TermApi::PositionsHistoryRequest, ::Mt5TermApi::PositionsHistoryReply
      rpc :AllHistoryOrders, ::Mt5TermApi::AllHistoryOrdersRequest, ::Mt5TermApi::AllHistoryOrdersReply
    end

    Stub = Service.rpc_stub_class
  end
end
