# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mt5-term-api-trade-functions.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'google/protobuf/timestamp_pb'
require 'google/protobuf/empty_pb'
require 'mrpc-mt5-error_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("mt5-term-api-trade-functions.proto", :syntax => :proto3) do
    add_message "mt5_term_api.OrderCalcMarginRequest" do
      optional :symbol, :string, 1
      optional :order_type, :enum, 2, "mt5_term_api.ENUM_ORDER_TYPE_TF"
      optional :volume, :double, 3
      optional :open_price, :double, 4
    end
    add_message "mt5_term_api.OrderCalcMarginReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.OrderCalcMarginData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.OrderCalcMarginData" do
      optional :margin, :double, 1
    end
    add_message "mt5_term_api.OrderCalcProfitRequest" do
      optional :order_type, :enum, 1, "mt5_term_api.ENUM_ORDER_TYPE_TF"
      optional :symbol, :string, 2
      optional :volume, :double, 3
      optional :open_price, :double, 4
      optional :close_price, :double, 5
    end
    add_message "mt5_term_api.OrderCalcProfitReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.OrderCalcProfitData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.OrderCalcProfitData" do
      optional :profit, :double, 1
    end
    add_message "mt5_term_api.OrderCheckRequest" do
      optional :mql_trade_request, :message, 1, "mt5_term_api.MrpcMqlTradeRequest"
    end
    add_message "mt5_term_api.OrderCheckReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.OrderCheckData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.OrderCheckData" do
      optional :mql_trade_check_result, :message, 1, "mt5_term_api.MrpcMqlTradeCheckResult"
    end
    add_message "mt5_term_api.MrpcMqlTradeRequest" do
      optional :action, :enum, 1, "mt5_term_api.MRPC_ENUM_TRADE_REQUEST_ACTIONS"
      optional :expert_advisor_magic_number, :uint64, 2
      optional :order, :uint64, 3
      optional :symbol, :string, 4
      optional :volume, :double, 5
      optional :price, :double, 6
      optional :stop_limit, :double, 7
      optional :stop_loss, :double, 8
      optional :take_profit, :double, 9
      optional :deviation, :uint64, 10
      optional :order_type, :enum, 11, "mt5_term_api.ENUM_ORDER_TYPE_TF"
      optional :type_filling, :enum, 12, "mt5_term_api.MRPC_ENUM_ORDER_TYPE_FILLING"
      optional :type_time, :enum, 13, "mt5_term_api.MRPC_ENUM_ORDER_TYPE_TIME"
      optional :expiration, :message, 14, "google.protobuf.Timestamp"
      optional :comment, :string, 15
      optional :position, :uint64, 16
      optional :position_by, :uint64, 17
    end
    add_message "mt5_term_api.MrpcMqlTradeCheckResult" do
      optional :returned_code, :uint32, 1
      optional :balance_after_deal, :double, 2
      optional :equity_after_deal, :double, 3
      optional :profit, :double, 4
      optional :margin, :double, 5
      optional :free_margin, :double, 6
      optional :margin_level, :double, 7
      optional :comment, :string, 8
    end
    add_message "mt5_term_api.PositionsTotalReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.PositionsTotalData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.PositionsTotalData" do
      optional :total_positions, :int32, 1
    end
    add_enum "mt5_term_api.ENUM_ORDER_TYPE_TF" do
      value :ORDER_TYPE_TF_BUY, 0
      value :ORDER_TYPE_TF_SELL, 1
      value :ORDER_TYPE_TF_BUY_LIMIT, 2
      value :ORDER_TYPE_TF_SELL_LIMIT, 3
      value :ORDER_TYPE_TF_BUY_STOP, 4
      value :ORDER_TYPE_TF_SELL_STOP, 5
      value :ORDER_TYPE_TF_BUY_STOP_LIMIT, 6
      value :ORDER_TYPE_TF_SELL_STOP_LIMIT, 7
      value :ORDER_TYPE_TF_CLOSE_BY, 8
    end
    add_enum "mt5_term_api.MRPC_ENUM_TRADE_REQUEST_ACTIONS" do
      value :TRADE_ACTION_DEAL, 0
      value :TRADE_ACTION_PENDING, 1
      value :TRADE_ACTION_SLTP, 2
      value :TRADE_ACTION_MODIFY, 3
      value :TRADE_ACTION_REMOVE, 4
      value :TRADE_ACTION_CLOSE_BY, 5
    end
    add_enum "mt5_term_api.MRPC_ENUM_ORDER_TYPE_FILLING" do
      value :ORDER_FILLING_FOK, 0
      value :ORDER_FILLING_IOC, 1
      value :ORDER_FILLING_BOC, 3
      value :ORDER_FILLING_RETURN, 2
    end
    add_enum "mt5_term_api.MRPC_ENUM_ORDER_TYPE_TIME" do
      value :ORDER_TIME_GTC, 0
      value :ORDER_TIME_DAY, 1
      value :ORDER_TIME_SPECIFIED, 2
      value :ORDER_TIME_SPECIFIED_DAY, 3
    end
  end
end

module Mt5TermApi
  OrderCalcMarginRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OrderCalcMarginRequest").msgclass
  OrderCalcMarginReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OrderCalcMarginReply").msgclass
  OrderCalcMarginData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OrderCalcMarginData").msgclass
  OrderCalcProfitRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OrderCalcProfitRequest").msgclass
  OrderCalcProfitReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OrderCalcProfitReply").msgclass
  OrderCalcProfitData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OrderCalcProfitData").msgclass
  OrderCheckRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OrderCheckRequest").msgclass
  OrderCheckReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OrderCheckReply").msgclass
  OrderCheckData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OrderCheckData").msgclass
  MrpcMqlTradeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.MrpcMqlTradeRequest").msgclass
  MrpcMqlTradeCheckResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.MrpcMqlTradeCheckResult").msgclass
  PositionsTotalReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.PositionsTotalReply").msgclass
  PositionsTotalData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.PositionsTotalData").msgclass
  ENUM_ORDER_TYPE_TF = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ENUM_ORDER_TYPE_TF").enummodule
  MRPC_ENUM_TRADE_REQUEST_ACTIONS = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.MRPC_ENUM_TRADE_REQUEST_ACTIONS").enummodule
  MRPC_ENUM_ORDER_TYPE_FILLING = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.MRPC_ENUM_ORDER_TYPE_FILLING").enummodule
  MRPC_ENUM_ORDER_TYPE_TIME = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.MRPC_ENUM_ORDER_TYPE_TIME").enummodule
end
