# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mt5-term-api-market-info.proto for package 'mt5_term_api'

require 'grpc'
require 'mt5-term-api-market-info_pb'

module Mt5TermApi
  module MarketInfo
    # The MarketInfo service provides information about the current state of the market
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mt5_term_api.MarketInfo'

      # Returns the number of available (selected in Market Watch or all) symbols
      # https://www.mql5.com/en/docs/marketinformation/symbolstotal
      rpc :SymbolsTotal, ::Mt5TermApi::SymbolsTotalRequest, ::Mt5TermApi::SymbolsTotalReply
      # Checks if a symbol with a specified name exists
      # https://www.mql5.com/en/docs/marketinformation/symbolexist
      rpc :SymbolExist, ::Mt5TermApi::SymbolExistRequest, ::Mt5TermApi::SymbolExistReply
      # Returns the name of a symbol
      # https://www.mql5.com/en/docs/marketinformation/symbolname 
      rpc :SymbolName, ::Mt5TermApi::SymbolNameRequest, ::Mt5TermApi::SymbolNameReply
      # Selects a symbol in the Market Watch window or removes a symbol from the window
      # https://www.mql5.com/en/docs/marketinformation/symbolselect
      rpc :SymbolSelect, ::Mt5TermApi::SymbolSelectRequest, ::Mt5TermApi::SymbolSelectReply
      # The function checks whether data of a selected symbol in the terminal are synchronized with data on the trade server.
      # https://www.mql5.com/en/docs/marketinformation/symbolissynchronized
      rpc :SymbolIsSynchronized, ::Mt5TermApi::SymbolIsSynchronizedRequest, ::Mt5TermApi::SymbolIsSynchronizedReply
      # Returns the corresponding property of a specified symbol. Immediately returns the property value.
      # https://www.mql5.com/en/docs/marketinformation/symbolinfodouble
      rpc :SymbolInfoDouble, ::Mt5TermApi::SymbolInfoDoubleRequest, ::Mt5TermApi::SymbolInfoDoubleReply
      # Returns the corresponding property of a specified symbol. 
      # https://www.mql5.com/en/docs/marketinformation/symbolinfointeger
      rpc :SymbolInfoInteger, ::Mt5TermApi::SymbolInfoIntegerRequest, ::Mt5TermApi::SymbolInfoIntegerReply
      # Returns the corresponding property of a specified symbol. Immediately returns the property value
      # https://www.mql5.com/en/docs/marketinformation/symbolinfostring  
      rpc :SymbolInfoString, ::Mt5TermApi::SymbolInfoStringRequest, ::Mt5TermApi::SymbolInfoStringReply
      # Returns the margin rates depending on the order type and direction
      # https://www.mql5.com/en/docs/marketinformation/symbolinfomarginrate
      rpc :SymbolInfoMarginRate, ::Mt5TermApi::SymbolInfoMarginRateRequest, ::Mt5TermApi::SymbolInfoMarginRateReply
      # The function returns current prices of a specified symbol in a variable of the MqlTick type
      # https://www.mql5.com/en/docs/marketinformation/symbolinfotick
      rpc :SymbolInfoTick, ::Mt5TermApi::SymbolInfoTickRequest, ::Mt5TermApi::SymbolInfoTickRequestReply
      # Allows receiving time of beginning and end of the specified quoting sessions for a specified symbol and day of week
      # https://www.mql5.com/en/docs/marketinformation/symbolinfosessionquote
      rpc :SymbolInfoSessionQuote, ::Mt5TermApi::SymbolInfoSessionQuoteRequest, ::Mt5TermApi::SymbolInfoSessionQuoteReply
      # Allows receiving time of beginning and end of the specified trading sessions for a specified symbol and day of week
      # https://www.mql5.com/en/docs/marketinformation/symbolinfosessiontrade
      rpc :SymbolInfoSessionTrade, ::Mt5TermApi::SymbolInfoSessionTradeRequest, ::Mt5TermApi::SymbolInfoSessionTradeReply
      # Provides opening of Depth of Market for a selected symbol, and subscribes for receiving notifications of the DOM changes
      # https://www.mql5.com/en/docs/marketinformation/marketbookadd
      rpc :MarketBookAdd, ::Mt5TermApi::MarketBookAddRequest, ::Mt5TermApi::MarketBookAddReply
      # Provides closing of Depth of Market for a selected symbol, and cancels the subscription for receiving notifications of the DOM changes
      # https://www.mql5.com/en/docs/marketinformation/marketbookrelease
      rpc :MarketBookRelease, ::Mt5TermApi::MarketBookReleaseRequest, ::Mt5TermApi::MarketBookReleaseReply
      # Returns a structure array MqlBookInfo containing records of the Depth of Market of a specified symbol
      # https://www.mql5.com/en/docs/marketinformation/marketbookget
      rpc :MarketBookGet, ::Mt5TermApi::MarketBookGetRequest, ::Mt5TermApi::MarketBookGetReply
      # Returns a collection of a broker symbols
      rpc :SymbolList, ::Mt5TermApi::SymbolListRequest, ::Mt5TermApi::SymbolListReply
      # Historical bars for a symbol - what a chart is drawn from.
      #
      # This API had no such call, so a client holding a terminal id could list symbols, read a live
      # price and trade, and still not draw a chart. Ticks are not candles.
      rpc :PriceHistory, ::Mt5TermApi::PriceHistoryRequest, ::Mt5TermApi::PriceHistoryReply
    end

    Stub = Service.rpc_stub_class
  end
end
