# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mt5-term-api-trading-helper.proto for package 'mt5_term_api'

require 'grpc'
require 'mt5-term-api-trading-helper_pb'

module Mt5TermApi
  module TradingHelper
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mt5_term_api.TradingHelper'

      # Send market or pending order
      # [DefaultValues]
      # {
      #   "symbol": "EURUSD",
      #   "operation": "TMT5_ORDER_TYPE_BUY",
      #   "volume": "0.1"
      # }
      rpc :OrderSend, ::Mt5TermApi::OrderSendRequest, ::Mt5TermApi::OrderSendReply
      # Send market or pending order immediately, with no Market Watch or quotes preparation.
      # Same request and reply as OrderSend, but nothing is checked first and quotes_wait_ms is
      # ignored. Use only for a symbol already known to be streaming; otherwise the trade server
      # rejects the order (ErrMarketLasttimeUnknown 4304 "no ticks" and friends).
      # [DefaultValues]
      # {
      #   "symbol": "EURUSD",
      #   "operation": "TMT5_ORDER_TYPE_BUY",
      #   "volume": "0.1"
      # }
      rpc :OrderSendWithoutChecks, ::Mt5TermApi::OrderSendRequest, ::Mt5TermApi::OrderSendReply
      # Modify market or pending order
      rpc :OrderModify, ::Mt5TermApi::OrderModifyRequest, ::Mt5TermApi::OrderModifyReply
      # Close market or pending order
      rpc :OrderClose, ::Mt5TermApi::OrderCloseRequest, ::Mt5TermApi::OrderCloseReply
    end

    Stub = Service.rpc_stub_class
  end
end
