# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mt5-term-api-demo-account.proto for package 'mt5_term_api'

require 'grpc'
require 'mt5-term-api-demo-account_pb'

module Mt5TermApi
  module DemoAccount
    # Demo account creation service.
    # Automates the MT5 "Open an Account" wizard via Win32 GUI automation.
    # Does NOT require 'id' header — auto-picks any available terminal.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mt5_term_api.DemoAccount'

      # Open a demo account. Full wizard flow: search → select → fill form → register.
      # Returns login, password, and investor password for the new demo account.
      # [DefaultValues]
      # {
      #   "company": "MetaQuotes Ltd.",
      #   "firstName": "Test",
      #   "lastName": "User",
      #   "email": "test@test.com",
      #   "phone": "+1234567890",
      #   "timeoutSeconds": "60"
      # }
      rpc :OpenDemoAccount, ::Mt5TermApi::GuiDemoOpenAccountRequest, ::Mt5TermApi::GuiDemoOpenAccountReply
      # Interactive step-by-step demo account opening wizard.
      # Bidirectional streaming session: search company -> select -> form schema -> submit -> 2FA (if any) -> completed.
      rpc :DemoOpenAccountInteractive, stream(::Mt5TermApi::GuiDemoInteractiveClientMessage), stream(::Mt5TermApi::GuiDemoInteractiveServerMessage)
    end

    Stub = Service.rpc_stub_class
  end
end
