# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mt5-term-api-charts.proto for package 'mt5_term_api'

require 'grpc'
require 'mt5-term-api-charts_pb'

module Mt5TermApi
  module Charts
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mt5_term_api.Charts'

      rpc :OpenTerminalChartWithEa, ::Mt5TermApi::OpenTerminalChartWithEaRequest, ::Mt5TermApi::OpenTerminalChartWithEaReply
      rpc :GetEaParams, ::Mt5TermApi::GetEaParamsRequest, ::Mt5TermApi::GetEaParamsReply
      rpc :AttachEa, ::Mt5TermApi::AttachEaRequest, ::Mt5TermApi::AttachEaReply
      rpc :GetRunningEas, ::Mt5TermApi::GetRunningEasRequest, ::Mt5TermApi::GetRunningEasReply
      rpc :GetEaLogs, ::Mt5TermApi::GetEaLogsRequest, ::Mt5TermApi::GetEaLogsReply
      rpc :StopEa, ::Mt5TermApi::StopEaRequest, ::Mt5TermApi::StopEaReply
    end

    Stub = Service.rpc_stub_class
  end
end
