# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mt5-term-api-vnc.proto for package 'mt5_term_api'

require 'grpc'
require 'mt5-term-api-vnc_pb'

module Mt5TermApi
  module VncService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mt5_term_api.VncService'

      # Bidirectional stream: raw VNC (RFB) binary data flows in both directions
      rpc :VncStream, stream(::Mt5TermApi::VncData), stream(::Mt5TermApi::VncData)
    end

    Stub = Service.rpc_stub_class
  end
end
