# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mt5-term-api-trade-stats.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'google/api/annotations_pb'
require 'mrpc-mt5-error_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("mt5-term-api-trade-stats.proto", :syntax => :proto3) do
    add_message "mt5_term_api.TradeStatsRequest" do
      proto3_optional :from, :string, 1
    end
    add_message "mt5_term_api.TradeStatsReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.StatsData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.TradeStatsEquityHistoryRequest" do
      proto3_optional :from, :string, 1
      proto3_optional :exclude_same_bars, :bool, 2
    end
    add_message "mt5_term_api.TradeStatsEquityHistoryReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.StatsWithChartsData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.EquityHistoryRequest" do
      proto3_optional :from, :string, 1
      proto3_optional :exclude_same_bars, :bool, 2
    end
    add_message "mt5_term_api.EquityHistoryReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.EquityHistoryData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.TradeUnrealizedPLRequest" do
      proto3_optional :from, :string, 1
    end
    add_message "mt5_term_api.TradeUnrealizedPLReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.TradeUnrealizedPLData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.StatsData" do
      optional :summary, :message, 1, "mt5_term_api.TradeSummaryData"
      optional :max_balance_drawdown_raw, :double, 2
      optional :max_balance_drawdown_relative, :double, 3
      optional :max_equity_drawdown_raw, :double, 4
      optional :max_equity_drawdown_relative, :double, 5
      repeated :markets, :message, 6, "mt5_term_api.MarketTradeCountData"
      optional :profitability, :message, 7, "mt5_term_api.ProfitabilityData"
      optional :pips, :double, 8
      optional :lots, :double, 9
      optional :comissions, :double, 10
      optional :average_win, :message, 11, "mt5_term_api.AveragePipsUsdData"
      optional :average_lost, :message, 12, "mt5_term_api.AveragePipsUsdData"
      optional :longs_won, :message, 13, "mt5_term_api.WonData"
      optional :shorts_won, :message, 14, "mt5_term_api.WonData"
      optional :best_trade, :message, 15, "mt5_term_api.ProfitData"
      optional :worst_trade, :message, 16, "mt5_term_api.ProfitData"
      optional :best_trade_pips, :message, 17, "mt5_term_api.ProfitData"
      optional :worst_trade_pips, :message, 18, "mt5_term_api.ProfitData"
      optional :average_trade_length, :string, 19
      optional :profit_factor, :double, 20
      optional :standard_deviation, :double, 21
      optional :sharpe_ratio, :double, 22
      optional :z_score, :message, 23, "mt5_term_api.ZScoreData"
      optional :expectancy, :message, 24, "mt5_term_api.ExpectancyData"
      optional :ghpr, :double, 25
      optional :trades, :int64, 26
    end
    add_message "mt5_term_api.TradeSummaryData" do
      optional :open_trades, :int32, 1
      optional :open_profit, :double, 2
      optional :day_profit, :double, 3
      optional :week_profit, :double, 4
      optional :month_profit, :double, 5
      optional :total_profit, :double, 6
    end
    add_message "mt5_term_api.MarketTradeCountData" do
      optional :market_name, :string, 1
      optional :count, :int32, 2
    end
    add_message "mt5_term_api.ProfitabilityData" do
      optional :won_trades, :int64, 1
      optional :won_trades_percent, :double, 2
      optional :lost_trades, :int64, 3
      optional :lost_trades_percent, :double, 4
    end
    add_message "mt5_term_api.AveragePipsUsdData" do
      optional :average_pips, :double, 1
      optional :average_usd, :double, 2
    end
    add_message "mt5_term_api.WonData" do
      optional :won_count, :int32, 1
      optional :all, :int32, 2
      optional :won_persent, :double, 3
    end
    add_message "mt5_term_api.ProfitData" do
      optional :tiket, :int64, 1
      optional :date, :message, 2, "google.protobuf.Timestamp"
      optional :profit, :double, 3
    end
    add_message "mt5_term_api.ZScoreData" do
      optional :z_score_decimal, :double, 1
      optional :z_score_probability, :double, 2
    end
    add_message "mt5_term_api.ExpectancyData" do
      optional :pips, :double, 1
      optional :dollar, :double, 2
    end
    add_message "mt5_term_api.StatsWithChartsData" do
      optional :stats, :message, 1, "mt5_term_api.StatsData"
      repeated :charts, :message, 2, "mt5_term_api.EquityPointData"
    end
    add_message "mt5_term_api.EquityHistoryData" do
      repeated :points, :message, 1, "mt5_term_api.EquityPointData"
    end
    add_message "mt5_term_api.EquityPointData" do
      optional :time, :message, 1, "google.protobuf.Timestamp"
      optional :balance, :double, 2
      optional :equity, :double, 3
      optional :balance_drawdown_raw, :double, 4
      optional :balance_drawdown_relative, :double, 5
      optional :equity_drawdown_raw, :double, 6
      optional :equity_drawdown_relative, :double, 7
      optional :realized_pl, :double, 8
      optional :unrealized_pl, :double, 9
    end
    add_message "mt5_term_api.TradeUnrealizedPLData" do
      repeated :extrema, :message, 1, "mt5_term_api.TradeUnrealizedExtremaData"
    end
    add_message "mt5_term_api.TradeUnrealizedExtremaData" do
      optional :ticket, :int64, 1
      optional :symbol, :string, 2
      optional :max_unrealized_time, :message, 3, "google.protobuf.Timestamp"
      optional :max_unrealized_pl, :double, 4
      optional :min_unrealized_time, :message, 5, "google.protobuf.Timestamp"
      optional :min_unrealized_pl, :double, 6
    end
  end
end

module Mt5TermApi
  TradeStatsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.TradeStatsRequest").msgclass
  TradeStatsReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.TradeStatsReply").msgclass
  TradeStatsEquityHistoryRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.TradeStatsEquityHistoryRequest").msgclass
  TradeStatsEquityHistoryReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.TradeStatsEquityHistoryReply").msgclass
  EquityHistoryRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.EquityHistoryRequest").msgclass
  EquityHistoryReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.EquityHistoryReply").msgclass
  TradeUnrealizedPLRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.TradeUnrealizedPLRequest").msgclass
  TradeUnrealizedPLReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.TradeUnrealizedPLReply").msgclass
  StatsData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.StatsData").msgclass
  TradeSummaryData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.TradeSummaryData").msgclass
  MarketTradeCountData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.MarketTradeCountData").msgclass
  ProfitabilityData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ProfitabilityData").msgclass
  AveragePipsUsdData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.AveragePipsUsdData").msgclass
  WonData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.WonData").msgclass
  ProfitData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ProfitData").msgclass
  ZScoreData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ZScoreData").msgclass
  ExpectancyData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ExpectancyData").msgclass
  StatsWithChartsData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.StatsWithChartsData").msgclass
  EquityHistoryData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.EquityHistoryData").msgclass
  EquityPointData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.EquityPointData").msgclass
  TradeUnrealizedPLData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.TradeUnrealizedPLData").msgclass
  TradeUnrealizedExtremaData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.TradeUnrealizedExtremaData").msgclass
end
