# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mt5-term-api-health-check.proto

require 'google/protobuf'

require 'mt5-term-api-connection_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("mt5-term-api-health-check.proto", :syntax => :proto3) do
    add_message "mt5_term_api.StopListeningRequest" do
    end
    add_message "mt5_term_api.StopListeningReply" do
    end
    add_message "mt5_term_api.HealthCheckRequest" do
    end
    add_message "mt5_term_api.HealthCheckReply" do
      optional :is_connected_to_server, :bool, 1
      optional :server_time_seconds, :int64, 2
    end
  end
end

module Mt5TermApi
  StopListeningRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.StopListeningRequest").msgclass
  StopListeningReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.StopListeningReply").msgclass
  HealthCheckRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.HealthCheckRequest").msgclass
  HealthCheckReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.HealthCheckReply").msgclass
end
