# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mt5-term-api-trading-helper.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'google/api/annotations_pb'
require 'mrpc-mt5-error_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("mt5-term-api-trading-helper.proto", :syntax => :proto3) do
    add_message "mt5_term_api.OrderCloseRequest" do
      optional :ticket, :uint64, 1
      optional :volume, :double, 2
      optional :slippage, :int32, 5
    end
    add_message "mt5_term_api.OrderCloseReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.OrderCloseData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.OrderCloseData" do
      optional :returned_code, :uint32, 1
      optional :returned_string_code, :string, 2
      optional :returned_code_description, :string, 3
      optional :close_mode, :enum, 4, "mt5_term_api.MRPC_ORDER_CLOSE_MODE"
    end
    add_message "mt5_term_api.OrderModifyRequest" do
      optional :ticket, :uint64, 1
      proto3_optional :stop_loss, :double, 2
      proto3_optional :take_profit, :double, 3
      proto3_optional :price, :double, 4
      proto3_optional :expiration_time_type, :enum, 5, "mt5_term_api.TMT5_ENUM_ORDER_TYPE_TIME"
      proto3_optional :expiration_time, :message, 6, "google.protobuf.Timestamp"
      proto3_optional :stop_limit, :double, 8
    end
    add_message "mt5_term_api.OrderModifyReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.OrderModifyData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.OrderModifyData" do
      optional :returned_code, :uint32, 1
      optional :deal, :uint64, 2
      optional :order, :uint64, 3
      optional :volume, :double, 4
      optional :price, :double, 5
      optional :bid, :double, 6
      optional :ask, :double, 7
      optional :comment, :string, 8
      optional :request_id, :uint32, 9
      optional :ret_code_external, :int32, 10
      optional :returned_string_code, :string, 11
      optional :returned_code_description, :string, 12
    end
    add_message "mt5_term_api.OrderSendRequest" do
      optional :symbol, :string, 1
      optional :operation, :enum, 2, "mt5_term_api.TMT5_ENUM_ORDER_TYPE"
      optional :volume, :double, 3
      proto3_optional :price, :double, 4
      proto3_optional :slippage, :uint64, 5
      proto3_optional :stop_loss, :double, 6
      proto3_optional :take_profit, :double, 7
      proto3_optional :comment, :string, 8
      proto3_optional :expert_id, :uint64, 9
      proto3_optional :stop_limit_price, :double, 10
      proto3_optional :expiration_time_type, :enum, 11, "mt5_term_api.TMT5_ENUM_ORDER_TYPE_TIME"
      proto3_optional :expiration_time, :message, 12, "google.protobuf.Timestamp"
      proto3_optional :quotes_wait_ms, :int32, 13
    end
    add_message "mt5_term_api.OrderSendReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.OrderSendData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.OrderSendData" do
      optional :returned_code, :uint32, 1
      optional :deal, :uint64, 2
      optional :order, :uint64, 3
      optional :volume, :double, 4
      optional :price, :double, 5
      optional :bid, :double, 6
      optional :ask, :double, 7
      optional :comment, :string, 8
      optional :request_id, :uint32, 9
      optional :ret_code_external, :int32, 10
      optional :returned_string_code, :string, 11
      optional :returned_code_description, :string, 12
    end
    add_enum "mt5_term_api.MRPC_ORDER_CLOSE_MODE" do
      value :MRPC_MARKET_ORDER_CLOSE, 0
      value :MRPC_MARKET_ORDER_PARTIAL_CLOSE, 1
      value :MRPC_PENDING_ORDER_REMOVE, 2
    end
    add_enum "mt5_term_api.TMT5_ENUM_ORDER_TYPE" do
      value :TMT5_ORDER_TYPE_BUY, 0
      value :TMT5_ORDER_TYPE_SELL, 1
      value :TMT5_ORDER_TYPE_BUY_LIMIT, 2
      value :TMT5_ORDER_TYPE_SELL_LIMIT, 3
      value :TMT5_ORDER_TYPE_BUY_STOP, 4
      value :TMT5_ORDER_TYPE_SELL_STOP, 5
      value :TMT5_ORDER_TYPE_BUY_STOP_LIMIT, 6
      value :TMT5_ORDER_TYPE_SELL_STOP_LIMIT, 7
      value :TMT5_ORDER_TYPE_CLOSE_BY, 8
    end
    add_enum "mt5_term_api.TMT5_ENUM_ORDER_TYPE_TIME" do
      value :TMT5_ORDER_TIME_GTC, 0
      value :TMT5_ORDER_TIME_DAY, 1
      value :TMT5_ORDER_TIME_SPECIFIED, 2
      value :TMT5_ORDER_TIME_SPECIFIED_DAY, 3
    end
  end
end

module Mt5TermApi
  OrderCloseRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OrderCloseRequest").msgclass
  OrderCloseReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OrderCloseReply").msgclass
  OrderCloseData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OrderCloseData").msgclass
  OrderModifyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OrderModifyRequest").msgclass
  OrderModifyReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OrderModifyReply").msgclass
  OrderModifyData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OrderModifyData").msgclass
  OrderSendRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OrderSendRequest").msgclass
  OrderSendReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OrderSendReply").msgclass
  OrderSendData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OrderSendData").msgclass
  MRPC_ORDER_CLOSE_MODE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.MRPC_ORDER_CLOSE_MODE").enummodule
  TMT5_ENUM_ORDER_TYPE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.TMT5_ENUM_ORDER_TYPE").enummodule
  TMT5_ENUM_ORDER_TYPE_TIME = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.TMT5_ENUM_ORDER_TYPE_TIME").enummodule
end
