# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mt5-term-api-charts.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'mrpc-mt5-error_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("mt5-term-api-charts.proto", :syntax => :proto3) do
    add_message "mt5_term_api.GetEaParamsRequest" do
      optional :ea_file_name, :string, 1
    end
    add_message "mt5_term_api.GetEaParamsReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.GetEaParamsData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.GetEaParamsData" do
      optional :ea_name, :string, 1
      optional :ea_found, :bool, 2
      optional :ea_has_params, :bool, 3
      repeated :parameters, :message, 4, "mt5_term_api.EaParam"
    end
    add_message "mt5_term_api.EaParam" do
      optional :name, :string, 1
      optional :type, :enum, 2, "mt5_term_api.EA_PARAM_TYPE"
    end
    add_message "mt5_term_api.OpenTerminalChartWithEaRequest" do
      optional :symbol_name, :string, 1
      optional :ea_file_name, :string, 2
      optional :chart_period, :enum, 3, "mt5_term_api.EnumOpenTerminalChartWithEaChatPeriod"
      repeated :ea_parameters, :message, 4, "mt5_term_api.OpenTerminalChartWithEaParameter"
    end
    add_message "mt5_term_api.OpenTerminalChartWithEaParameter" do
      optional :index, :int32, 1
      optional :type, :enum, 2, "mt5_term_api.EnumOpenTerminalChartWithEaParameterType"
      proto3_optional :int_param_value, :int32, 3
      proto3_optional :long_param_value, :int64, 4
      proto3_optional :bool_param_value, :bool, 5
      proto3_optional :string_param_value, :string, 6
      proto3_optional :double_param_value, :double, 7
    end
    add_message "mt5_term_api.OpenTerminalChartWithEaReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.OpenTerminalChartWithEaData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.OpenTerminalChartWithEaData" do
      optional :chart_id, :int64, 1
    end
    add_enum "mt5_term_api.EA_PARAM_TYPE" do
      value :EA_PARAM_TYPE_UNDEFINED, 0
      value :EA_PARAM_TYPE_STRING, 1
      value :EA_PARAM_TYPE_INTEGER, 2
      value :EA_PARAM_TYPE_DOUBLE, 3
      value :EA_PARAM_TYPE_BOOLEAN, 4
    end
    add_enum "mt5_term_api.EnumOpenTerminalChartWithEaParameterType" do
      value :MRPC_EA_PARAM_INT, 0
      value :MRPC_EA_PARAM_LONG, 1
      value :MRPC_EA_PARAM_BOOL, 2
      value :MRPC_EA_PARAM_STRING, 3
      value :MRPC_EA_PARAM_DOUBLE, 4
    end
    add_enum "mt5_term_api.EnumOpenTerminalChartWithEaChatPeriod" do
      value :MRPC_EA_CHART_PERIOD_CURRENT, 0
      value :MRPC_EA_CHART_PERIOD_M1, 1
      value :MRPC_EA_CHART_PERIOD_M2, 2
      value :MRPC_EA_CHART_PERIOD_M3, 3
      value :MRPC_EA_CHART_PERIOD_M4, 4
      value :MRPC_EA_CHART_PERIOD_M5, 5
      value :MRPC_EA_CHART_PERIOD_M6, 6
      value :MRPC_EA_CHART_PERIOD_M10, 7
      value :MRPC_EA_CHART_PERIOD_M12, 8
      value :MRPC_EA_CHART_PERIOD_M15, 9
      value :MRPC_EA_CHART_PERIOD_M20, 10
      value :MRPC_EA_CHART_PERIOD_M30, 11
      value :MRPC_EA_CHART_PERIOD_H1, 12
      value :MRPC_EA_CHART_PERIOD_H2, 13
      value :MRPC_EA_CHART_PERIOD_H3, 14
      value :MRPC_EA_CHART_PERIOD_H4, 15
      value :MRPC_EA_CHART_PERIOD_H6, 16
      value :MRPC_EA_CHART_PERIOD_H8, 17
      value :MRPC_EA_CHART_PERIOD_H12, 18
      value :MRPC_EA_CHART_PERIOD_D1, 19
      value :MRPC_EA_CHART_PERIOD_W1, 20
      value :MRPC_EA_CHART_PERIOD_MN1, 21
    end
  end
end

module Mt5TermApi
  GetEaParamsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.GetEaParamsRequest").msgclass
  GetEaParamsReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.GetEaParamsReply").msgclass
  GetEaParamsData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.GetEaParamsData").msgclass
  EaParam = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.EaParam").msgclass
  OpenTerminalChartWithEaRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OpenTerminalChartWithEaRequest").msgclass
  OpenTerminalChartWithEaParameter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OpenTerminalChartWithEaParameter").msgclass
  OpenTerminalChartWithEaReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OpenTerminalChartWithEaReply").msgclass
  OpenTerminalChartWithEaData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OpenTerminalChartWithEaData").msgclass
  EA_PARAM_TYPE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.EA_PARAM_TYPE").enummodule
  EnumOpenTerminalChartWithEaParameterType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.EnumOpenTerminalChartWithEaParameterType").enummodule
  EnumOpenTerminalChartWithEaChatPeriod = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.EnumOpenTerminalChartWithEaChatPeriod").enummodule
end
