# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mt5-term-api-internal-charts.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("mt5-term-api-internal-charts.proto", :syntax => :proto3) do
    add_message "mt5_term_api.SaveChartTemplateRequest" do
      optional :chart_id, :int64, 1
    end
    add_message "mt5_term_api.SaveChartTemplateReply" do
      optional :file_name, :string, 1
    end
    add_message "mt5_term_api.OpenChartWithEaRequest" do
      optional :symbol_name, :string, 1
      optional :ea_file_name, :string, 2
      optional :chart_period, :enum, 3, "mt5_term_api.EnumOpenChartWithEaChatPeriod"
      repeated :ea_parameters, :message, 4, "mt5_term_api.OpenChartWithEaParameter"
    end
    add_message "mt5_term_api.OpenChartWithEaParameter" do
      optional :index, :int32, 1
      optional :type, :enum, 2, "mt5_term_api.EnumOpenChartWithEaParemeterType"
      proto3_optional :int_param_value, :int32, 3
      proto3_optional :long_param_value, :int64, 4
      proto3_optional :bool_param_value, :bool, 5
      proto3_optional :string_param_value, :string, 6
      proto3_optional :double_param_value, :double, 7
    end
    add_message "mt5_term_api.OpenChartWithEaReply" do
      optional :chart_id, :int64, 1
    end
    add_message "mt5_term_api.OpenChartForSymbolRequest" do
      optional :symbol_name, :string, 1
      optional :expert_mode, :enum, 2, "mt5_term_api.ChartExpertMode"
      proto3_optional :timer_period, :int32, 3
      proto3_optional :ignore_empty_data, :bool, 4
    end
    add_message "mt5_term_api.OpenChartForSymbolReply" do
      optional :mql_chart_id, :int64, 1
    end
    add_message "mt5_term_api.CloseChartForSymbolRequest" do
      optional :mql_chart_id, :int64, 1
    end
    add_message "mt5_term_api.CloseChartForSymbolReply" do
    end
    add_enum "mt5_term_api.EnumOpenChartWithEaParemeterType" do
      value :EA_PARAM_INT, 0
      value :EA_PARAM_LONG, 1
      value :EA_PARAM_BOOL, 2
      value :EA_PARAM_STRING, 3
      value :EA_PARAM_DOUBLE, 4
    end
    add_enum "mt5_term_api.EnumOpenChartWithEaChatPeriod" do
      value :EA_CHART_PERIOD_CURRENT, 0
      value :EA_CHART_PERIOD_M1, 1
      value :EA_CHART_PERIOD_M2, 2
      value :EA_CHART_PERIOD_M3, 3
      value :EA_CHART_PERIOD_M4, 4
      value :EA_CHART_PERIOD_M5, 5
      value :EA_CHART_PERIOD_M6, 6
      value :EA_CHART_PERIOD_M10, 7
      value :EA_CHART_PERIOD_M12, 8
      value :EA_CHART_PERIOD_M15, 9
      value :EA_CHART_PERIOD_M20, 10
      value :EA_CHART_PERIOD_M30, 11
      value :EA_CHART_PERIOD_H1, 12
      value :EA_CHART_PERIOD_H2, 13
      value :EA_CHART_PERIOD_H3, 14
      value :EA_CHART_PERIOD_H4, 15
      value :EA_CHART_PERIOD_H6, 16
      value :EA_CHART_PERIOD_H8, 17
      value :EA_CHART_PERIOD_H12, 18
      value :EA_CHART_PERIOD_D1, 19
      value :EA_CHART_PERIOD_W1, 20
      value :EA_CHART_PERIOD_MN1, 21
    end
    add_enum "mt5_term_api.ChartExpertMode" do
      value :ON_TICK, 0
      value :ON_TRADE, 1
      value :ON_ORDER_PROFIT, 2
      value :ON_OPENED_ORDERS_TICKETS, 3
      value :ON_TRADE_TRANSACTION, 4
    end
  end
end

module Mt5TermApi
  SaveChartTemplateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SaveChartTemplateRequest").msgclass
  SaveChartTemplateReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.SaveChartTemplateReply").msgclass
  OpenChartWithEaRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OpenChartWithEaRequest").msgclass
  OpenChartWithEaParameter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OpenChartWithEaParameter").msgclass
  OpenChartWithEaReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OpenChartWithEaReply").msgclass
  OpenChartForSymbolRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OpenChartForSymbolRequest").msgclass
  OpenChartForSymbolReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OpenChartForSymbolReply").msgclass
  CloseChartForSymbolRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.CloseChartForSymbolRequest").msgclass
  CloseChartForSymbolReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.CloseChartForSymbolReply").msgclass
  EnumOpenChartWithEaParemeterType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.EnumOpenChartWithEaParemeterType").enummodule
  EnumOpenChartWithEaChatPeriod = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.EnumOpenChartWithEaChatPeriod").enummodule
  ChartExpertMode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.ChartExpertMode").enummodule
end
