# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mt5-term-api-internal-charts.proto for package 'mt5_term_api'

require 'grpc'
require 'mt5-term-api-internal-charts_pb'

module Mt5TermApi
  module InternalCharts
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mt5_term_api.InternalCharts'

      rpc :OpenChartForSymbol, ::Mt5TermApi::OpenChartForSymbolRequest, ::Mt5TermApi::OpenChartForSymbolReply
      rpc :CloseChartForSymbol, ::Mt5TermApi::CloseChartForSymbolRequest, ::Mt5TermApi::CloseChartForSymbolReply
      rpc :OpenChartWithEa, ::Mt5TermApi::OpenChartWithEaRequest, ::Mt5TermApi::OpenChartWithEaReply
      rpc :SaveChartTemplate, ::Mt5TermApi::SaveChartTemplateRequest, ::Mt5TermApi::SaveChartTemplateReply
    end

    Stub = Service.rpc_stub_class
  end
end
