# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mt5-term-api-charts.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'google/protobuf/timestamp_pb'
require 'mrpc-mt5-error_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("mt5-term-api-charts.proto", :syntax => :proto3) do
    add_message "mt5_term_api.GetEaParamsRequest" do
      optional :ea_file_name, :string, 1
    end
    add_message "mt5_term_api.GetEaParamsReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.GetEaParamsData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.GetEaParamsData" do
      optional :ea_name, :string, 1
      optional :ea_found, :bool, 2
      optional :ea_has_params, :bool, 3
      repeated :parameters, :message, 4, "mt5_term_api.EaParam"
    end
    add_message "mt5_term_api.EaParam" do
      optional :name, :string, 1
      optional :type, :enum, 2, "mt5_term_api.EA_PARAM_TYPE"
    end
    add_message "mt5_term_api.OpenTerminalChartWithEaRequest" do
      optional :symbol_name, :string, 1
      optional :ea_file_name, :string, 2
      optional :chart_period, :enum, 3, "mt5_term_api.EnumOpenTerminalChartWithEaChatPeriod"
      repeated :ea_parameters, :message, 4, "mt5_term_api.OpenTerminalChartWithEaParameter"
    end
    add_message "mt5_term_api.OpenTerminalChartWithEaParameter" do
      optional :index, :int32, 1
      optional :type, :enum, 2, "mt5_term_api.EnumOpenTerminalChartWithEaParameterType"
      proto3_optional :int_param_value, :int32, 3
      proto3_optional :long_param_value, :int64, 4
      proto3_optional :bool_param_value, :bool, 5
      proto3_optional :string_param_value, :string, 6
      proto3_optional :double_param_value, :double, 7
    end
    add_message "mt5_term_api.OpenTerminalChartWithEaReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.OpenTerminalChartWithEaData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.OpenTerminalChartWithEaData" do
      optional :chart_id, :int64, 1
    end
    add_message "mt5_term_api.AttachEaRequest" do
      optional :session_id, :string, 1
      optional :ea_file_name, :string, 2
      optional :symbol_name, :string, 3
      optional :chart_period, :enum, 4, "mt5_term_api.EnumOpenTerminalChartWithEaChatPeriod"
      repeated :ea_parameters, :message, 5, "mt5_term_api.OpenTerminalChartWithEaParameter"
      proto3_optional :ea_file_content, :bytes, 6
      proto3_optional :max_cpu_percent, :double, 7
      proto3_optional :max_ram_bytes, :int64, 8
    end
    add_message "mt5_term_api.AttachEaReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.AttachEaData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.AttachEaData" do
      optional :ea_id, :string, 1
      optional :ea_terminal_id, :string, 2
      optional :parent_session_id, :string, 3
      optional :ea_name, :string, 4
      optional :state, :string, 5
      optional :process_id, :int32, 6
    end
    add_message "mt5_term_api.GetRunningEasRequest" do
      proto3_optional :session_id, :string, 1
      proto3_optional :ea_id, :string, 2
    end
    add_message "mt5_term_api.GetRunningEasReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.GetRunningEasData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.GetRunningEasData" do
      repeated :eas, :message, 1, "mt5_term_api.RunningEaInfo"
    end
    add_message "mt5_term_api.RunningEaInfo" do
      optional :ea_id, :string, 1
      optional :ea_name, :string, 2
      optional :parent_session_id, :string, 3
      optional :ea_terminal_id, :string, 4
      optional :process_id, :int32, 5
      optional :symbol, :string, 6
      optional :period, :string, 7
      optional :state, :string, 8
      optional :started_at, :message, 9, "google.protobuf.Timestamp"
      optional :ea_cpu_percent, :double, 10
      optional :ref_cpu_percent, :double, 11
      optional :cpu_ratio, :double, 12
      optional :ea_ram_bytes, :int64, 13
      optional :ref_ram_bytes, :int64, 14
      optional :ram_ratio, :double, 15
      optional :resource_multiplier, :double, 16
    end
    add_message "mt5_term_api.GetEaLogsRequest" do
      optional :ea_id, :string, 1
      proto3_optional :log_type, :string, 2
    end
    add_message "mt5_term_api.GetEaLogsReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.GetEaLogsData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.GetEaLogsData" do
      repeated :rows, :message, 1, "mt5_term_api.EaLogRow"
    end
    add_message "mt5_term_api.EaLogRow" do
      optional :time, :message, 1, "google.protobuf.Timestamp"
      optional :source, :string, 2
      optional :message, :string, 3
    end
    add_message "mt5_term_api.StopEaRequest" do
      optional :ea_id, :string, 1
      proto3_optional :reason, :string, 2
    end
    add_message "mt5_term_api.StopEaReply" do
      oneof :response do
        optional :data, :message, 1, "mt5_term_api.StopEaData"
        optional :error, :message, 2, "mt5_term_api.Error"
      end
    end
    add_message "mt5_term_api.StopEaData" do
      optional :success, :bool, 1
      optional :ea_id, :string, 2
      optional :message, :string, 3
    end
    add_enum "mt5_term_api.EA_PARAM_TYPE" do
      value :EA_PARAM_TYPE_UNDEFINED, 0
      value :EA_PARAM_TYPE_STRING, 1
      value :EA_PARAM_TYPE_INTEGER, 2
      value :EA_PARAM_TYPE_DOUBLE, 3
      value :EA_PARAM_TYPE_BOOLEAN, 4
    end
    add_enum "mt5_term_api.EnumOpenTerminalChartWithEaParameterType" do
      value :MRPC_EA_PARAM_INT, 0
      value :MRPC_EA_PARAM_LONG, 1
      value :MRPC_EA_PARAM_BOOL, 2
      value :MRPC_EA_PARAM_STRING, 3
      value :MRPC_EA_PARAM_DOUBLE, 4
    end
    add_enum "mt5_term_api.EnumOpenTerminalChartWithEaChatPeriod" do
      value :MRPC_EA_CHART_PERIOD_CURRENT, 0
      value :MRPC_EA_CHART_PERIOD_M1, 1
      value :MRPC_EA_CHART_PERIOD_M2, 2
      value :MRPC_EA_CHART_PERIOD_M3, 3
      value :MRPC_EA_CHART_PERIOD_M4, 4
      value :MRPC_EA_CHART_PERIOD_M5, 5
      value :MRPC_EA_CHART_PERIOD_M6, 6
      value :MRPC_EA_CHART_PERIOD_M10, 7
      value :MRPC_EA_CHART_PERIOD_M12, 8
      value :MRPC_EA_CHART_PERIOD_M15, 9
      value :MRPC_EA_CHART_PERIOD_M20, 10
      value :MRPC_EA_CHART_PERIOD_M30, 11
      value :MRPC_EA_CHART_PERIOD_H1, 12
      value :MRPC_EA_CHART_PERIOD_H2, 13
      value :MRPC_EA_CHART_PERIOD_H3, 14
      value :MRPC_EA_CHART_PERIOD_H4, 15
      value :MRPC_EA_CHART_PERIOD_H6, 16
      value :MRPC_EA_CHART_PERIOD_H8, 17
      value :MRPC_EA_CHART_PERIOD_H12, 18
      value :MRPC_EA_CHART_PERIOD_D1, 19
      value :MRPC_EA_CHART_PERIOD_W1, 20
      value :MRPC_EA_CHART_PERIOD_MN1, 21
    end
  end
end

module Mt5TermApi
  GetEaParamsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.GetEaParamsRequest").msgclass
  GetEaParamsReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.GetEaParamsReply").msgclass
  GetEaParamsData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.GetEaParamsData").msgclass
  EaParam = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.EaParam").msgclass
  OpenTerminalChartWithEaRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OpenTerminalChartWithEaRequest").msgclass
  OpenTerminalChartWithEaParameter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OpenTerminalChartWithEaParameter").msgclass
  OpenTerminalChartWithEaReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OpenTerminalChartWithEaReply").msgclass
  OpenTerminalChartWithEaData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.OpenTerminalChartWithEaData").msgclass
  AttachEaRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.AttachEaRequest").msgclass
  AttachEaReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.AttachEaReply").msgclass
  AttachEaData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.AttachEaData").msgclass
  GetRunningEasRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.GetRunningEasRequest").msgclass
  GetRunningEasReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.GetRunningEasReply").msgclass
  GetRunningEasData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.GetRunningEasData").msgclass
  RunningEaInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.RunningEaInfo").msgclass
  GetEaLogsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.GetEaLogsRequest").msgclass
  GetEaLogsReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.GetEaLogsReply").msgclass
  GetEaLogsData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.GetEaLogsData").msgclass
  EaLogRow = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.EaLogRow").msgclass
  StopEaRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.StopEaRequest").msgclass
  StopEaReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.StopEaReply").msgclass
  StopEaData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.StopEaData").msgclass
  EA_PARAM_TYPE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.EA_PARAM_TYPE").enummodule
  EnumOpenTerminalChartWithEaParameterType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.EnumOpenTerminalChartWithEaParameterType").enummodule
  EnumOpenTerminalChartWithEaChatPeriod = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt5_term_api.EnumOpenTerminalChartWithEaChatPeriod").enummodule
end
