# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mt5-term-api-connection.proto for package 'mt5_term_api'

require 'grpc'
require 'mt5-term-api-connection_pb'

module Mt5TermApi
  module Connection
    # -------------------------------------!!!! MT5 CONNECTION SERVICE START !!!!!!!---------------------------------------
    #
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mt5_term_api.Connection'

      # Creates terminal connection to the MT5 server by MT cluster name, waits for connection and returns Guid of it 
      # [DefaultValues]
      # {
      #   "user": "213889529",
      #   "password": "7dPjA*Jm",
      #   "mtClusterName": "OctaFX-Demo",
      #   "timeoutSeconds": "120"
      # }  
      rpc :ConnectEx, ::Mt5TermApi::ConnectExRequest, ::Mt5TermApi::ConnectExReply
      # Creates terminal connection to the MT5 server and returns Guid of it 
      # [DefaultValues]
      # {
      #   "user": "213889529",
      #   "password": "7dPjA*Jm",
      #   "host": "d51a1.octanetwork.net",
      #   "port": "443",
      #   "timeoutSeconds": "120"
      # }  
      rpc :Connect, ::Mt5TermApi::ConnectRequest, ::Mt5TermApi::ConnectReply
      # Connect to account with user, password, host, port.
      # [DefaultValues] 
      # { 
      #  "user": "213889529", 
      #  "password": "7dPjA*Jm", 
      #  "host": "d51a1.octanetwork.net", 
      #  "port": "443", 
      #  "proxyUser": "ProxyUser123", 
      #  "proxyPassword": "qwerty123", 
      #  "proxyHost": "65.108.126.217", 
      #  "proxyPort": "1080", 
      #  "proxyType": "Socks5" 
      # }
      rpc :ConnectProxy, ::Mt5TermApi::ConnectProxyRequest, ::Mt5TermApi::ConnectProxyReply
      # Checks if terminal connection to MT5 server is alive
      rpc :CheckConnect, ::Mt5TermApi::CheckConnectRequest, ::Mt5TermApi::CheckConnectReply
      # Returns detailed live connection state of this terminal instance
      rpc :ConnectState, ::Mt5TermApi::ConnectStateRequest, ::Mt5TermApi::ConnectStateReply
      # Streams real-time connection state changes for specified or visible terminals
      rpc :OnConnectState, ::Mt5TermApi::OnConnectStateRequest, stream(::Mt5TermApi::OnConnectStateReply)
      # Deprecated alias for ConnectState
      rpc :ConnectionStatus, ::Mt5TermApi::ConnectionStatusRequest, ::Mt5TermApi::ConnectionStatusReply
      # Close terminal connection to MT5 server
      rpc :Disconnect, ::Mt5TermApi::DisconnectRequest, ::Mt5TermApi::DisconnectReply
      # If you need to recreate terminal instance with the same id
      rpc :Reconnect, ::Mt5TermApi::ReconnectRequest, ::Mt5TermApi::ReconnectReply
      # Rebuild a terminal instance from a previously-saved token_details_mt5 row. The id header
      # names the terminal to bring back; every credential (User/Password/Server or Host+Port,
      # proxy settings, servers.dat bytes, PfxFile, HardwareId, Build) is read from the DB. Same
      # reply as ConnectEx so callers do not need a separate result path.
      rpc :ConnectByToken, ::Mt5TermApi::ConnectByTokenRequest, ::Mt5TermApi::ConnectExReply
      rpc :GetBrokerServersByBrokerName, ::Mt5TermApi::GetBrokerServersByBrokerNameRequest, ::Mt5TermApi::GetBrokerServersByBrokerNameReply
      # Captures the Xvfb display screenshot for the terminal instance
      rpc :Screenshot, ::Mt5TermApi::ScreenshotRequest, ::Mt5TermApi::ScreenshotReply
      # Generates a deterministic GUID from user and password.
      # The same user/password combination always produces the same GUID.
      # Use this GUID as the 'id' header for Connect and other endpoints.
      # [DefaultValues]
      # {
      #   "user": "213889529",
      #   "password": "7dPjA*Jm"
      # }
      rpc :GetId, ::Mt5TermApi::GetIdRequest, ::Mt5TermApi::GetIdReply
      # Same as Connect but streams real-time progress events.
      # Requires 'id' header — use GetId to generate.
      # Swagger does not support streaming — use /connect-stream interactive viewer.
      # [DefaultValues]
      # {
      #   "user": "213889529",
      #   "password": "7dPjA*Jm",
      #   "host": "d51a1.octanetwork.net",
      #   "port": "443",
      #   "timeoutSeconds": "120"
      # }
      rpc :ConnectStream, ::Mt5TermApi::ConnectRequest, stream(::Mt5TermApi::ConnectStreamEvent)
      # Same as ConnectEx but streams real-time progress events.
      # Requires 'id' header — use GetId to generate.
      # Swagger does not support streaming — use /connect-stream interactive viewer.
      # [DefaultValues]
      # {
      #   "user": "213889529",
      #   "password": "7dPjA*Jm",
      #   "mtClusterName": "OctaFX-Demo",
      #   "timeoutSeconds": "120"
      # }
      rpc :ConnectExStream, ::Mt5TermApi::ConnectExRequest, stream(::Mt5TermApi::ConnectStreamEvent)
    end

    Stub = Service.rpc_stub_class
  end
  module Logs
    # Provides access to terminal log content (Journal and Experts tabs).
    # Reads log entries directly from the MT5 terminal GUI.
    # Requires 'id' header with the terminal connection GUID returned by Connect.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mt5_term_api.Logs'

      # Returns log entries from the terminal Journal tab.
      # The Journal tab contains system messages about terminal connection status, 
      # network activity, server synchronization and other internal events.
      # Works regardless of which tab is currently active in the terminal UI.
      rpc :Journal, ::Mt5TermApi::JournalRequest, ::Mt5TermApi::JournalReply
      # Streams log entries from the terminal Journal tab in real-time.
      # Requires 'id' header with the terminal connection GUID returned by Connect.
      rpc :OnJournal, ::Mt5TermApi::OnJournalRequest, stream(::Mt5TermApi::OnJournalReply)
      # Returns log entries from the terminal Experts tab.
      # The Experts tab contains messages from Expert Advisors (EAs), scripts and indicators
      # including Print() output, initialization/deinitialization events and runtime errors.
      # Works regardless of which tab is currently active in the terminal UI.
      rpc :Experts, ::Mt5TermApi::JournalRequest, ::Mt5TermApi::JournalReply
      # Streams log entries from the terminal Experts tab in real-time.
      # Requires 'id' header with the terminal connection GUID returned by Connect.
      rpc :OnExperts, ::Mt5TermApi::OnJournalRequest, stream(::Mt5TermApi::OnJournalReply)
    end

    Stub = Service.rpc_stub_class
  end
end
