# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mt5-term-api-admin.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("mt5-term-api-admin.proto", :syntax => :proto3) do
    add_message "mrpc_admin.SessionRestoreWatcherStatus" do
      optional :enabled, :bool, 1
      optional :state, :string, 2
      optional :reason, :string, 3
      optional :total_candidates, :int32, 4
      optional :distinct_tokens, :int32, 5
      optional :already_loaded, :int32, 6
      optional :in_queue, :int32, 7
      optional :in_progress, :int32, 8
      optional :restored_success, :int32, 9
      optional :restored_failed, :int32, 10
      optional :last_reconcile_start_utc, :string, 11
      optional :last_reconcile_end_utc, :string, 12
      optional :last_reconcile_duration_ms, :double, 13
      optional :last_error, :string, 14
    end
    add_message "mrpc_admin.GetSessionRestoreStatusReply" do
      optional :status, :message, 1, "mrpc_admin.SessionRestoreWatcherStatus"
      optional :error, :string, 2
    end
    add_message "mrpc_admin.GetSessionRestoreLogsRequest" do
      optional :admin_key, :string, 1
      optional :pod, :string, 2
      optional :latest_only, :bool, 3
    end
    add_message "mrpc_admin.SessionRestoreLogEntry" do
      optional :token_id, :string, 1
      optional :platform, :string, 2
      optional :reason, :string, 3
      optional :owner, :string, 4
      optional :user, :string, 5
      optional :target, :string, 6
      optional :success, :bool, 7
      optional :error, :string, 8
      optional :elapsed_ms, :double, 9
      optional :created_utc, :string, 10
    end
    add_message "mrpc_admin.GetSessionRestoreLogsReply" do
      repeated :entries, :message, 1, "mrpc_admin.SessionRestoreLogEntry"
      optional :error, :string, 2
    end
    add_message "mrpc_admin.GetAllLogsRequest" do
      optional :admin_key, :string, 1
      optional :max_bytes_per_log, :int64, 2
      optional :exclude_event_logs, :bool, 3
    end
    add_message "mrpc_admin.AllLogsEntry" do
      optional :source, :string, 1
      optional :name, :string, 2
      optional :path, :string, 3
      optional :size_bytes, :int64, 4
      optional :modified_at, :string, 5
      optional :content, :string, 6
      optional :truncated, :bool, 7
      optional :error, :string, 8
    end
    add_message "mrpc_admin.GetAllLogsReply" do
      repeated :logs, :message, 1, "mrpc_admin.AllLogsEntry"
      optional :error, :string, 2
    end
    add_message "mrpc_admin.VersionRequest" do
    end
    add_message "mrpc_admin.VersionReply" do
      optional :service, :string, 1
      optional :version, :string, 2
      optional :build_time_utc, :string, 3
      optional :mode, :string, 4
    end
    add_message "mrpc_admin.ListLogFilesReply" do
      repeated :files, :message, 1, "mrpc_admin.LogFileEntry"
      optional :error, :string, 2
    end
    add_message "mrpc_admin.LogFileEntry" do
      optional :name, :string, 1
      optional :size_bytes, :int64, 2
      optional :modified_at, :message, 3, "google.protobuf.Timestamp"
    end
    add_message "mrpc_admin.GetLogFileRequest" do
      optional :admin_key, :string, 1
      optional :file_name, :string, 2
      optional :max_bytes, :int64, 3
    end
    add_message "mrpc_admin.GetLogFileReply" do
      optional :content, :string, 1
      optional :truncated, :bool, 2
      optional :total_size_bytes, :int64, 3
      optional :error, :string, 4
    end
    add_message "mrpc_admin.GetTerminalJournalRequest" do
      optional :admin_key, :string, 1
      optional :id, :string, 2
      optional :max_bytes, :int64, 3
    end
    add_message "mrpc_admin.TerminalJournalFile" do
      optional :name, :string, 1
      optional :content, :string, 2
      optional :truncated, :bool, 3
      optional :total_size_bytes, :int64, 4
    end
    add_message "mrpc_admin.GetTerminalJournalReply" do
      optional :terminal_dir, :string, 1
      repeated :files, :message, 2, "mrpc_admin.TerminalJournalFile"
      optional :error, :string, 3
    end
    add_message "mrpc_admin.GetEventLogEntriesRequest" do
      optional :admin_key, :string, 1
      optional :log_name, :string, 2
      optional :max_count, :int32, 3
    end
    add_message "mrpc_admin.GetEventLogEntriesReply" do
      repeated :entries, :string, 1
      optional :error, :string, 2
    end
    add_message "mrpc_admin.CaptureSessionScreenshotRequest" do
      optional :admin_key, :string, 1
      optional :session_user_name, :string, 2
    end
    add_message "mrpc_admin.CaptureSessionScreenshotOnPodRequest" do
      optional :admin_key, :string, 1
      optional :pod_ip, :string, 2
      optional :session_user_name, :string, 3
    end
    add_message "mrpc_admin.CaptureSessionScreenshotReply" do
      optional :image_png, :bytes, 1
      optional :error, :string, 2
    end
    add_message "mrpc_admin.RefreshMrpcRestReply" do
      optional :success, :bool, 1
      optional :message, :string, 2
      optional :error, :string, 3
    end
    add_message "mrpc_admin.UsageSample" do
      optional :time, :message, 1, "google.protobuf.Timestamp"
      optional :cpu_percent, :double, 2
      optional :ram_used_mb, :uint64, 3
      optional :ram_total_mb, :uint64, 4
    end
    add_message "mrpc_admin.SystemUsageReply" do
      optional :cpu_percent, :double, 1
      optional :ram_used_mb, :uint64, 2
      optional :ram_total_mb, :uint64, 3
      repeated :history, :message, 4, "mrpc_admin.UsageSample"
      optional :error, :string, 5
    end
    add_message "mrpc_admin.ActiveTerminalsRequest" do
      optional :admin_key, :string, 1
    end
    add_message "mrpc_admin.TerminalInfo" do
      optional :id, :string, 1
      optional :user_number, :uint32, 2
      optional :windows_user, :string, 3
      optional :account, :uint64, 4
      optional :server, :string, 5
      optional :port, :uint32, 6
      optional :created_at, :message, 7, "google.protobuf.Timestamp"
      optional :windows_password, :string, 8
      proto3_optional :name, :string, 9
      optional :state, :string, 10
      optional :error_message, :string, 11
      proto3_optional :user_email, :string, 12
      proto3_optional :startup_duration_seconds, :double, 13
      proto3_optional :connected_at, :message, 14, "google.protobuf.Timestamp"
      proto3_optional :startup_time, :string, 15
    end
    add_message "mrpc_admin.ActiveTerminalsReply" do
      optional :pod, :string, 1
      optional :node, :string, 2
      optional :pod_ip, :string, 3
      repeated :terminals, :message, 4, "mrpc_admin.TerminalInfo"
      optional :error, :string, 5
      optional :cpu_percent, :double, 6
      optional :ram_used_mb, :uint64, 7
      optional :ram_total_mb, :uint64, 8
      repeated :usage_history, :message, 9, "mrpc_admin.UsageSample"
      optional :restore_status, :message, 10, "mrpc_admin.SessionRestoreWatcherStatus"
    end
    add_message "mrpc_admin.PodTerminals" do
      optional :pod, :string, 1
      optional :node, :string, 2
      optional :pod_ip, :string, 3
      optional :novnc_url, :string, 4
      repeated :terminals, :message, 5, "mrpc_admin.TerminalInfo"
      optional :error, :string, 6
      optional :host_ip, :string, 7
      optional :cpu_percent, :double, 8
      optional :ram_used_mb, :uint64, 9
      optional :ram_total_mb, :uint64, 10
      repeated :usage_history, :message, 11, "mrpc_admin.UsageSample"
      optional :restore_status, :message, 12, "mrpc_admin.SessionRestoreWatcherStatus"
    end
    add_message "mrpc_admin.ActiveTerminalsClusterReply" do
      repeated :pods, :message, 1, "mrpc_admin.PodTerminals"
    end
  end
end

module MrpcAdmin
  SessionRestoreWatcherStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mrpc_admin.SessionRestoreWatcherStatus").msgclass
  GetSessionRestoreStatusReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mrpc_admin.GetSessionRestoreStatusReply").msgclass
  GetSessionRestoreLogsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mrpc_admin.GetSessionRestoreLogsRequest").msgclass
  SessionRestoreLogEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mrpc_admin.SessionRestoreLogEntry").msgclass
  GetSessionRestoreLogsReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mrpc_admin.GetSessionRestoreLogsReply").msgclass
  GetAllLogsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mrpc_admin.GetAllLogsRequest").msgclass
  AllLogsEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mrpc_admin.AllLogsEntry").msgclass
  GetAllLogsReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mrpc_admin.GetAllLogsReply").msgclass
  VersionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mrpc_admin.VersionRequest").msgclass
  VersionReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mrpc_admin.VersionReply").msgclass
  ListLogFilesReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mrpc_admin.ListLogFilesReply").msgclass
  LogFileEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mrpc_admin.LogFileEntry").msgclass
  GetLogFileRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mrpc_admin.GetLogFileRequest").msgclass
  GetLogFileReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mrpc_admin.GetLogFileReply").msgclass
  GetTerminalJournalRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mrpc_admin.GetTerminalJournalRequest").msgclass
  TerminalJournalFile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mrpc_admin.TerminalJournalFile").msgclass
  GetTerminalJournalReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mrpc_admin.GetTerminalJournalReply").msgclass
  GetEventLogEntriesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mrpc_admin.GetEventLogEntriesRequest").msgclass
  GetEventLogEntriesReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mrpc_admin.GetEventLogEntriesReply").msgclass
  CaptureSessionScreenshotRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mrpc_admin.CaptureSessionScreenshotRequest").msgclass
  CaptureSessionScreenshotOnPodRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mrpc_admin.CaptureSessionScreenshotOnPodRequest").msgclass
  CaptureSessionScreenshotReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mrpc_admin.CaptureSessionScreenshotReply").msgclass
  RefreshMrpcRestReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mrpc_admin.RefreshMrpcRestReply").msgclass
  UsageSample = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mrpc_admin.UsageSample").msgclass
  SystemUsageReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mrpc_admin.SystemUsageReply").msgclass
  ActiveTerminalsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mrpc_admin.ActiveTerminalsRequest").msgclass
  TerminalInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mrpc_admin.TerminalInfo").msgclass
  ActiveTerminalsReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mrpc_admin.ActiveTerminalsReply").msgclass
  PodTerminals = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mrpc_admin.PodTerminals").msgclass
  ActiveTerminalsClusterReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mrpc_admin.ActiveTerminalsClusterReply").msgclass
end
