# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mt5-term-api-health-check.proto for package 'mt5_term_api'

require 'grpc'
require 'mt5-term-api-health-check_pb'

module Mt5TermApi
  module Health
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mt5_term_api.Health'

      rpc :Check, ::Mt5TermApi::HealthCheckRequest, ::Mt5TermApi::HealthCheckReply
      rpc :StopListening, ::Mt5TermApi::StopListeningRequest, ::Mt5TermApi::StopListeningReply
    end

    Stub = Service.rpc_stub_class
  end
end
