# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mt5-term-api-account-information.proto for package 'mt5_term_api'

require 'grpc'
require 'mt5-term-api-account-information_pb'

module Mt5TermApi
  module AccountInformation
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mt5_term_api.AccountInformation'

      # Returns the double value of the corresponding account property
      # https://www.mql5.com/en/docs/account/accountinfodouble
      rpc :AccountInfoDouble, ::Mt5TermApi::AccountInfoDoubleRequest, ::Mt5TermApi::AccountInfoDoubleReply
      # Returns the value of the properties of the account
      # https://www.mql5.com/en/docs/account/accountinfointeger
      rpc :AccountInfoInteger, ::Mt5TermApi::AccountInfoIntegerRequest, ::Mt5TermApi::AccountInfoIntegerReply
      # Returns the value of the appropriate account property
      # https://www.mql5.com/en/docs/account/accountinfostring
      rpc :AccountInfoString, ::Mt5TermApi::AccountInfoStringRequest, ::Mt5TermApi::AccountInfoStringReply
    end

    Stub = Service.rpc_stub_class
  end
end
