# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mt5-term-api-subscriptions.proto for package 'mt5_term_api'

require 'grpc'
require 'mt5-term-api-subscriptions_pb'

module Mt5TermApi
  module SubscriptionService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mt5_term_api.SubscriptionService'

      # Streams real-time symbol tick data for the specified symbols.
      # Requires 'id' header with the terminal connection GUID returned by Connect.
      # Swagger does not support streaming — use /subscription-stream interactive viewer.
      # [DefaultValues]
      # {
      #   "symbolNames": "EURUSD,BTCUSD"
      # }
      rpc :OnSymbolTick, ::Mt5TermApi::OnSymbolTickRequest, stream(::Mt5TermApi::OnSymbolTickReply)
      # Streams real-time trade events (orders, positions, deals changes).
      # Requires 'id' header with the terminal connection GUID returned by Connect.
      # Swagger does not support streaming — use /subscription-stream interactive viewer.
      rpc :OnTrade, ::Mt5TermApi::OnTradeRequest, stream(::Mt5TermApi::OnTradeReply)
      # Streams real-time position profit updates at the specified timer interval.
      # Requires 'id' header with the terminal connection GUID returned by Connect.
      # Swagger does not support streaming — use /subscription-stream interactive viewer.
      rpc :OnPositionProfit, ::Mt5TermApi::OnPositionProfitRequest, stream(::Mt5TermApi::OnPositionProfitReply)
      # Streams real-time position and pending order ticket changes.
      # Requires 'id' header with the terminal connection GUID returned by Connect.
      # Swagger does not support streaming — use /subscription-stream interactive viewer.
      rpc :OnPositionsAndPendingOrdersTickets, ::Mt5TermApi::OnPositionsAndPendingOrdersTicketsRequest, stream(::Mt5TermApi::OnPositionsAndPendingOrdersTicketsReply)
      # Streams real-time trade transaction events (order add/update/delete, deal add, position changes).
      # Requires 'id' header with the terminal connection GUID returned by Connect.
      # Swagger does not support streaming — use /subscription-stream interactive viewer.
      rpc :OnTradeTransaction, ::Mt5TermApi::OnTradeTransactionRequest, stream(::Mt5TermApi::OnTradeTransactionReply)
    end

    Stub = Service.rpc_stub_class
  end
end
